<div id="centralized_RoomsConfig" hasform="true">
			<div class="centralized_RoomsConfig_C">
				<div class="a fl">
					<ul>
						<li class="head_TJ">房间信息</li>
						<li>总计：<span class="red">{{$room_count}}</span>间</li>
						<li>已配置：<span class="red">{{$room_config_count}}</span>间</li>
						<li>未配置：<span class="red">{{$no_config}}</span>间</li>
					</ul>
				</div>
				<div class="b fr">
					<ul>
						<li><span  class="checkBox checked"><span class="ifont1">&#xe60c;</span></span><a href="javascript:;" style="display: inline; margin: 0;">隐藏已配置房间</a><a parent_url="{{$parent_url}}"  href="javascript:;" class="btn btn2">保存</a></li>
					</ul>
				</div>
			</div>
			<div class="centralized_RoomsConfig_D">
				<div class="a">
					<div class="a_1">{{$flat_data.flat_name}}</div>
					<!--[if ie 6]>
					<div style="height: 0; overflow: hidden;"></div>
					<![endif]--> 
					<div class="a_2 fl">
						<ul>
						{{foreach from=$floor key=lk item=lv}}
							<li {{if $lk eq 0}}class="current"{{/if}}>
							{{foreach from=$lv.data key=lvk item=lvval}}
								<span class="floorNum">{{$lvval}}</span>{{if $lvk lt ($lv.data|@count)-1}}\{{/if}}
							{{/foreach}}
							
							<div class="floor_Detail">
								<dl>
								{{foreach from=$lv.count key=fk item=fv}}
									<dd><span class="name">已租：</span><span class="num">{{$fv.rent}}</span></dd>
									<dd><span class="name">未租：</span><span class="num">{{$fv.not_rent}}</span></dd>
									<dd><span class="name">预订：</span><span class="num">{{$fv.yd}}</span></dd>
									<dd><span class="name">停用：</span><span class="num">{{$fv.stop}}</span></dd>
									<dd><span class="name">预退：</span><span class="num">{{$fv.yytd}}</span></dd>
								{{/foreach}}
								</dl>
							</div>
							</li>
					{{/foreach}}
						</ul>
						<div class="clear"></div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="b">
					<ul>
					{{foreach from=$list_data key=listkey item=listval}}
						<li style="z-index:{{$listkey}};">
							<span class="floorNum fl"><span class="floor_Num">{{$listkey}}</span> 楼</span>
							<dl class="fl">
								{{foreach from=$listval key=lvkey item=lvval}}
								<dd {{if $lvval.room_id gt 0}} class="choosed"{{/if}}>
									<span class="romm_NUM fl">{{$lvval.custom_number}}</span>
									<span class="checkBox">
										<label {{if $lvval.template_id gt 0 and $lvval.template_id eq $template_id}}class="checked"{{/if}}><span class="gou ifont ifont1" {{if $lvval.template_id gt 0 and $lvval.template_id eq $template_id}}style="display: inline;"{{/if}}>&#xe60c;</span></label>
										<input {{if $lvval.template_id gt 0 and $lvval.template_id eq $template_id}}checked="checked"{{/if}} value="{{$lvval.room_focus_id}}" type="checkbox"/>
									</span>
									{{if $lvval.room_id gt 0}}<span class="room-configed"><p>配置名称：{{$lvval.template_name}}</p><p>房间户型：{{$lvval.house_type}}</p></span>{{/if}}
								</dd>
								{{/foreach}}
							</dl>
						</li>
					{{/foreach}}
					</ul>
				</div>
			</div>
</div>
