<!--集中式公寓-添加模板 s-->
<div is-edit='1' class="centralized_add_mode view" hasform="true">
	<div class="view-head">
		<h1>模板信息</h1>
		<b>[{{$flat_data.flat_name}}]</b>
	</div>
	<div class="view-con">
		<ul>
			<li><b> <i class="bit">*</i> 模板名称：
			</b> <input value="{{$template_data.template_name}}" type="text" class="ipt ipt-200 template_name" datatype="*,string40" nullmsg="请输入模板名称" errormsg = "模板名称不能超过40个字符"/></li>
			<li><b> <i class="bit">*</i> 房间租金：
			</b> <input value="{{$template_data.money}}" type="text" class="ipt ipt-160 rent_money" datatype="rentmoney" nullmsg="请输入房间租金" errormsg="房间租金格式不正确"/> <span class="ml5">元/月</span>
				<b class="dte-60"> <i class="bit">*</i> 房间户型：
			</b>
				<div class="selectByM">
					<input type="text" class="selectByMT centralized_Ind_CuteType room_type"
						readonly='readonly' selectVal='' value="房间户型" datatype="chooseGroup" choosenull="请选择房间户型"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$room_type key=tkey item=tval}}
								<li {{if $tkey eq $template_data.house_type}}class="selectedLi"{{/if}} selectVal='{{$tkey}}'>{{$tval}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div><span class="check-error check-error-ts"></span></li>
			<li><b> <i class="bit">*</i> 押付方式：
			</b> <span class="mr10">押</span>
				<div class="selectByM slt-70 mr10">
					<input type="text" class="selectByMT centralized_Ind_CuteType_Ya"
						readonly='readonly' selectVal='' value="" datatype="chooseGroup" choosenull="请选择押几"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$public_config key=pukey item=puval}}
							<li {{if $pukey eq $template_data.pledge_month}}class="selectedLi"{{/if}} selectVal='{{$pukey}}'>{{$puval}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div> <span class="mr10">付</span>
				<div class="selectByM slt-70">
					<input type="text" class="selectByMT centralized_Ind_CuteType_Fu"
						readonly='readonly' selectVal='' value=""  datatype="chooseGroup" choosenull="请选择付几"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$public_config key=pukey item=puval}}
							{{if $pukey neq 0}}
							<li {{if $pukey eq $template_data.pay_month}}class="selectedLi"{{/if}} selectVal='{{$pukey}}'>{{$puval}}</li>
							{{/if}}
						{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-60"> <i class="bit">*</i> 房间面积：
			</b> <input value="{{$template_data.area}}" type="text" class="ipt ipt-160 room_area" datatype = "float,gt0,lt999" nullmsg="请输入房间面积" errormsg = "房间面积应为整数或小数"/> <span class="ml5">平米</span>
			<span class="check-error check-error-ts"></span>
			</li>
			<li class="view-config"><b><i class="bit"></i>房间配置：</b>
				<div class="house-config">
					{{foreach from=$public_facilities key=fk item=fv}}
					<div class="check-box check-box-singel {{if $fv.name eq "飘窗" or $fv.name eq "阳台" or $fv.name eq "卫生间"}}canntchoose{{/if}}">
						<label {{if $fv.is_read eq 1}}class="checked"{{/if}}>
							<span {{if $fv.is_read eq 1}}style="display: inline;"{{/if}} class="choose ifont1">&#xe60c;</span>
						</label> 
						<input {{if $fv.is_read eq 1}}checked="checked"{{/if}} name="centralized_add_house_room_config" type="checkbox" value="{{$fv.value}}" /> 
						<span><a href="javascript:;">{{$fv.name}}</a></span>
					</div>
					{{/foreach}}
					<div class="check-box check-box-all">
						<label class="checkAll"><i class="choose ifont1">&#xe60c;</i></label>
						<span class="select-all"><a href="javascript:;">全选</a></span>
					</div>
					<div class="check-box roomconfig_diy">
						<a href="javascript:;" class="roomconfig_dy">自定义房间配置</a>
					</div>
					<div class="roomconfig-diy-txt">
						<div class="roomconfig-diy-txt-a">
							<ul>
								<li><label class='checkbox'><span class='choose ifont1'>&#xe60c;</span></label><a href="javascript:;">全选</a></li>
								<li><a url="{{'Company/addconfig'|url}}" href="javascript:;" class="config-auto-add">新增配置</a></li>
								<li><a href="javascript:;" url="{{'Company/deleteconfig'|url}}" class="config-auto-deleteall">删除配置</a></li>
								<li><a href="javascript:;" class="config-auto-submit">保存配置</a></li>
							</ul>
						</div>
						<ul class="roomconfig-diy-txt-auto">
							
						</ul>
					</div>
				</div></li>
			<li style="margin-bottom: 0;"><b style="margin-bottom: 0;"><i class="bit"></i>房间图片：</b><i class="notice-auto" style="color: red;margin-bottom: 0;">（建议上传真实、美观的房间图片，要求：jpg、gif、png格式，最多上传9张）</i></li>
			<li class="view-img">
				<div class="uploader-area" id="js-uploaderArea1">
					 {{foreach from=$imag key=imgkey item=imgval}}
				      		<div filename="{{$imgval.key}}" class="upload-imgview">
				      			<img class="" style="_display: none;" src="{{imageView2 op='w/60/h/60' key=$imgval.key}}">
				      			<span class="ie7bug"></span><i class="ifont deleteImg">&#xe627;</i>
				      			<input type="hidden" name="images[new][room1][]" value="{{$imgval.key}}">
				      		</div>
					 {{/foreach}}
					<div class="uploadview-wrapper">
						<div class="upload-group">
							<div id="queue"></div>
							<input id="file_upload1" name="file_upload" type="file">
						</div>
					</div>
				</div>
			</li>
			<li class="view-txt"><b><i class="bit"></i>备注说明：</b> 
				<textarea class="i-txt">{{$template_data.mark}}</textarea>
			</li>
			<li class="list-box"><b>已配置房间：</b>
				<div class="house-list" deledt-url={{'Centralized-FlatTemplate/deletroom'|url}}>
					<ul>
						<li class="config-house"><a  href="javascript:;" url="#{{'Centralized-FlatTemplate/configroom'|url|cat:'&'|cat:'template_id='|cat:$template_data.template_id|cat:'&'|cat:'flat_id='|cat:$flat_data.flat_id}}" class="goHouseConfig">配置房间</a></li>
						{{foreach from=$room_data key=rdkey item=rdval}}
						<li room-id="{{$rdval.room_focus_id}}" class="template_roomsconfig">
							<a href="javascript:;">{{$rdval.custom_number}}</a>
						</li>
						{{/foreach}}
						<!--当配置房间不只当前页时，换一批才可点击-->
						<li class="config-house" {{if $room_data|@count lt 10}}style="display: none"{{/if}}><a href="javascript:;" url="{{'Centralized-FlatTemplate/update'|url}}" class="exchangeTenplateConfigRooms">换一批</a></li>
							
						<!--当配置房间不只当前页时，换一批才可点击-->
					</ul>
				</div></li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" url="{{'Centralized-FlatTemplate/update'|url}}" class="btn btn2">保存</a> <a href="javascript:;" class="btn btn4 btn-cancel">取消</a>
		<div class="check-box">
			<label class="checked"><span style="display: inline;" class="choose ifont1">&#xe60c;</span></label> <input name="updata_room" checked="checked" type="checkbox"/> <span>更新房间</span>
		</div>
	</div>
</div>
<!--集中式公寓-添加模板 s-->

<!--多选删除遮罩模板-->
	<div class="deletemoreauto none">
		<div class="top">
			<div class="top1">
				<span class="fl">正在删除...</span>
				<span class="fr">
					<span class="num_cur">1</span>/<span class="num_total"></span>
				</span>
			</div>
			<div class="top2">
				<div class="top2a">
					<div class="top2at"></div>
				</div>
			</div>
		</div>
		<div class="content">
			<table>
				<tr><th class="zb">房间配置名称</th><th class="yb">删除结果</th></tr>
				<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
			</table>
		</div>
	</div>
