<link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-message.css" />
<!--首页 s-->
<div class="smart-msg">
	<!--头部 s-->
	<div class="smart-msg-head">
		<i></i>
		<a href="javascript:;">功能插件></a>
		<span>功能详情</span>
	</div>
	<!--头部 e-->

	<!--福利说明 s-->
	<div class="smart-msg-says">
		<h1>9月1日起，我们将给九猪各位新老用户陆续推出一系列的福利措施，第一波的福利就是给各位二房东赠送短信啦~</h1>
		<div class="sms-content">
			<b>九猪老用户</b>
			<p>规则：</p>
			<p>1.如果您是系统的老用户，并且在系统中存在1套以上的房源，我们将赠送给您300条的免费短信，帮助您避免在使用系统时产生额外支出。</p>
			<p>2.果您上月登录系统次数满足15次以上（含15次），我们还将继续赠送200条的免费短信，当月立即生效。（例：用户A在8月登陆SaaS系统18次，9月将会获得200条短信）。</p>
			<p class="red">时间：9月1日~10月31日</p>
		</div>
		<div class="sms-content">
			<b>九猪新用户</b>
			<p>规则：</p>
			<p>1.如果您是当月内注册的新用户的话，我们也将立即赠送您300条的免费短信，帮助您熟悉系统，避免额外的支出。</p>
			<p>2.如果您本月登录系统次数满足15次以上（含15次），我们将会在下个月赠送您200条的免费短信，下月生效。（例：用户B在9月注册了新账号且登陆SaaS系统18次，10月将会获得200条短信）。</p>
			<p class="red">时间：9月1日~10月31日</p>
		</div>
	</div>
	<!--福利说明 e-->


	<!--功能介绍 s-->
	<div class="smart-msg-introduce">
		<div class="title">
			<h1>智能短信服务</h1>
		</div>
		<div class="content open-tip">
			<p class="fl">开通该功能后，可设定短信模板、手动发送短信、智能发送短信、群发短信。</p>
			<div class="fr">
				<a href="javascript:;" data-url="{{'Plugins-Sms/open'|url}}" class="btn btn1 apply-open-act">我要开通</a>
			</div>
		</div>
		<div class="smi-mark">
			<p>您的账户截止目前总共已发送短信<span>5000</span>条，当月账户剩余免费短信<span>2000</span>条，充值短信<span>0</span>条，已发送<span>500</span>条，还剩<span>1500</span>条。</p>
			<p class="red">注：每月免费短信条数超过则需自行充值（8分钱/条），且免费短信当月未用完不累计至下月！</p>
		</div>
	</div>
	<!--功能介绍 e-->

	<!--开通短信功能前 s-->
	<div class="open-message-before open-message">
		<div class="title">
			<i class="ifont2">&#xe603;</i>
			<b>开通“智能短信服务”功能前</b>
		</div>
		<div class="img-box">
			<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_13.png" />
		</div>
	</div>
	<!--开通短信功能前 e-->

	<!--开通短信功能后 s-->
	<div class="open-message-after open-message">
		<div class="title">
			<i class="ifont2">&#xe603;</i>
			<b>开通“智能短信服务”功能后(效果图)</b>
		</div>
		<div class="img-box">
			<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_14.png" />
		</div>
		<div class="img-box mt20">
			<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_15.png" />
		</div>
	</div>
	<!--开通短信功能后 e-->
