<link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-message.css" />	
<!--首页 s-->
<div class="smart-msg">
	<!--头部 s-->
	<div class="smart-msg-head">
		<i></i>
		<a href="javascript:;">功能插件></a>
		<span>功能详情</span>
	</div>
	<!--头部 e-->

	<!--功能介绍 s-->
	<div class="smart-msg-introduce">
		<div class="title">
			<h1>智能短信服务</h1>
		</div>
		<div class="content">
			<p class="fl">开通该功能后，可设定短信模板、手动发送短信、智能发送短信、群发短信。</p>
			<div class="fr">
				<a href="javascript:;" class="btn btn1">我要充值</a><a href="javascript:;" class="btn btn4">我要关闭</a>
			</div>
		</div>
	</div>
	<!--功能介绍 e-->

	<!--tab导航 s-->
	<div class="smart-msg-nav">
		<ul>
			<li class="nav-mode current">
				<a href="javascript:;">短信模板</a>
				<i></i>
			</li>
			<li class="nav-condetion">
				<a href="javascript:;">智能短信</a>
				<i></i>
			</li>
			<li class="nav-send">
				<a href="javascript:;">短信群发</a>
				<i></i>
			</li>
			<li class="nav-send-record">
				<a href="javascript:;">短信发送记录</a>
				<i></i>
			</li>
			<li class="nav-recharge-record">
				<a href="javascript:;">充值记录</a>
				<i></i>
			</li>
		</ul>
	</div>
	<!--tab导航 e-->

	<!--短信模板 s-->
	<div class="msg-mode-box box">
		<!--tab内容 s-->
		<div class="smart-msg-content">
			<div class="title">
				<b>短信模板</b>
			</div>
			<div class="message-mode send-condetion">
				<ul>
					<li>
						<div class="send-condetion-title">
							<div class="sct-title">
								<b>租客签约提醒</b>
							</div>
							<div class="sct-tool del-box">
								<i class="ifont">&#xe675;</i>
								<span>删除</span>
							</div>
							<div class="sct-tool edit-box mr20">
								<i class="ifont">&#xe77d;</i>
								<span>编辑</span>
							</div>
						</div>
						<div class="message-mode-con">
							<p>尊敬的小张，您好，我是新怡花园小区3栋1单元1402的房东，我们约定07月03日签合同。若有变动，请联系15986866868。</p>
						</div>
						<div class="message-mode-total">
							<p>共101个字，将计为2条短信</p>
						</div>
					</li>
					<li>
						<div class="send-condetion-title">
							<div class="sct-title">
								<b>租客预定提醒</b>
							</div>
							<div class="sct-tool del-box">
								<i class="ifont">&#xe675;</i>
								<span>删除</span>
							</div>
							<div class="sct-tool edit-box mr20">
								<i class="ifont">&#xe77d;</i>
								<span>编辑</span>
							</div>
						</div>
						<div class="message-mode-con">
							<p>尊敬的小张，您好，我是新怡花园小区3栋1单元1402号的房东，感谢您预订蜜柚公寓，我们是专注于打造纯粹的女性公寓，追求简约优雅，格调统一，力求让租客找到回家的感觉。
电话：028-85939222</p>
						</div>
						<div class="message-mode-total">
							<p>共101个字，将计为2条短信</p>
						</div>
					</li>
					<li>
						<div class="send-condetion-title">
							<div class="sct-title">
								<b>租客已入住</b>
							</div>
							<div class="sct-tool del-box">
								<i class="ifont">&#xe675;</i>
								<span>删除</span>
							</div>
							<div class="sct-tool edit-box mr20">
								<i class="ifont">&#xe77d;</i>
								<span>编辑</span>
							</div>
						</div>
						<div class="message-mode-con">
							<p>尊敬的小张，您好，我是新怡花园小区3栋1单元1402号的房东，欢迎入住蜜柚公寓，我们为您提供最优质的房源，若有任何问题，请联系我们的客服15986866868。</p>
						</div>
						<div class="message-mode-total">
							<p>共101个字，将计为2条短信</p>
						</div>
					</li>
					<li class="li-spe">
						<div class="plus"></div>
						<span class="words">添加新模板</span>
					</li>
				</ul>
			</div>
		</div>
		<!--tab内容 e-->
	</div>
	<!--短信模板 e-->

	<!--智能短信 s-->
	<div class="msg-condetion-box box" style="display: none;">
		<!--tab内容 s-->
		<div class="smart-msg-content">
			<div class="title">
				<b>短信发送条件</b>
			</div>
			<div class="send-condetion">
				<div class="send-condetion-box">
					<div class="send-condetion-title">
						<div class="sct-tool del-box">
							<i class="ifont">&#xe675;</i>
							<span>删除</span>
						</div>
						<div class="sct-tool edit-box mr20">
							<i class="ifont">&#xe77d;</i>
							<span>编辑</span>
						</div>
					</div>
					<div class="send-condetion-fm">
						<div class="selectByM">
							<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="当添加预定人信息时" />
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
									<li selectVal='0'>当添加预定人信息时</li>
								</ul>
							</div>
						</div>
						<b class="scf-send">发送</b>
						<div class="selectByM">
							<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="当添加预定人信息时" />
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
									<li selectVal='0'>租客预约提醒</li>
								</ul>
							</div>
						</div>
						<b class="ml10">到手机租客</b>
					</div>
				</div>
				<div class="send-condetion-add">
					<i class="ifont2">&#xe601;</i>
					<span class="words">添加一条智能短信</span>
				</div>
			</div>
		</div>
		<!--tab内容 e-->
	</div>
	<!--智能短信 e-->

	<!--短途群发 s-->
	<div class="msg-send-box box" style="display: none;">
		<!--tab内容 s-->
		<div class="smart-msg-content">
			<div class="title">
				<b>短信群发</b>
			</div>
			<div class="message-send">
				<div class="message-send-fm">
					<div class="selectByM">
						<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="租房平台" />
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						<div class="selectByMO">
							<ul>
								<li selectVal='0'>租房平台</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="message-send-fm">
					<div class="selectByM">
						<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="租房平台" />
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						<div class="selectByMO">
							<ul>
								<li selectVal='0'>租房平台</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="message-send-fm">
					<div class="selectByM">
						<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="租房平台" />
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						<div class="selectByMO">
							<ul>
								<li selectVal='0'>租房平台</li>
							</ul>
						</div>
					</div>
					<span>共计<span>30</span>位客人</span>
				</div>
				<div class="message-send-fm">
					<div class="selectByM">
						<input type="text" class="selectByMT" readonly='readonly' selectVal='0' value="租房平台" />
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						<div class="selectByMO">
							<ul>
								<li selectVal='0'>租房平台</li>
							</ul>
						</div>
					</div>
					<span>预计发出<span>30</span>条短信</span>
				</div>
				<div class="message-send-fm">
					<a href="javascript:;" class="btn btn1">确认发送</a>
				</div>
			</div>
		</div>
		<!--tab内容 e-->
	</div>
	<!--短途群发 e-->

	<!--发送记录 s-->
	<div class="send-record-box box" style="display: none;">
		<!--tab内容 s-->
		<div class="smart-msg-content">
			<div class="title">
				<b>短信发送记录</b>
			</div>
			<table class="lst_tb">
				<tr>
					<th class="td_first">操作人</th>
					<th>发送方式</th>
					<th>接收号码</th>
					<th>短信模板</th>
					<th>发送条数</th>
					<th>发送时间</th>
				</tr>
				<tr>
					<td class="td_first">15984526589</td>
					<td>单发</td>
					<td>13256894589</td>
					<td>租客签约提醒</td>
					<td>1</td>
					<td>2015-06-23 17：13</td>
				</tr>
				<tr>
					<td class="td_first">15984526589</td>
					<td>群发</td>
					<td>13256894589</td>
					<td>租客签约提醒</td>
					<td>1</td>
					<td>2015-06-23 17：13</td>
				</tr>
			</table>
		</div>
		<!--tab内容 e-->

		<!--页码 s-->
		<div class="jzf-pagination clearfix">
			<div class="pagination" id="recharge-page"></div>
			<div class="jump-to-page clearfix">
				<span>跳转至</span>
				<div class="jump-edit-box">
		        	<input type="text" placeholder="页码" class="page">
		        	<a href="javascript:;" class="p-btn btn btn4">GO</a>
		        	<i class="page-unit">页</i>
		        </div>
			</div>
		</div>
		<!--页码 e-->
	</div>
	<!--发送记录 e-->

	<!--充值记录 s-->
	<div class="recharge-record-box box" style="display: none;">
		<!--tab内容 s-->
		<div class="smart-msg-content">
			<div class="title">
				<b>短信充值记录</b>
			</div>
			<table class="lst_tb">
				<tr>
					<th class="td_first">操作人</th>
					<th>充值金额</th>
					<th>短信条数</th>
					<th>充值时间</th>
				</tr>
				<tr>
					<td class="td_first">15984526589</td>
					<td>150.00</td>
					<td>450</td>
					<td>2015-06-23 17：13</td>
				</tr>
				<tr>
					<td class="td_first">15984526589</td>
					<td>150.00</td>
					<td>450</td>
					<td>2015-06-23 17：13</td>
				</tr>
			</table>
		</div>
		<!--tab内容 e-->

		<!--页码 s-->
		<div class="jzf-pagination clearfix">
			<div class="pagination" id="recharge-page"></div>
			<div class="jump-to-page clearfix">
				<span>跳转至</span>
				<div class="jump-edit-box">
		        	<input type="text" placeholder="页码" class="page">
		        	<a href="javascript:;" class="p-btn btn btn4">GO</a>
		        	<i class="page-unit">页</i>
		        </div>
			</div>
		</div>
		<!--页码 e-->
	</div>
	<!--充值记录 e-->

</div>
<!--首页 e-->

<!--编辑模板弹窗 s-->
<div class="hide-edit-mode" style="display: none;">
	<div class="edit-mode">
		<ul>
			<li>
				<b>模板名称：</b>
				<input type="text" class="ipt ipt-340" />
			</li>
			<li>
				<b>模板内容：</b>
				<textarea class="i-txt"></textarea>
			</li>
			<li class="ml80">
				<div class="check-box fl">
                    <label>
                        <i class="choose ifont1">&#xe60c;</i>
                    </label>
                    <input type="checkbox" value="" />
                    <span>我已阅读</span>
                </div>
                <a href="javascript:;" class="message-contract fl">短信内容条款</a>
			</li>
			<li class="ml80">
				<p>已输入101个字，将计为2条短信。</p>
			</li>
			<li class="li-btn ml80">
				<a href="javascript:;" class="btn btn1 mr30">恢复初始模板</a>
				<a href="javascript:;" class="btn btn1">保存</a>
			</li>
		</ul>
	</div>
</div>
<!--编辑模板弹窗 e-->

<!--合约条款弹窗 s-->
<div class="hide-treaty-article" style="display: none;">
	<div class="treaty-article">
		<h1>不利用短信平台制作、复制、发布、传播含有下列内容的信息：</h1>
		<p>1、不利用短信平台制作、复制、发布、传播含有下列内容的信息；</p>
		<p>2、危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</p>
		<p>3、损坏国家荣誉和利益的；</p>
		<p>4、煽动民族仇恨、民族歧视，破坏民族团结的；</p>
		<p>5、破坏国家民族宗教政策，宣扬邪教和封建迷信的；</p>
		<p>6、散布谣言，扰乱社会秩序，破坏社会稳定的；</p>
		<p>7、散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</p>
		<p>8、侮辱或者诽谤他人，侵害他人合法权益的；</p>
		<p>9、含有法律、行政法规禁止的其它内容的。</p>
	</div>
</div>
<!--合约条款弹窗 e-->

<!--敏感词汇 s-->
<div class="hide-sensitive-words" style="display: none;">
	<div class="sensitive-words">
		<i class="ifont2">&#xe602;</i>
		<p>对不起！您输入的短信内容包含有敏感词“共产党”、
“党员”，建议更改后重试！</p>
	</div>
</div>
<!--敏感词汇 e-->

<!--充值弹窗 s-->
<div class="hide-recharge" style="display: none;">
	<div class="recharge">
		<div class="recharge-fm">
			<ul>
				<li>
					<b>充值金额：</b>
					<input type="text" class="ipt ipt-340" />
					<span class="red">金额数为整数，短信0.08元/条</span>
				</li>
				<li>
					<b>合计金额：</b>
					<input type="text" class="ipt ipt-340" value="100.00" />
				</li>
			</ul>
		</div>
		<div class="recharge-bank">
			<ul>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon1"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon2"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon3"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon4"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon5"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon6"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon7"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon8"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon9"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon10"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon11"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon12"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon13"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon14"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon15"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon16"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon17"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon18"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon19"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon20"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon21"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon22"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon23"></div>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon24"></div>
				</li>
			</ul>
		</div>
		<div class="recharge-other recharge-bank">
			<ul>
				<li class="radio-box">
					<label class="radio"><i class="ifont r-default">&#xe612;</i><i class="ifont r-select">&#xe617;</i></label>
					<input type="radio" value=""  />
					<span>支付宝</span>
				</li>
				<li>
					<label>
						<i class="ifont r-default">&#xe612;</i>
						<i class="ifont r-select" style="display: none;">&#xe617;</i>
					</label>
					<input type="radio" />
					<div class="icon icon25"></div>
				</li>
			</ul>
		</div>
		<div class="recharge-btn">
			<a href="javascript:;" class="btn btn1">前去支付</a>
		</div>
	</div>
</div>
<!--充值弹窗 e-->
