	<div id="workerManage_Add" hasform="true">
		<div class="workerManage_Add">
			<div class="workerManage_Add_A">{{if $smarty.get.a eq 'edit'}}编辑员工{{else}}新增员工{{/if}}</div>
			<div class="workerManage_Add_B">
				<ul>
					<li><span class="name"><i class="bit">* </i>登录名&nbsp;:&nbsp;</span><input type="text" {{if !empty($userinfo) }}value="{{$userinfo.username}}" {{/if}} class="ipt" name="workerManage_Add_Id" datatype="*,string60" nullmsg = "请输入登录名" errormsg="登录名不能超过60个字符"/><span class="lst email_HZ">@{{$user.username}}</span><span class="check-error check-error-ts"></span></li>
					<li><span class="name"><i class="bit">* </i>密&nbsp;&nbsp;&nbsp;&nbsp;码&nbsp;:&nbsp;</span><input type="password" class="ipt" name="workerManage_Add_Psw" datatype="*6-18" nullmsg = "请输入密码" errormsg = "密码由6到18位字符组成" {{if $smarty.get.a eq 'edit'}}ignore="ignore"{{/if}}/><span class="check-error check-error-ts"></span></li>
					<li><span class="name"><i class="bit">* </i>姓&nbsp;&nbsp;&nbsp;&nbsp;名&nbsp;:&nbsp;</span><input type="text" class="ipt" {{if !empty($userinfo) }}value="{{$userinfo.uname}}" {{/if}} name="workerManage_Add_Name" datatype="*,string60" nullmsg = "请输入员工姓名" errormsg="员工姓名不能超过60个字符"/>
						<span class="lst">
							<label class="radio workerManage_Add_B_Radio"  {{if !empty($userinfo) && $userinfo.gender eq '1' }} checked="checked" {{/if}}>
							    {{if $smarty.get.a eq 'add'}}
							         <span class="notChoose ifont" style="display: none;">&#xe612;</span>
    								 <span class="choose ifont" style="display: inline;">&#xe617;</span>
								{{elseif !empty($userinfo) && $userinfo.gender eq '1' }}
    								 <span class="notChoose ifont" style="display: none;">&#xe612;</span>
    								 <span class="choose ifont" style="display: inline;">&#xe617;</span>
    							{{else}}
    								 <span class="notChoose ifont" style="display: inline;">&#xe612;</span>
    								 <span class="choose ifont" style="display: none;">&#xe617;</span>
								{{/if}}

							</label>
							{{if $smarty.get.a eq 'add'}}
							    <input type="radio" name="workerManage_Add_B_Radio_gender" value="1"  checked="checked"/>
							{{else}}
							    <input type="radio" name="workerManage_Add_B_Radio_gender" value="1"  {{if !empty($userinfo) && $userinfo.gender eq '1' }} checked="checked" {{/if}}/>
							{{/if}}
							<span>男</span>


							<label class="radio workerManage_Add_B_Radio"  {{if !empty($userinfo) && $userinfo.gender eq '0' }} checked="checked" {{/if}}>
								{{if !empty($userinfo) && $userinfo.gender eq '0' }}
    								 <span class="notChoose ifont" style="display: none;">&#xe612;</span>
    								 <span class="choose ifont" style="display: inline;">&#xe617;</span>
    							{{else}}
    							     <span class="notChoose ifont" style="display: inline;">&#xe612;</span>
    								 <span class="choose ifont" style="display: none;">&#xe617;</span>
								{{/if}}

							</label>
							<input type="radio" name="workerManage_Add_B_Radio_gender" value="0" {{if !empty($userinfo) && $userinfo.gender eq '0' }} checked="checked" {{/if}} />
							<span>女</span>
						</span>
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>

					<li><span class="name"><i class="bit">* </i>电&nbsp;&nbsp;&nbsp;&nbsp;话&nbsp;:&nbsp;</span><input type="text" class="ipt" {{if !empty($userinfo) }}value="{{$userinfo.contact}}" {{/if}} name="workerManage_Add_Tel" datatype="/^1\d{10}$/" nullmsg = "请输入员工联系电话" errormsg = "电话格式不正确"/><span class="check-error check-error-ts"></span></li>
					<li><span class="name fl"><i class="bit">* </i>分&nbsp;&nbsp;&nbsp;&nbsp;组&nbsp;:&nbsp;</span>
						<div class="selectByM">
							<input type="text" class="selectByMT centralized_Ind_CuteType"
								readonly='readonly' {{if !empty($userinfo) }} selectVal='{{$userinfo.group_id}}'{{else}}selectVal='' {{/if}}   {{if !empty($userinfo)}} value="{{$userinfo.name}} "{{else}} value='请选择分组' {{/if}}  name="workerManage_Add_GroupName" datatype="chooseGroup"/> <span
								class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
    								{{foreach from=$grouplist item=v}}
    								    <li selectVal='{{$v.group_id}}' {{if !empty($userinfo) && $userinfo.group_id eq $v.group_id }} class="selectedLi" {{/if}}>{{$v.name}}</li>
    								{{/foreach}}
								</ul>
							</div>
						</div><span class="check-error check-error-ts"></span></li>
					<li style="height: auto; overflow: hidden;"><span class="name fl"><i class="bit">&nbsp;&nbsp;</i>备&nbsp;&nbsp;&nbsp;&nbsp;注&nbsp;:</span><textarea class="ipx-txt" id="remark" datatype="string255" errormsg="备注不能超过255个字符">{{if !empty($userinfo) }}{{$userinfo.mark}} {{/if}}</textarea><span class="check-error check-error-ts"></span></li>
					<li class="lst"><button class="submite" url="{{if $smarty.get.a eq 'edit'}}{{"staffmanage-staff/edit"|url|cat:'&'|cat:'user_id'|cat:'='|cat:$userinfo.user_id}}{{else}}{{"staffmanage-staff/add"|url}}{{/if}}">{{if $smarty.get.a eq 'edit'}}保存{{else}}确定{{/if}}</button></li>
				</ul>
			</div>
		</div>
	</div>