<div id="workerManage_RoomManage" hasform="true">
	<div class="workerManage_RoomManage_A">
		<div class="a fl">
			<span class="name">分配房间</span>
			<span class="worker">员工：<span class="red">{{$staffinfo.uname}}</span></span>
		</div>
		<div class="b fr">
			<label><span class="choose ifont1">&#xe60c;</span></label>
			<a class="name" href="javascript:void(0);">隐藏已配置房间</a>
		</div>
	</div>
	<div class="workerManage_RoomManage_B">
		<div class="workerManage_RoomManage_B_a" url="{{"staffmanage-staff/allotlist/user_id/"|cat:$staffinfo['user_id']|cat:"/type/TYPE/area/AREA"|url}}">
			<ul>
				<!--集中式分散式混合-->
				<li class="jzfss">
					<div class="selectByM selectByM1">
						<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '{{if $login_user.company.isCentralized}}0{{else}}1{{/if}}' value="{{if $login_user.company.isCentralized}}集中式{{else}}分散式{{/if}}"/>
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						{{if $login_user.company.isCentralized and $login_user.company.isDispersive}}
						<div class="selectByMO">
							<ul>
								<li class="selectedLi" selectVal='0'>集中式</li>
								<li selectVal='1'>分散式</li>
							</ul>
						</div>
						{{/if}}
					</div>
					<div class="selectByM" style="display:none;">
						<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '' value="区域"/>
						<span class='jt_Ctr'><span class='jt_box'></span></span>
						<div class="selectByMO">
							<ul>
								{{foreach from=$area key=key item=val}}
								<li selectVal="{{$val.area_id}}">{{$val.name}}</li>
								{{/foreach}}
							</ul>
						</div>
					</div>
				</li>
				<li>
					<label class="chooseHouses"><i class="ifont1">&#xe60c;</i></label><a href="javascript:;" class="checkAllHouses">全选</a>
				</li>
			</ul>
		</div>
		<div class="workerManage_RoomManage_B_b">
            
            
			<!-- 
			<li>
				<span class="name">保利心语</span><span class="checkBox"><label class="ifont1">&#xe60c;</label><input type="checkbox"/></span>
			</li>
			<li class="choose">
				<span class="name">保利心语</span><span class="checkBox checked"><label class="ifont1">&#xe60c;</label><input type="checkbox" checked="checked"/></span>
				<div class="choosed_Detail">
					已分配给：王晓晓
				</div>
			</li>
			 -->
			<ul>
				
			</ul>
			<div class="li_Submite">
				<button class="submite btn btn2" url="{{'staffmanage-staff/saveallot/user_id/'|cat:$staffinfo['user_id']|cat:'/type/TYPE/area/AREA'|url}}">保存</button>
			</div>
		</div>
	</div>
</div>
