{{if $view == 'template'}}
    <div id="workerManage_Ind">
		<div class="workerManage_Ind_a">
			<div class="a fl">
				<ul>
					<li class="checkAllBox"><label class="checkAll"><span
							class="ifont ifont1">&#xe60c;</span></label><a href="javascript:;">全选</a></li>
					<li class="fzManage"><a
						href="#{{'Staffmanage-Group/list'|url}}" class="btn-auto-new"><span class="ifont ifont1 green">&#xe6ac;</span>分组管理</a></li>
					<li class="addWorkers"><a
						href="#{{'Staffmanage-staff/add'|url}}" class="btn-auto-new"><span class="ifont ifont1 blue">&#xe6d4;</span>新增成员</a></li>
					<li class="a_delete"><span class="ifont">&#xe675;</span><a href="javascript:;" class="delete_workerManage_Ind" deURL="{{'Staffmanage-Staff/delete'|url}}">删除</a></li>
				<!-- 	<li class="print"><span class="ifont ifont1">&#xe65e;</span><a
						href="javascript:;">打印</a></li> -->
					<li class="giveUpCheck"><span class="x_giveUpCheck">x</span><a
						href="javascript:;">取消</a></li>
				</ul>
			</div>
			<div class="b fr">
				<span class="fl num_worker_autospan">员工人数：<span class="num_worker_auto">{{$count}}</span></span>
				<input type="text" class="fl search_Txt" placeholder="姓名/联系电话/所住品牌"/>
				<a href="javascript:;" class="search_workerManage_Ind"><span class="ifont">&#xe645;</span></a>
			</div>
		</div>
		<div class="workerManage_Ind_b">
			<table>
				<tr>
					<th class="first_T" width="10%"></label>姓名</th>
					<th width="10%">联系电话</th>
					<th width="10%">分组</th>
					<th width="34%">管理间数</th>
					<th width="22%">添加时间</th>
					<th width="14%">操作</th>
				</tr>
{{/if}}
{{if $view == 'data'}}
				{{foreach from=$staffList key=k item=v}}
				<tr  uid="{{$v.user_id}}">
					<td class="first_T"><label
						class="workerManage_Ind_checkBox checkBox"><span
							class="gou ifont ifont1">&#xe60c;</span><input type="checkbox" /></label><span class="workername">{{$v.staffname}}</span></td>
					<td>{{$v.contact}}</td>
					<td>{{$v.groupname}}</td>
					<td>
						{{if isset($v.community_count)}}小区{{$v.community_count}}
							(
							{{if isset($v.all_house_count)}}整租{{$v.all_house_count}}套{{/if}}
							{{if isset($v.all_house_count) and isset($v.all_room_count)}}、{{/if}}
							{{if isset($v.all_room_count)}}合租{{$v.all_room_count}}套{{/if}}
							)
						{{/if}}
						{{if isset($v.flat_data)}}
							公寓{{$v.flat_data}}
							{{if isset($v.room_focus_count)}}
								({{$v.room_focus_count}}间)
							{{/if}}
						{{/if}}
					</td>
					<td>{{if $v.create_time gt 0}}{{$v.create_time|date_format:'%Y-%m-%d'}}{{elseif $v.create_time lte 0}}0{{/if}}</td>
					<td>
						<ul>
							<li class="first"><a href="#{{'Staffmanage-Staff/edit'|url|cat:'&'|cat:'user_id'|cat:'='|cat:$v.user_id}}">查看</a></li>
							<li><a href="#{{'Staffmanage-Staff/allotHouse'|url|cat:'&'|cat:'staff_id'|cat:'='|cat:$v.user_id}}">分配</a></li>
							<li class="last"><a href="javascript:;" class="delete_LineTab" deURL="{{'Staffmanage-Staff/delete'|url}}">删除</a></li>
						</ul>
					</td>
				</tr>
				{{/foreach}}
{{/if}}
{{if $view == 'template'}}
			</table>
			<div class="jzf-pagination clearfix" url="{{'staffmanage-staff/list/view_type/data'|url}}">
				<div class="pagination" id="workerManage_Ind_b_fy"></div>
				<div class="jump-to-page clearfix">
					<span>跳转至</span>
					<div class="jump-edit-box">
						<input type="text" placeholder="页码"> <a href="javascript:;"
							class="p-btn btn btn4">GO</a> <i class="page-unit">页</i>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--多选删除遮罩模板-->
	<div class="deletemoreauto none">
		<div class="top">
			<div class="top1">
				<span class="fl">正在删除...</span>
				<span class="fr">
					<span class="num_cur">1</span>/<span class="num_total"></span>
				</span>
			</div>
			<div class="top2">
				<div class="top2a">
					<div class="top2at"></div>
				</div>
			</div>
		</div>
		<div class="content">
			<table>
				<tr><th class="zb">房间名称</th><th class="yb">删除结果</th></tr>
				<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
			</table>
		</div>
	</div>
	<div class="staff_List none">
        <div class="empty">
        	<div class="empty-main">
        		<img src="/web/images/03.png" />
        		<p>当前页面没有任何数据，请<a href="#/index.php?c=staffmanage-staff&a=add">点击这里添加</a>！</p>
        	</div>
        </div>
    </div>
{{/if}}
