<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http：//www.w3.org/TR/html4/strict.dtd">

<html xmlns="http：//www.w3.org/1999/xhtml" lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=10,IE=9">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>找回密码</title>
		<script type="text/javascript">
        	window.APP_WEB = window.APP_WEB || {};
        	window.APP_WEB.CONST = window.APP_WEB.CONST || {};
        	window.APP_WEB.CONST.VERSION = window.APP_WEB.CONST.VERSION || '{{$smarty.const.APP_WEB_VERSION}}';
        </script>
		<link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/view.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
		<link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/dialog/artDialog/ui-dialog.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
		<script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js?v={{$smarty.const.APP_WEB_VERSION}}" type="text/javascript" charset="utf-8"></script>
		<script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js?v={{$smarty.const.APP_WEB_VERSION}}" type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript">
			seajs.use("application_Js/recovery_pwdJs");
		</script>
	</head>
	<body>
		<!--顶部条 s-->
		<div class="top-nav">
			<div class="top-nav-con">
				<a href="{{'index'|url}}" class="logo">
					<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/logo-small.png?v={{$smarty.const.APP_WEB_VERSION}}"/>
				</a>
				<span class="top-nav-r"><a href="{{'user-login'|url}}">已有账号，点击这里直接登录</a></span>
			</div>
		</div>
		<!--顶部条 e-->
		
		<!--找回密码 s-->
		<div class="recovery-pwd">
			<div class="recovery-pwd-head">
				<ul>
					<li class="current">
						<span>1</span>
						<b>确认账号</b>
					</li>
					<li>
						<i class="ifont">&#x3464;</i>
					</li>
					<li>
						<span>2</span>
						<b>重置密码</b>
					</li>
					<li>
						<i class="ifont">&#x3464;</i>
					</li>
					<li class="vh-r">
						<span>3</span>
						<b>完成</b>
					</li>
				</ul>
			</div>
			<div class="recovery-pwd-con recovery-pwd-con-step1">
				<form class="step_form_01" action="{{'common-verification/check'|url}}" target="formIframe">
				<ul>
					<li>
						<input type="text" class="ipt ipt-230 accountTxt" id="phone" errormsg="手机号格式错误" datatype="/^1\d{10}$/" nullmsg="请输入手机号" name="phone" placeholder="输入手机号" value="" />
						<div class="msgWrap">
							<div class="ermsg-tip">
								<i class="ico-arrow-l"></i>
								<i class="msgTxt"></i>
							</div>
						</div>
					</li>
					<li>
						<input type="text" id="img_code" class="ipt ipt-125 accountTxt" errormsg="" datatype="*" nullmsg="请输入验证码" name="img_code" placeholder="验证码" value="" />
						<a href="javascript:;" class="img-code">
							<img src="/index.php?c=common-imagecaptcha&a=show&width=98&height=30"/>
						</a>
						<div class="msgWrap">
							<div class="ermsg-tip">
								<i class="ico-arrow-l"></i>
								<i class="msgTxt"></i>
							</div>
						</div>
					</li>
					<li>
						<input type="text" id="phone_code" class="ipt ipt-125 accountTxt" errormsg="" datatype="*" nullmsg="请输入校验码" name="code" placeholder="校验码" value="" />
						<a href="javascript:;" class="get-code" url="{{'common-verification/sendtouser'|url}}">获取校验码</a>
						<!--<a href="javascript:;" class="get-code current">60秒后获取</a>-->
						<div class="msgWrap">
							<div class="ermsg-tip">
								<i class="ico-arrow-l"></i>
								<i class="msgTxt"></i>
							</div>
						</div>
					</li>
					<li>
						<input type="submit" id="sub_step1" class="btn btn1 recovery-pwd-conStep1"/>
						<!--<a href="javascript:;" id="sub_step1" class="btn btn1 recovery-pwd-conStep1" url="">下一步</a>-->
					</li>
				</ul></form>
			</div>
			<div class="recovery-pwd-con recovery-pwd-con-step2">
				<form action="{{'user-retrieve/save'|url}}" target="formIframe" class="step_form_02">
				<ul>
					<li>
						<input type="password" class="ipt ipt-230 accountTxt" id="npwd" datatype="*6-16" nullmsg="请输入新密码！" errormsg="密码范围在6~16位之间！" name="passwd" placeholder="请输入新密码" value="" />
						<div class="msgWrap">
							<div class="ermsg-tip">
								<i class="ico-arrow-l"></i>
								<i class="msgTxt"></i>
							</div>
						</div>
					</li>
					<li>
						<input type="password" class="ipt ipt-230 accountTxt" id="cfnpwd" datatype="*6-16" recheck="passwd" nullmsg="请再输入一次密码！" errormsg="您两次输入的密码不一致！" name="cfm_passwd" placeholder="请再输入一次密码" value="" />
						<div class="msgWrap">
							<div class="ermsg-tip">
								<i class="ico-arrow-l"></i>
								<i class="msgTxt"></i>
							</div>
						</div>
					</li>
					<li>
						<!--<a href="javascript:;" class="btn btn1 recovery-pwd-conStep2" url="">下一步</a>-->
						<input type="submit" id="step_last" value="下一步" class="btn btn1 recovery-pwd-conStep2" />
					</li>
				</ul>
				</form>
			</div>
			<div class="recovery-pwd-con recovery-pwd-con-step3" url="{{'index/index'|url}}">
				<ul>
					<li class="suc-btn">
						<i class="ifont1">&#xe617;</i>
					</li>
					<li class="suc-word">
						<p>恭喜您！您的新密码已经设置完成，页面将在 <span class="timer">3</span>秒后自动跳转！</p>
					</li>
				</ul>
			</div>
		</div>
		<!--找回密码 e-->
		<iframe name="formIframe" style="display: none;"></iframe>
		
	</body>
</html>