
<!--集中式公寓-添加房间 s-->
<div class="centralized_add_house view" hasform="true">
	<div class="view-head">
		<h1>房间信息</h1>
	</div>
	<div class="view-con">
		<ul>
			<li><b><i class="bit">*</i>公寓名称：</b> <span>{{$flatInfo.flat_name}}</span></li>
			<li><b><i class="bit">*</i>房间编号：</b> 
			<input name="centralized_add_house_custom_number" type="text" class="ipt ipt-200" datatype="n,house_num" nullmsg="请输入房间编号" errormsg="房源编号应为8位内大于0正整数"/> 
			<b class="dte-60"><i class="bit">*</i>房间户型：</b>
				<div class="selectByM">
					<input name="centralized_add_house_room_type" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='' value="" datatype="*,chooseGroup" nullmsg="请选择房间户型"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$focus_room_type key=k item=v}}
							<li selectVal='{{$k}}'>{{$v}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div><span class="check-error check-error-ts"></span></li>
			<li><b><i class="bit">*</i>房间租金：</b> 
			<input name="centralized_add_house_money" type="text"class="ipt ipt-160" datatype="rentmoney" nullmsg = "请输入房间租金" errormsg = "请输入整数或小数"/> <span class="ml5">元/月</span> 
			<b class="dte-60"><i class="bit">*</i>房间面积：</b> 
			<input name="centralized_add_house_area" type="text" class="ipt ipt-160" datatype="float,gt0,lt999" nullmsg = "请输入房间面积" errormsg = "请输入整数或小数"/> <span class="ml5">平米</span><span class="check-error check-error-ts"></span></li>
			<li><b><i class="bit">*</i>计费方式：</b> <span class="mr10">押</span>
				<div class="selectByM slt-70 mr5">
					<input name="centralized_add_house_detain" type="text" class="selectByMT centralized_Ind_CuteType" readonly='readonly' selectVal='' value="" datatype="*,chooseGroup" nullmsg="请选择押几"/> 
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='0'>零</li>
							<li selectVal='1'>一</li>
							<li selectVal='2'>二</li>
							<li selectVal='3'>三</li>
							<li selectVal='4'>四</li>
							<li selectVal='6'>五</li>
							<li selectVal='6'>六</li>
							<li selectVal='7'>七</li>
							<li selectVal='8'>八</li>
							<li selectVal='9'>九</li>
							<li selectVal='10'>十</li>
							<li selectVal='11'>十一</li>
							<li selectVal='12'>十二</li>
						</ul>
					</div>
				</div> <span class="mr10 ml5">付</span>
				<div class="selectByM slt-70">
					<input name="centralized_add_house_pay" type="text" class="selectByMT centralized_Ind_CuteType" readonly='readonly' selectVal='' value="" datatype="*,chooseGroup" nullmsg="请选择付几"/> 
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='1'>一</li>
							<li selectVal='2'>二</li>
							<li selectVal='3'>三</li>
							<li selectVal='4'>四</li>
							<li selectVal='6'>五</li>
							<li selectVal='6'>六</li>
							<li selectVal='7'>七</li>
							<li selectVal='8'>八</li>
							<li selectVal='9'>九</li>
							<li selectVal='10'>十</li>
							<li selectVal='11'>十一</li>
							<li selectVal='12'>十二</li>
						</ul>
					</div>
				</div> <b class="dte-60"><i class="bit">*</i>所在楼层：</b>
					<input name="centralized_add_house_floor" type="text" class="ipt ipt-160" datatype="s1-3" nullmsg="请输入所在楼层" errormsg = "所在楼层数不超过三位"/>
						<span class="check-error check-error-ts"></span></li>
			<li class="view-config"><b><i class="bit"></i>房间配置：</b>
				<div class="house-config">
					{{foreach from=$public_facilities key=fk item=fv}}
					<div class="check-box check-box-o {{if $fv eq "飘窗" or $fv eq "阳台" or $fv eq "卫生间"}}canntchoose{{/if}}">
						<label><span class="choose ifont1">&#xe60c;</span></label> <input name="centralized_add_house_room_config" type="checkbox" value="{{$fk}}" /> <span><a href="javascript:;">{{$fv}}</a></span>
					</div>
					{{/foreach}}
					<div class="check-box check-box-a">
						<label class="checkAll"><span class="choose ifont1">&#xe60c;</span></label>
						<span class="select-all"><a href="javascript:;">全选</a></span>
					</div>
					<div class="check-box roomconfig_diy">
						<a href="javascript:;" class="roomconfig_dy">自定义房间配置</a>
					</div>
					<div class="roomconfig-diy-txt">
						<div class="roomconfig-diy-txt-a">
							<ul>
								<li><label class='checkbox'><span class='choose ifont1'>&#xe60c;</span></label><a href="javascript:;">全选</a></li>
								<li><a url="{{'Company/addconfig'|url}}" href="javascript:;" class="config-auto-add">新增配置</a></li>
								<li><a href="javascript:;" url="{{'Company/deleteconfig'|url}}" class="config-auto-deleteall">删除配置</a></li>
								<li><a href="javascript:;" class="config-auto-submit">保存配置</a></li>
							</ul>
						</div>
						<ul class="roomconfig-diy-txt-auto">
							
						</ul>
					</div>
				</div></li>
			<li style="margin-bottom: 0;">
				<b style="margin-bottom: 0;"><i class="bit"></i>房间照片：</b>
				<i style="color: red; margin-bottom: 0;">（请上传真实，美观的房间图片，要求：jpg、gif、png格式，最多上传9张）</i>
			</li>
			<li class="view-img">
				<div class="uploader-area" id="js-uploaderArea">
		        	<div class="uploadview-wrapper">
		                <div class="upload-group">
		                    <div id="queue"></div>
		                    <input id="file_upload" name="file_upload" type="file">
		                </div>
		            </div>
		        </div>
			</li>
		</ul>
	</div>

	<div class="view-con view-cost dpt-fee-list">
		<ul>
		
			<li class="forclone" style="display: none;"><b>费用名称：</b>
				<div class="selectByM slt-100" hasevent="true">
					<input type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='' value="费用选择"  name="feechoose" datatype="chooseGroup" choosenull="请选择费用类型"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$fee_type key=fk item=fv}}
							<li selectVal='{{$fv.fee_type_id}}'>{{$fv.type_name}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">计费方式：</b>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='' value="计费选择" name="jfeechoose" datatype="chooseGroup" choosenull="请选择计费方式"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$pay_config key=pkey item=pval}}
							 <li selectVal='{{$pkey}}'>{{$pval}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">收费单价：</b> <input type="text" value=""
				 class="ipt ipt-80" name="money" datatype="float,price-singel" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> <i class="ifont">&#xe675;</i>
						<a href="javascript:;" class="forclonedelete">删除</a>
						<span class="check-error check-error-ts"></span>
			</li>
			
			{{foreach from=$fee_data key=fkey item=fval}}
			<li  class="forcloneauto">
				<b>费用名称：</b>
				<div class="selectByM slt-100" hasevent="true">
					<input name="feechoose" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='{{$fval.fee_type_id}}' value="电费" /> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$fee_type key=ftkey item=ftval}}
							<li {{if $fval.fee_type_id eq $ftval.fee_type_id}}class="selectedLi"{{/if}} selectVal='{{$ftval.fee_type_id}}'>{{$ftval.type_name}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">计费方式：</b>
				<div class="selectByM slt-100">
					<input name="jfeechoose" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='{{$fval.payment_mode}}' value="" /> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$pay_config key=pkey item=pval}}
								<li {{if $fval.payment_mode eq $pkey}}class="selectedLi"{{/if}} selectVal='{{$pkey}}'>{{$pval}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">收费单价：</b> 
				<input name="money" type="text" value="{{$fval.money}}" class="ipt ipt-80" datatype="float,price-singel" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> 
				<i class="ifont">&#xe675;</i><a href="javascript:;" class="forclonedelete">删除</a>
				<span class="check-error check-error-ts"></span>
			</li>
			{{/foreach}}
			<li class="view-add-cost">
				<i class="ifont mr5">&#xf0037;</i> 
				<a href="javascript:;" class="dpt-add-btn-auto" title="除租金、定金、押金外如有其他费用可在此处添加">添加费用</a>
				<i style="color: red;">（除房屋租金、押金、定金外的其他费用,如服务费、保洁费等）</i>
			</li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" url="{{'Centralized-Roomfocus/add'|url}}" class="btn btn2">保存</a> <a href="javascript:;" class="btn btn4 btn-cancel">取消</a>
		<div class="check-box add-continue">
			<label><span class="choose ifont1">&#xe60c;</span></label><input type="checkbox" value="continue" /><span>继续添加</span>
		</div>
	</div>
</div>
<!--集中式公寓-添加房间 e-->
<!--多选删除遮罩模板-->
	<div class="deletemoreauto none">
		<div class="top">
			<div class="top1">
				<span class="fl">正在删除...</span>
				<span class="fr">
					<span class="num_cur">1</span>/<span class="num_total"></span>
				</span>
			</div>
			<div class="top2">
				<div class="top2a">
					<div class="top2at"></div>
				</div>
			</div>
		</div>
		<div class="content">
			<table>
				<tr><th class="zb">房间配置名称</th><th class="yb">删除结果</th></tr>
				<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
			</table>
		</div>
	</div>
