
<!--集中式公寓-添加房间 s-->
<div class="centralized_add_house view" flat-id="{{$flatInfo.flat_id}}" is-edit="true" hasform="true">
	<div class="view-head">
				<h1>房间信息</h1>
				<span class="{{if $roomFocusInfo.status eq 1}}red{{/if}}{{if $roomFocusInfo.status eq 2}}blue{{/if}} {{if $roomFocusInfo.status eq 3}}black{{/if}}" style="margin-right: 10px;">
					  {{if $roomFocusInfo.status eq 1}}未租{{/if}}
					  {{if $roomFocusInfo.status eq 2}}已租{{/if}}
					  {{if $roomFocusInfo.status eq 3}}停用{{/if}}
				</span>
				{{if $roomFocusInfo.is_yytz == 1}}
				<span class="{{if $roomFocusInfo.status eq 1}}red{{/if}}{{if $roomFocusInfo.status eq 2}}yellow{{/if}} {{if $roomFocusInfo.status eq 3}}black{{/if}}" style="margin-right: 10px;">
					预约退租
				</span>
				{{/if}}
				{{if $fee_show eq 1 and $rental_data.contract_id gt 0}}
				<a href="#{{'MeterReading/index'|url|cat:'&room_id='|cat:$roomFocusInfo.room_focus_id|cat:'&house_id=0'|cat:'&house_type=2'}}">抄表</a>
				{{/if}}
				{{if $rental_data.contract_id gt 0}}
				<a href="#{{'finance-serial/newaddincome'|url|cat:'&room_id='|cat:{{$roomFocusInfo.room_focus_id}}|cat:'&house_type=2'|cat:'&charge_contract_id='|cat:$rental_data.contract_id|cat:'&charge_source=room_charge'}}">收费</a>
				{{/if}}
				{{if $roomFocusInfo.status eq 3}}
				<a href="javascript:;" stop-id="{{$stop_house_data.stop_id}}" list-url="{{'Centralized-Roomfocus/index'|url|cat:'&flat_id='|cat:$roomFocusInfo.flat_id}}" recover-url="{{'Centralized-Roomfocus/recover'|url|cat:'&room_id='|cat:$roomFocusInfo.room_focus_id}}" url="{{'Centralized-Roomfocus/getstop'|url}}" stop-url="{{'Centralized-Roomfocus/editstop'|url}}" class="edite-auto-stop">停用</a>
				{{/if}}
				{{if $roomFocusInfo.status eq 2}}
				<a href="#{{'tenant-index/edit'|url|cat:'&'|cat:'contract_id='|cat:$rental_data.contract_id}}">合同</a>
				{{/if}}
				{{if $roomFocusInfo.is_yd eq 1}}
                <a href="#{{'tenant-index/reserve'|url|cat:'&room_id='|cat:$roomFocusInfo.room_focus_id|cat:'&house_type=2'|cat:'&reserve_id='|cat:$resver_data.reserve_id}}">预定</a>
				{{/if}}
				{{if $roomFocusInfo.is_yytz eq 1}}
                <a href="javascript:;" class="yytz-room"  room_id="{{$roomFocusInfo.room_focus_id}}" reser_back_id="{{$reserve_back_info.reserve_back_id}}" data-url="{{'centralized-roomfocus/getyytzu'|url|cat:"&room_id="|cat:$roomFocusInfo.room_focus_id}}">预约退租</a>
				{{/if}}
	</div>
	<div class="view-con">
		<ul>
			<li><b><i class="bit">*</i>公寓名称：</b> <span>{{$flatInfo.flat_name}}</span></li>
			<li><b><i class="bit">*</i>房间编号：</b> 
			<input name="centralized_add_house_custom_number" type="text" class="ipt ipt-200" value="{{$roomFocusInfo.custom_number}}" datatype="n,house_num" nullmsg="请输入房间编号" errormsg="房源编号应为8位内大于0正整数"/> 
			<b class="dte-60"><i class="bit">*</i>房间户型：</b>
				<div class="selectByM">
					<input name="centralized_add_house_room_type" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='{{$roomFocusInfo.room_type}}' value="房间户型"  datatype="*,chooseGroup" nullmsg="请选择房间户型"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$focus_room_type key=k item=v}}
							<li {{if $k eq $roomFocusInfo.room_type}}class="selectedLi"{{/if}} selectVal='{{$k}}'>{{$v}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div><span class="check-error check-error-ts"></span></li>
			<li><b><i class="bit">*</i>房间租金：</b> 
			<input name="centralized_add_house_money" type="text"class="ipt ipt-160" value="{{$roomFocusInfo.money}}" datatype="rentmoney" nullmsg = "请输入房间租金" errormsg = "请输入整数或小数"/> <span class="ml5">元/月</span> 
			<b class="dte-60"><i class="bit">*</i>房间面积：</b> 
			<input name="centralized_add_house_area" type="text" class="ipt ipt-160" value="{{$roomFocusInfo.area}}" datatype="float,gt0,lt999" nullmsg = "请输入房间面积" errormsg = "请输入整数或小数"/> <span class="ml5">平米</span><span class="check-error check-error-ts"></span></li>
			<li><b><i class="bit">*</i>计费方式：</b> <span class="mr10">押</span>
				<div class="selectByM slt-70 mr5">
					<input name="centralized_add_house_detain" type="text" class="selectByMT centralized_Ind_CuteType" readonly='readonly' selectVal='{{$roomFocusInfo.detain}}' value="几" datatype="*,chooseGroup" nullmsg="请选择押几"/> 
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$house_public_config key=hkey item=hval}}
							<li {{if $hkey eq $roomFocusInfo.detain}}class="selectedLi"{{/if}}selectVal='{{$hkey}}'>{{$hval}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div> <span class="mr10 ml5">付</span>
				<div class="selectByM slt-70">
					<input name="centralized_add_house_pay" type="text" class="selectByMT centralized_Ind_CuteType" readonly='readonly' selectVal='{{$roomFocusInfo.pay}}' value="几" datatype="*,chooseGroup" nullmsg="请选择付几" /> 
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$house_public_config key=hkey item=hval}}
							{{if $hkey neq 0}}
							<li {{if $hkey eq $roomFocusInfo.pay}}class="selectedLi"{{/if}}selectVal='{{$hkey}}'>{{$hval}}</li>
							{{/if}}
						{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-60"><i class="bit">*</i>所在楼层：</b>
				<input value="{{$roomFocusInfo.floor}}" name="centralized_add_house_floor" type="text" class="ipt ipt-160" datatype="s1-3" nullmsg="请输入所在楼层" errormsg = "所在楼层数不超过三位"/>
				<span class="check-error check-error-ts"></span>
				</li>
			<li class="view-config"><b><i class="bit"></i>房间配置：</b>
				<div class="house-config">
					{{foreach from=$public_facilities key=fk item=fv}}
					<div class="check-box check-box-o {{if $fv.name eq "飘窗" or $fv.name eq "阳台" or $fv.name eq "卫生间"}}canntchoose{{/if}}">
						<label {{if $fv.is_read eq 1}}class="checked"{{/if}}><span class="choose ifont1" {{if $fv.is_read eq 1}}style="display: inline;"{{/if}}>&#xe60c;</span></label> 
						<input {{if $fv.is_read eq 1}}checked="checked"{{/if}} name="centralized_add_house_room_config" type="checkbox" value="{{$fv.value}}" /> 
						<span><a href="javascript:;">{{$fv.name}}</a></span>
					</div>
					{{/foreach}}
					<div class="check-box check-box-a">
						<label class="checkAll"><span class="choose ifont1">&#xe60c;</span></label>
						<span class="select-all"><a href="javascript:;">全选</a></span>
					</div>
					<div class="check-box roomconfig_diy">
						<a href="javascript:;" class="roomconfig_dy">自定义房间配置</a>
					</div>
					<div class="roomconfig-diy-txt">
						<div class="roomconfig-diy-txt-a">
							<ul>
								<li><label class='checkbox'><span class='choose ifont1'>&#xe60c;</span></label><a href="javascript:;">全选</a></li>
								<li><a url="{{'Company/addconfig'|url}}" href="javascript:;" class="config-auto-add">新增配置</a></li>
								<li><a href="javascript:;" url="{{'Company/deleteconfig'|url}}" class="config-auto-deleteall">删除配置</a></li>
								<li><a href="javascript:;" class="config-auto-submit">保存配置</a></li>
							</ul>
						</div>
						<ul class="roomconfig-diy-txt-auto">
							
						</ul>
					</div>
				</div></li>
				<li style="margin-bottom: 0;">
				<b style="margin-bottom: 0;"><i class="bit"></i>房间照片：</b>
				<i style="color: red; margin-bottom: 0;">（请上传真实，美观的房间图片，要求：jpg、gif、png格式，最多上传9张）</i>
			</li>
			<li class="view-img">
				<div class="uploader-area" id="js-uploaderArea-auto100">
					{{foreach from=$imag key=imgkey item=imgval}}
					      		<div filename="{{$imgval.key}}" class="upload-imgview">
					      			<img class="" style="_display: none;" src="{{imageView2 op='w/60/h/60' key=$imgval.key}}">
					      			<span class="ie7bug"></span><i class="ifont deleteImg">&#xe627;</i>
					      			<input type="hidden" name="images[new][room1][]" value="{{$imgval.key}}">
					      		</div>
					 {{/foreach}}
		        	<div class="uploadview-wrapper">
		                <div class="upload-group">
		                    <div id="queue"></div>
		                    <input id="file_upload_auto100" name="file_upload" type="file">
		                </div>
		            </div>
		        </div>
			</li>
		</ul>
	</div>

	<div class="view-con view-cost dpt-fee-list">
		<ul>
			<li class="forclone" style="display: none;"><b>费用名称：</b>
				<div class="selectByM slt-100" hasevent="true">
					<input type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='' value="费用选择"  name="feechoose" datatype="chooseGroup" choosenull="请选择费用类型"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$fee_type_data key=fk item=fv}}
							<li selectVal='{{$fv.fee_type_id}}'>{{$fv.type_name}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">计费方式：</b>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='' value="计费选择" name="jfeechoose" datatype="chooseGroup" choosenull="请选择计费方式"/> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$pay_type key=pkey item=pval}}
							<li selectVal='{{$pkey}}' val>{{$pval}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">收费单价：</b> <input type="text" value=""
				 class="ipt ipt-80" name="money" datatype="float,price-singel" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> <i class="ifont">&#xe675;</i>
						<a href="javascript:;" class="forclonedelete">删除</a>
						<span class="check-error check-error-ts"></span>
			</li>
			{{foreach from=$fee_data key=fkey item=fval}}
			<li  class="forcloneauto">
				<b>费用名称：</b>
				<div class="selectByM slt-100" hasevent="true">
					<input name="feechoose" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='{{$fval.fee_type_id}}' value="电费" /> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$fee_type_data key=ftkey item=ftval}}
							<li {{if $fval.fee_type_id eq $ftval.fee_type_id}}class="selectedLi"{{/if}} selectVal='{{$ftval.fee_type_id}}'>{{$ftval.type_name}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">计费方式：</b>
				<div class="selectByM slt-100">
					<input name="jfeechoose" type="text" class="selectByMT centralized_Ind_CuteType"
						readonly='readonly' selectVal='{{$fval.payment_mode}}' value="" /> <span
						class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							{{foreach from=$pay_type key=pkey item=pval}}
								<li {{if $fval.payment_mode eq $pkey}}class="selectedLi"{{/if}} selectVal='{{$pkey}}'>{{$pval}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div> <b class="dte-30">收费单价：</b> 
				<input name="money" type="text" value="{{$fval.money}}" class="ipt ipt-80" datatype="float,price-singel" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> 
				<i class="ifont">&#xe675;</i><a href="javascript:;" class="forclonedelete">删除</a>
				<span class="check-error check-error-ts"></span>
			</li>
			{{/foreach}}
			<li class="view-add-cost"><i class="ifont mr5">&#xf0037;</i> <a href="javascript:;" title="除租金、定金、押金外如有其他费用可在此处添加">添加费用</a><i style="color: red;">（除房屋租金、押金、定金外的其他费用,如服务费、保洁费等）</i></li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" url="{{'Centralized-Roomfocus/edit'|url}}" class="btn btn2">保存</a> <a href="javascript:;" class="btn btn4 btn-cancel">取消</a>
	</div>
</div>
<!--集中式公寓-添加房间 e-->
<!--多选删除遮罩模板-->
	<div class="deletemoreauto none">
		<div class="top">
			<div class="top1">
				<span class="fl">正在删除...</span>
				<span class="fr">
					<span class="num_cur">1</span>/<span class="num_total"></span>
				</span>
			</div>
			<div class="top2">
				<div class="top2a">
					<div class="top2at"></div>
				</div>
			</div>
		</div>
		<div class="content">
			<table>
				<tr><th class="zb">房间配置名称</th><th class="yb">删除结果</th></tr>
				<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
			</table>
		</div>
	</div>
	<!-- 预约退租信息展示-房间详情 -->
    <script type="text/template" id="cover-room-yytz">
    		<div class="rsv-wrap jzf-form room-chekout-form" id="roomCheckoutForm">
    			<div class="jzf-col">
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span class="room-num"></span>
					</div>
					<div class="jzf-col-r">
						<span class="roomNum"></span>
					</div>
			    </div>
			</div>
			<div class="jzf-col">
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span><i class="red">*</i>退租日期：</span>
					</div>
					<div class="jzf-col-r fl clearfix">
						<input type="text" datatype="*" readonly="readonly" name="start_time" nullmsg="请选择退租日期" class="ipt ipt-165 date-input ipx-txt">
						<span class="check-error-ts check-error-auto">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
					</div>
			    </div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-l">
					<span><i class="red">*</i>备注说明：</span>
				</div>
				<div class="jzf-col-r blo-row">
					<textarea class="ipx-txt" id="remark-for-tz-room" name="remark" datatype="*"  nullmsg="请输入备注信息"></textarea>
					<span class="check-error-ts">
						<i class="ico-arrwo-d ico-arrwo-d-remark"></i>
						<span class="check-error check-error-textarea"></span>
					</span>
				</div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-r blo-row">
					<div class="resv-act-btns">
						<a href="javascript:;" class="btn btn2 mr10"  id="room-tz-info-save-autos" tzurl="{{'centralized-roomfocus/rentalback'|url}}">保存</a>
						<a href="javascript:;" class="btn btn4 cancle-over-trigger-autos" rasb-url="{{'centralized-roomfocus/revocationsubscribe'|url|cat:'&room_id='|cat:$roomFocusInfo.room_focus_id}}">撤销</a>
					</div>
				</div>
			</div>
    		</div>
    </script>