		<div class="center-dpt jzf-form" isEditpage="1" hasform="true">
			<div class="dpt-item">
				<div class="center-dpt-top">
					<span class="iblue">公寓信息</span>
				</div>
				<div class="center-dpt-body">
							<div class="jzf-col">
								<div class="jzf-col-l">
									<span><i class="red">*</i>公寓名称：</span>
								</div>
								<div class="jzf-col-r">
									<input type="text" value="{{$flat_data.flat_name}}" class="ipt" name="centralized_Depart_InfoJs_flat_name" placeholder="输入公寓名称"  datatype = "*,checktszf" nullmsg = "请输入公寓名称"/>
								</div>
								<span class="check-error check-error-ts"></span>
								<i class="notice-auto">（例如：九猪公寓）</i>
							</div>
							<div class="jzf-col">
								<div class="jzf-col-l">
									<span><i class="red">&nbsp;&nbsp;</i>公寓编号：</span>
								</div>
								<div class="jzf-col-r">
									<input type="text" value="{{$flat_data.custom_number}}" class="ipt bor" style="background: #f5f5f5;" name="centralized_Depart_InfoJs_custom_number" placeholder="公寓编号" readonly="readonly"/>
								</div>
							</div>
							<div class="jzf-col clearfix">
								<div class="jzf-col-l float-l">
									<span><i class="red">*</i>区域商圈：</span>
								</div>
								<div class="jzf-col-r">
									<div class="selectByM" hasevent = true>
										<input type="text" business-url={{$business}} name="centralized_Depart_InfoJs_city_id" class="selectByMT centralized_Ind_CuteType1" readonly = 'readonly' selectVal = '' value="" prev-value="" datatype = "chooseGroup" choosenull = "请选择区域"/>
										<span class='jt_Ctr'><span class='jt_box'></span></span>
										<div class="selectByMO">
											<ul>
												{{foreach from=$area_data key=ak item=av}}
													<li {{if $flat_data.area_id eq $av.area_id}}class="selectedLi"{{/if}}selectVal="{{$av.area_id}}">{{$av.name}}</li>
												{{/foreach}}
											</ul>
										</div>
									</div>
									<div class="selectByM">
										<input name="centralized_Depart_InfoJs_area_id" type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="" datatype = "chooseGroup" choosenull = "请选择商圈"/>
										<span class='jt_Ctr'><span class='jt_box'></span></span>
										<div class="selectByMO">
											<ul>
												{{foreach from=$business_data key=bk item=bv}}
													<li {{if $flat_data.business_id eq $bv.business_id}}class="selectedLi"{{/if}}selectVal="{{$bv.business_id}}">{{$bv.name}}</li>
												{{/foreach}}
											</ul>
										</div>
									</div>
								</div>
								<span class="check-error check-error-ts" style="line-height: 32px;margin-left: 10px;"></span>
							</div>
							<div class="jzf-col" style="z-index: 2;">
								<div class="jzf-col-l">
									<span><i class="red">*</i>详细地址：</span>
								</div>
								<div class="jzf-col-r jzf-col-r-auto">
									<input type="text" point-lat="{{$flat_data.latitude}}" point-lng="{{$flat_data.longitude}}" value="{{$flat_data.address}}" class="ipt adr-box" id="centralized_Depart_InfoJs_address" name="centralized_Depart_InfoJs_address" placeholder="街道/号"  datatype = "*,check-flat-address" nullmsg = "请输入详细地址"/>
									<div id="show_addressdetail">
										<ul></ul>
									</div>
								</div>
								<a href="javascript:;" class="chooseaddressauto">地址不对，我来纠正</a>
								<span class="check-error check-error-ts"></span>
							</div>
							<div class="jzf-col" style="margin-top: 0;">
								<iframe id="map_auto_add" src="{{'Centralized-Flat/map'|url}}" width="100%" height="265" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="no" allowtransparency="yes" id="flat-map-auto" style="display: none;"></iframe>
							</div>
							<div class="jzf-col">
								<div class="jzf-col-l">
									<span><i class="red">*</i>楼层总数：</span>
								</div>
								<div class="jzf-col-r">
									<input type="text" value="{{$flat_data.total_floor}}" class="ipt bor" style="background: #f5f5f5;" name="centralized_Depart_InfoJs_total_floor" placeholder="楼层总数" readonly="readonly"/>
									<a href="javascript:;" class="floor-num" id="show_floors">楼层编号</a>
								</div>
							</div>
							<div class="jzf-col">
								<div class="jzf-col-l">
									<span><i class="red">*</i>楼层房源：</span>
								</div>
								<div class="jzf-col-r">
									<input type="text" value="{{$flat_data.group_number}}" class="ipt mr5 bor" style="background: #f5f5f5;" name="centralized_Depart_InfoJs_group_number" placeholder="楼层房源" readonly="readonly"/>
									<span class="jzf-unit">套</span>
								</div>
							</div>
							<div class="jzf-col clearfix mb20">
								<div class="jzf-col-l float-l">
									<span><i class="red">*</i>出租类型：</span>
								</div>
								<div class="jzf-col-r clearfix">
									{{if $flat_data.rental_way eq 2}}
									<div class="radio-box">
										<label class="radio" nochoose = "true">
											<i class="ifont r-default"{{if $flat_data.room_number eq 0}}style="display: none;"{{/if}}>&#xe612;</i>
											<i class="ifont r-select" {{if $flat_data.room_number eq 0}}style="display: inline;"{{/if}}>&#xe617;</i>
										</label>
										<input type="radio" name="rental_way" value="2" />
										<span>整租</span>
									</div>
									{{/if}}
									{{if $flat_data.rental_way eq 1}}
									<div class="radio-box">
										<label class="radio" nochoose = "true">
											<i class="ifont r-default" {{if $flat_data.room_number gt 0}}style="display: none;"{{/if}}>&#xe612;</i>
											<i class="ifont r-select" {{if $flat_data.room_number gt 0}}style="display: inline;"{{/if}}>&#xe617;</i>
										</label>
										<input type="radio" name="rental_way" value="1" />
										<span>合租</span>
									</div>
									{{/if}}
									<div class="jzf-col-2 {{if $flat_data.rental_way neq 1}}unit-rooms{{/if}} fl">
										<div class="jzf-col-l">
											<span><i class="red">*</i>套内间数：</span>
										</div>
										<div class="jzf-col-r">
											<input type="text" value="{{$flat_data.room_number}}" class="ipt mr5 bor" style="background: #f5f5f5;" name="room_number" placeholder="套内房间数" readonly="readonly"/>
											<span class="jzf-unit">间</span>
											<!--
                                            	作者：710414018@qq.com
                                            	时间：2015-06-12
                                            	描述：
                                            	<a href="javascript:;" house-url={{'Centralized-Flat/getdiyhousenumber'|url}} url="{{'Centralized-Flat/roomsnumber'|url}}" class="jzf-unit sf-house zdy-roomNum">自定义房源编号</a>
                                            -->
										</div>
									</div>
								</div>
							</div>
							<!--费用模块添加-->
								<div class="jf-fees">
								 <div class="dpt-fee-list">
								 	 <div class="dpt-fee-item">
											<ul class="gen-f-item clearfix">
												<li class="forclone fl" style="clear: both;"><b>费用名称：</b>
														<div class="selectByM slt-90" hasevent="true">
															<input type="text" class="selectByMT centralized_Ind_CuteType"
																readonly='readonly' selectVal='' value="费用选择" placeholder="费用选择"  name="feechoose" datatype="chooseGroup" choosenull="请选择费用类型"/> <span
																class='jt_Ctr'><span class='jt_box'></span></span>
															<div class="selectByMO">
																<ul>
																{{foreach from=$fee_type key=fk item=fv}}
																	<li selectVal='{{$fv.fee_type_id}}'>{{$fv.type_name}}</li>
																{{/foreach}}
																</ul>
															</div>
														</div> <b class="dte-30">计费方式：</b>
														<div class="slt-180 selectByM">
															<input type="text" class="selectByMT centralized_Ind_CuteType" readonly='readonly' selectVal='' value="计费选择" placeholder="计费选择" name="jfeechoose" /> <span class='jt_Ctr'><span class='jt_box'></span></span>
															<div class="selectByMO">
																<ul>
																	{{foreach from=$pay_type key=mpk item=mpv}}
																		<li selectVal = '{{$mpk}}'>{{$mpv}}</li>
																	{{/foreach}}
																</ul>
															</div>
														</div> <b class="dte-30">收费单价：</b> <input type="text" value="" class="ipt ipt-80" name="money" datatype="float,fee-check" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> <i class="ifont">&#xe675;</i>
																<a href="javascript:;" class="forclonedelete">删除</a>
																<span class="check-error check-error-ts"></span>
													</li>
													{{foreach from=$fee_data key=fkey item=fval}}
													<li  class="forcloneauto  fl jzf-col clearfix" style="clear: both; width: 100%;">
														<b>费用名称：</b>
														<div class="selectByM slt-90" hasevent="true">
															<input type="text" name="feechoose"  class="selectByMT centralized_Ind_CuteType"
																readonly='readonly' selectVal='{{$fval.fee_type_id}}' value="" datatype="chooseGroup" choosenull="请选择费用类型"/> <span
																class='jt_Ctr'><span class='jt_box'></span></span>
															<div class="selectByMO">
																<ul>
																	{{foreach from=$fee_type key=ftkey item=ftval}}
																	<li {{if $fval.fee_type_id eq $ftval.fee_type_id}}class="selectedLi"{{/if}} selectVal='{{$fval.fee_type_id}}'>{{$ftval.type_name}}</li>
																	{{/foreach}}
																</ul>
															</div>
														</div> <b class="dte-30">计费方式：</b>
														<div class="slt-180 selectByM">
															<input type="text" class="selectByMT centralized_Ind_CuteType"
																readonly='readonly' selectVal='money' name="jfeechoose" value="现金" /> <span
																class='jt_Ctr'><span class='jt_box'></span></span>
															<div class="selectByMO">
																<ul>
																	{{foreach from=$pay_type key=mpk item=mpv}}
																		<li {{if $fval.payment_mode eq $mpk}}class="selectedLi"{{/if}} selectVal = '{{$mpk}}'>{{$mpv}}</li>
																	{{/foreach}}
																</ul>
															</div>
														</div> <b class="dte-30">收费单价：</b> <input  name="money" type="text" value="{{$fval.money}}" class="ipt ipt-80" datatype="float,fee-check" nullmsg="请输入收费单价" errormsg="收费单价格式错误"/> <span class="ml10">元/月</span> 
														<i class="ifont">&#xe675;</i>
														<a href="javascript:;" class="forclonedelete">删除</a>
													</li>
													{{/foreach}}
											</ul>
								 	 </div>
								 </div>
								<a href="javascript:;" class="dpt-add-btn-auto" title="除租金、定金、押金外如有其他费用可在此处添加"><i class="ifont">&#xf0037;</i>添加费用</a><i style="color: red;">（除房屋租金、押金、定金外的其他费用,如服务费、保洁费等）</i>
							</div>
							<!--费用模块end-->

				</div>
			</div>
			<div class="dpt-item">
				<div class="center-dpt-top">
					<span class="iblue">模板信息</span>
				</div>
				<div class="center-dpt-body">
					<table class="lr-tb">
						<tr class="lr-tb-h">
							<td>模板名称</td>
							<td>房间户型</td>
							<td>房间总数</td>
							<td>房间租金</td>
							<td>操作</td>
						</tr>
						{{foreach from=$template_data key=tkey item=tval}}
						<tr>
							<td>{{$tval.template_name}}</td>
							<td>{{$tval.roomType}}</td>
							<td>{{$tval.room_count}}</td>
							<td>{{$tval.money}}元</td>
							<td>
								<a href="#{{'Centralized-FlatTemplate/update'|url|cat:'&'|cat:'template_id='|cat:$tval.template_id}}" class="mr10">配置</a>
								<a href="javascript:;" url="{{'Centralized-FlatTemplate/delete'|url|cat:'&'|cat:'template_id='|cat:$tval.template_id}}" class="del-trig">删除</a>
							</td>
						</tr>
						{{/foreach}}
					</table>
					<a href="javascript:;" url="#{{'Centralized-FlatTemplate/add'|url}}" class="dpt-add-btn"><i class="ifont">&#xf0037;</i>添加模板</a>
				</div>
			</div>
			<div class="dpt-bot-grp">
				<a href="javascript:;" url="{{'Centralized-Flat/edit'|url}}" class="btn btn2">保存</a>
				<a href="javascript:;" class="btn btn4 ml10 btn-cancel">取消</a>
			</div>
		</div>
	<!--
    	楼层编号遮罩模板
    -->
	<div id="hideTemp" style="display: none;">
		<div  class="dialog-dpt-flr">
		<div class="dpt-flr-top">
			<span class="dpt-name fl">{{$flat_data.flat_name}}<i class="dpt-flrs">(共计{{$flat_data.total_floor}}层)</i></span>
			<span class="smal-tip fl">地下楼层请填写负数，楼层数为三位内整数（不能为0）</span>
		</div>
		<div class="center-dpt-body">
			<table class="lr-tb center-dpt-row">
				<tr class="lr-tb-h">
					<td>当前楼层</td>
					<td>修改名称</td>
				</tr>
					{{foreach from=$floor_number key=fkey item=fval}}
					<tr>
						<td>第{{$fkey}}层</td>
						<td>
							<input type="text" class="ipt" value="{{$fval.update_number}}" readonly="readonly">
						</td>
					</tr>
					{{/foreach}}
		</table>
		</div>
		</div>
	</div>
