<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/customer_manage_page.css" />
        <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=uLe6iBql9gByOgFAaqdhPxzO"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript">
        	 seajs.use("{{$smarty.const.APP_WEB_STATIC_URL}}js/application_Js/map_auto.js")
        </script>
	</head>
	<body style="background-color: #FFFFFF;">
		<div class="jzf-form">
			<div class="jzf-col jzf-col-auto-showmap" style="z-index: 1;">
				<div class="autohandle"></div>
				<div class="map-box" id="mapContainer"></div>
			</div>
		</div>
	</body>
</html>
 