<div id="workerManage_Authority" hasform="true">
	<div class="workerManage_Authority">
		<div class="workerManage_Authority_A">新增权限组</div>
		<div class="workerManage_Authority_B">
			<div class="a">
				<span class="name fl">分组名：</span><input type="text"
					placeholder="部门名称" class="fl ipt" />
			</div>
			<div class="b">
				<ul>
					<li>
						<dl>
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">房源管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					<li>
						<div class="li_Head">
							<label><span class="choose ifont1">&#xe60c;</span></label> <input
								type="checkbox" /> <span class="name">客户管理</span>
						</div>
						<dl class="li_DL">
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">租客管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
						<dl class="li_DL">
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">预订管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					<li>
						<div class="li_Head">
							<label><span class="choose ifont1">&#xe60c;</span></label> <input
								type="checkbox" /> <span class="name">财务管理</span>
						</div>
						<dl class="li_DL">
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">流水统计</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
						<dl class="li_DL">
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">类型管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					<li>
						<dl>
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">业主管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					<li>
						<dl>
							<dt>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">员工管理</span>
							</dt>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">增加</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">修改</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">删除</span>
							</dd>
							<dd>
								<label><span class="choose ifont1">&#xe60c;</span></label> <input
									type="checkbox" /> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					<li class="lst">
						<button class="submit">确定</button>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
