<!--业主信息 s-->
<!-- 这是续租业主合同的模板 -->
{{if $smarty.get.a eq 'reletlandlord'}}
<div class="manager_landlord_msg view" hasform="true">
	<div class="view-head">
		<h1>业主信息[续租]</h1>
	</div>
	<div class="view-con">
		<ul>
			<li class="house-type">
				<b><i class="bit"></i>房源类型：</b>
				{{if $landlord_info.house_type eq '2'}}
				<div class="radio-box">
					<label class="radio checked"><i class="ifont r-default" style="display: none;">&#xe612;</i><i class="ifont r-select" style="display: inline;">&#xe617;</i></label>
					<input type="radio" name="type" value="" checked="checked" data-type="2" />
					<span>集中式公寓</span>
				</div>
				{{else}}
				<div class="radio-box radio-type">
					<label class="radio checked"><i class="ifont r-default" style="display: none;">&#xe612;</i><i class="ifont r-select" style="display: inline;">&#xe617;</i></label>
					<input type="radio" name="type" checked="checked" value="" data-type="1" />
					<span>分散式公寓</span>
				</div>
				{{/if}}
			</li>
			<li class="house-distributed" {{if $landlord_info.house_type eq '2'}}style="display: none;"{{else}}style="display: block;"{{/if}}>
				<b><i class="bit">*</i>小区名称：</b>
				{{if $landlord_info.house_type eq '1'}}
    				<input disabled type="text" class="ipt ipt-350 mr10 bg-gray" name="distributed_house" value="{{$landlord_info.0}}" placeholder="请输入小区名字" datatype="*" nullmsg="请输入房源名" />
    				<!--<input type="hidden" class="res_name" value="" community_id="" />-->
    				<input disabled type="text" value="{{$landlord_info.cost}}" class="ipt ipt-40 mr5 bg-gray" name="build" />
    				<span class="mr5">栋</span>
    				<input disabled type="text" value="{{$landlord_info.unit}}" class="ipt ipt-40 mr5 bg-gray" name="unit" />
    				<span class="mr5">单元</span>
    				<input disabled type="text" value="{{$landlord_info.floor}}" class="ipt ipt-40 mr5 bg-gray" name="floor" />
    				<span class="mr5">楼</span>
    				<input disabled type="text" value="{{$landlord_info.number}}" class="ipt ipt-50 mr5 bg-gray" name="number" />
    				<span>号</span>
    				<span class="check-error check-error-ts"></span>
    			{{else}}
    				<input type="text" class="ipt ipt-350 mr10" name="distributed_house" placeholder="请输入小区名字" datatype="*" nullmsg="请输入房源名" />
    				<input type="hidden" class="res_name" value="" community_id="" />	
    				<input type="text" class="ipt ipt-40 mr5" name="build" />
    				<span class="mr5">栋</span>
    				<input type="text" class="ipt ipt-40 mr5" name="unit" />
    				<span class="mr5">单元</span>
    				<input type="text" class="ipt ipt-40 mr5" name="floor" />
    				<span class="mr5">楼</span>
    				<input type="text" class="ipt ipt-50 mr5" name="number" />
    				<span>号</span>
    				<span class="check-error check-error-ts"></span>
    			{{/if}}
			</li>
			<li class="house-centralized" {{if $landlord_info.house_type eq '1'}}style="display: none;"{{else}}style="display: block;"{{/if}}>
				<b><i class="bit">*</i>公寓名称：</b>
				{{if $landlord_info.house_type eq '2'}}
    				<input disabled type="text" class="ipt ipt-625 bg-gray" id="houses"  name="centralized_house" datatype="*" nullmsg="请输入房源名" value="{{$landlord_info.hosue_name}}"/>
    				<input disabled type="hidden" name="rentType-select" value="1">
    				<input disabled type="hidden" name="community_id">
    			{{else}}
    				<input type="text" class="ipt ipt-625" id="houses" name="centralized_house" datatype="*" nullmsg="请输入房源名" value="{{$landlord_info.hosue_name}}"/>
    				<input type="hidden" name="rentType-select" value="1">
    				<input type="hidden" name="community_id">
    			{{/if}}
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit">*</i>业　　主：</b>
				<input type="text" class="ipt ipt-250 ipt-con" value="{{$landlord_info.name}}" name="landlord_name" datatype="*" nullmsg="请输入业主姓名" />
				<b class="dte-50"><i class="bit">*</i>电　　话：</b>
				<input type="text" class="ipt ipt-250 ipt-con" value="{{$landlord_info.phone}}" name="landlord_phone" datatype="/^1\d{10}$/" nullmsg="请输入业主电话" errormsg="电话号码格式错误" />
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit">*</i>证件号码：</b>
				<input type="text" class="ipt ipt-250 ipt-con landlord_card" value="{{$landlord_info.idcard}}" name="landlord_card" actionurl="{{'landlord-index/isexistIdcard'|url}}" datatype="*1-40" nullmsg="请输入业主证件号码" errormsg="证件号码格式错误" />
				<b class="dte-50"><i class="bit"></i>合同编号：</b>
				<input type="text" class="ipt ipt-250 ipt-con"  name="landlord_contract_num" />
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>合同起始：</b>
				<input type="text"  class="ipt ipt-110 ipt-con contract_start maxWdate" max_date="{{$landlord_info.max_time}}" datatype="contract-time" nullmsg="请填写合同起始时间" value="{{if $landlord_info.end_line neq '0'}}{{$landlord_info.end_line|date_format:'%Y-%m-%d'}}{{/if}}" readonly="readonly" name="landlord_start_time" />
				<span class="mr5 ml5">至</span>
				<input type="text" class="ipt ipt-110 ipt-con date contract_end" readonly="readonly"  name="landlord_end_time" datatype="contract-time" nullmsg="请填写合同起始时间" />
				<b class="dte-50"><i class="bit"></i>免房租期：</b>
				<input type="text" class="ipt ipt-230 ipt-con reduce-term" style="width: 135px;" name="landlord_term" value="{{$landlord_info.free_day}}" datatype="landlord_term" errormsg="租期格式错误" />
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con mzq-dw" readonly = 'readonly' selectVal = "month" value="月"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='month' class="selectedLi">月</li>
							<li  selectVal='day'>天</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="landlord-rent">
				<b><i class="bit"></i>租　　金：</b>
				<input type="text" class="ipt ipt-80 ipt-con" value="{{if $landlord_info.rent neq '0'}}{{$landlord_info.rent}}{{/if}}" name="landlord_rent" datatype="landlordRent" nullmsg="请输入租金" errormsg="租金格式不正确" />
				<span class="ml5">元/月</span>
				<div class="check-box" style="display: none;">
					<label class="increase"><i class="choose ifont1">&#xe60c;</i></label>
					<input type="checkbox" value="" style="display: none;" />
					<span>租金每年递增</span>
				</div>
				<div class="rent-con">
					<div class="radio-box">
						<label class="radio checked"><i class="ifont r-default" style="display: none;">&#xe612;</i><i class="ifont r-select" style="display: inline;">&#xe617;</i></label>
						<input type="radio" name="type" value="" checked="checked" data-type="1" />
						<span>按比例</span>
					</div>
					<div class="radio-box radio-type">
						<label class="radio"><i class="ifont r-default">&#xe612;</i><i class="ifont r-select">&#xe617;</i></label>
						<input type="radio" name="type" value="" data-type="2" />
						<span>按金额</span>
					</div>
					<input type="text" class="ipt ipt-80 rent-con-num" datatype="rentIncrease" errormsg="格式不正确" />
					<input type="hidden" name="rent_money" class="rent_money" />
					<span class="ml5 word" style="display: none;">元</span>
					<span class="ml5 sign">%</span>
					<a href="javascript:;" class="ml15 auto-money" style="display: none;">自定义递增金额</a>
				</div>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>付款方式：</b>
				<span class="mr10">押</span>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con" readonly = 'readonly' selectVal = "{{$landlord_info.detain}}" value="{{foreach from=$bet_arr key=key item=b}}{{if $key eq $landlord_info.detain}}{{$b}}{{/if}}{{/foreach}}" name="landlord_bet_num" datatype="chooseNumBet" nullmsg="请选择押几" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li {{if $landlord_info.detain eq '0'}}class="selectedLi"{{/if}} selectVal='0'>零</li>
							<li {{if $landlord_info.detain eq '1'}}class="selectedLi"{{/if}} selectVal='1'>一</li>
							<li {{if $landlord_info.detain eq '2'}}class="selectedLi"{{/if}} selectVal='2'>二</li>
							<li {{if $landlord_info.detain eq '3'}}class="selectedLi"{{/if}} selectVal='3'>三</li>
							<li {{if $landlord_info.detain eq '4'}}class="selectedLi"{{/if}}  selectVal='4'>四</li>
							<li {{if $landlord_info.detain eq '5'}}class="selectedLi"{{/if}} selectVal='5'>五</li>
							<li {{if $landlord_info.detain eq '6'}}class="selectedLi"{{/if}} selectVal='6'>六</li>
							<li {{if $landlord_info.detain eq '7'}}class="selectedLi"{{/if}} selectVal='7'>七</li>
							<li {{if $landlord_info.detain eq '8'}}class="selectedLi"{{/if}} selectVal='8'>八</li>
							<li {{if $landlord_info.detain eq '9'}}class="selectedLi"{{/if}} selectVal='9'>九</li>
							<li {{if $landlord_info.detain eq '10'}}class="selectedLi"{{/if}} selectVal='10'>十</li>
							<li {{if $landlord_info.detain eq '11'}}class="selectedLi"{{/if}} selectVal='11'>十一</li>
							<li {{if $landlord_info.detain eq '12'}}class="selectedLi"{{/if}} selectVal='12'>十二</li>
						</ul>
					</div>
				</div>
				<span class="mr10 ml10">付</span>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con" readonly = 'readonly' selectVal = "{{$landlord_info.pay}}" value="{{foreach from=$bet_arr key=key item=b}}{{if $key eq $landlord_info.pay}}{{$b}}{{/if}}{{/foreach}}" name="landlord_pay_num" datatype="chooseNumPay" nullmsg="请选择付几" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO" style="display: none;">
						<ul>
							<li {{if $landlord_info.pay eq '1'}}class="selectedLi"{{/if}} selectVal='1'>一</li>
							<li {{if $landlord_info.pay eq '2'}}class="selectedLi"{{/if}} selectVal='2'>二</li>
							<li  {{if $landlord_info.pay eq '3'}}class="selectedLi"{{/if}} selectVal='3'>三</li>
							<li  {{if $landlord_info.pay eq '4'}}class="selectedLi"{{/if}} selectVal='4'>四</li>
							<li {{if $landlord_info.pay eq '6'}} class="selectedLi" {{/if}} selectVal='6'>六</li>
							<!-- <li {{if $landlord_info.pay eq '7'}} class="selectedLi" {{/if}} selectVal='7'>七</li>
							<li {{if $landlord_info.pay eq '8'}} class="selectedLi" {{/if}} selectVal='8'>八</li>
							<li {{if $landlord_info.pay eq '9'}} class="selectedLi" {{/if}} selectVal='9'>九</li>
							<li {{if $landlord_info.pay eq '10'}} class="selectedLi" {{/if}} selectVal='10'>十</li>
							<li {{if $landlord_info.pay eq '11'}}class="selectedLi"{{/if}} selectVal='11'>十一</li> -->
							<li {{if $landlord_info.pay eq '12'}}class="selectedLi"{{/if}} selectVal='12'>十二</li>
						</ul>
					</div>
				</div>
				<b class="dte-50"><i class="bit"></i>押　　金：</b>
				<input type="text" class="ipt ipt-230 ipt-con cl-spe" value="{{if $landlord_info.deposit neq '0'}}{{$landlord_info.deposit}}{{/if}}" name="landlord_deposit" datatype="landlordDeposit" nullmsg="请输入押金" errormsg="押金格式不正确" />
				<span class="ml5">元</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>提前付款：</b>
				<input type="text" class="ipt ipt-230 advance-pay ipt-con" value="{{if $landlord_info.advance_time neq '0'}}{{$landlord_info.advance_time}}{{/if}}" placeholder="例如：15" name="landlord_advance_pay" datatype="landlord_term" nullmsg="请填写提前付款天数" errormsg="提前付款格式错误" />
				<span class="ml5">天</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>付款银行：</b>
				<div class="selectByM slt-200" hasevent="1">
					<input type="text" class="selectByMT slt-con" disabled="disabled" selectVal="{{$landlord_info.bank}}" value="{{foreach from=$bank_arr key=key item=b}}{{if $key eq $landlord_info.bank-1}}{{$b}}{{/if}}{{/foreach}}" name="landlord_pay_bank"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						      {{foreach from=$bankconfig key=key item=v}}
						          <li {{if $landlord_info.bank eq $key}}class="selectedLi"{{/if}} selectVal='{{$key}}'>{{$v}}</li>
						     {{/foreach}}
							<li {{if $landlord_info.bank eq '1'}}class="selectedLi"{{/if}} selectVal='1'>中国工商银行</li>
						</ul>
					</div>
				</div>
				<b class="dte-50"><i class="bit"></i>开户支行：</b>
				<input type="text" class="ipt ipt-250 ipt-con" value="{{$landlord_info.fork_bank}}" name="landlord_open_bank" />
			</li>
			<li class="view-con-last-li">
				<b><i class="bit"></i>银行卡号：</b>
				<input type="text" class="ipt ipt-250 ipt-con" value="{{if $landlord_info.bank_no neq '0'}}{{$landlord_info.bank_no}}{{/if}}" name="landlord_card_num" datatype="landlord_card_num" errormsg="银行卡号格式不正确" />
				<b class="dte-50"><i class="bit"></i>收 款 人：</b>
				<input type="text" class="ipt ipt-250 ipt-con" value="{{$landlord_info.payee}}" name="landlord_payee" />
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-con cost-msg">
		<ul>
			<!--<li>
				<b class="cm-head">费用信息</b>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="电费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>电费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="12" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="气费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>气费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="15" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="清洁费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>清洁费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
							<li selectVal = '1'>月付</li><li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="10" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li class="view-add-cost">
				<i class="ifont mr5">&#xf0037;</i>
				<a href="">添加费用</a>
			</li>-->
			<li class="li-pic" style="margin-bottom: 0;">
				<b style="margin-bottom: 0;"><i class="bit"></i>合同照片：</b>
				<span style="margin-bottom: 0;">（建议添加业主合同照片、业主证件照片等，要求：jpg、gif、png格式，最多上传9张）</span>
			</li>
			<li class="view-img">
				<div class="uploader-area" id="relet-uploaderArea">
		        	<div class="uploadview-wrapper">
		                <div class="upload-group">
		                    <div id="queue"></div>
		                    <input id="relet-file-upload" name="file_upload" type="file">
		                </div>
		            </div>
		        </div>
			</li>
			<li class="view-txt">
				<b><i class="bit"></i>备注说明：</b>
				<textarea class="i-txt ipt-con fl" name="landlord_mark" ignore="ignore" datatype="*1-400" errormsg="备注内容超出范围">{{$landlord_info.mark}}</textarea>
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" url="{{'landlord-index/reletLandlord'|url|cat:'&pid='|cat:$landlord_info.contract_id}}" class="btn btn2 add-landlord-btn">保存</a>
		<a href="javascript:;" class="btn btn4 btn-cancel">取消</a>
	</div>
</div>
<!--业主信息 e-->
<!--自定义金额 s-->
<div id="hide-auto-money" class="none">
	<div class="auto-money-con">
		<ul>
			<li class="auto-money-head">
				<b>合约年份</b>
				<span>租金</span>
			</li>
			<li>
				<b>第一年</b>
				<input type="text" class="ipt ipt-70 year-money rent-first" readonly="readonly" datatype="n" nullmsg="请输入金额" errormsg="金额格式不正确" />
				<span class="ml10 mr10">元/月</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="loop">
				<b>第${year}年</b>
				<input type="text" class="ipt ipt-70 year-money" datatype="n" nullmsg="请输入金额" errormsg="金额格式不正确" />
				<span class="ml10 mr10">元/月</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="submit-btn">
				<a href="javascript:;" url="" class="btn btn2 ok-btn">保存</a>
				<a href="javascript:;" class="btn btn4 cancel-btn">取消</a>
			</li>
		</ul>
	</div>
</div>
<!--自定义金额 e-->

<!--新增小区 s-->
<div id="hide-add-compounds" class="none">
	<div class="checkout-con add-compounds-con">
		<ul>
			<li>
				<b><i>*</i>小区名称：</b>
				<input type="text" class="ipt ipt-300 compounds-name fl mb20" datatype="*" nullmsg="请输入小区名称" />
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>城市：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT city" readonly = 'readonly' selectVal = '' value="" addressURL="{{'landlord-index/getAreaCity'|url}}"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						{{foreach from=$allcity item=ac}}
							<li selectVal = '{{$ac.city_id}}'>{{$ac.name}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div>
				<!--<span class="check-error check-error-ts check-center"></span>-->
			</li>
			<li>
				<b><i>*</i>区域：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT area" readonly = 'readonly' selectVal = '' value="" datatype="areaName" nullmsg="请选择区域" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '0'>区域</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>商圈：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT business" readonly = 'readonly' selectVal = '' value="" datatype="businessName" nullmsg="请选择商圈" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '0'>商圈</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>街道地址：</b>
			</li>
			<li>
				<textarea class="i-txt" datatype="*" nullmsg="请输入街道地址"></textarea>
				<span class="check-error check-error-ts ml5"></span>
			</li>
			<li class="checkout-btn">
				<a href="javascript:;" class="btn btn2 add_compounds_btn" actionurl="{{'landlord-index/addCommunity'|url}}">保存</a>
				<a href="javascript:;" class="btn btn4 cancel-btn">取消</a>
			</li>
		</ul>
	</div>
</div>
<!--新增小区 e上面是续租！！！！！！！！！！-->


{{else}}

<!-- 这是添加业主合同时的模板 -->
<div class="manager_landlord_msg view">
	<div class="view-head">
		<h1>业主信息</h1>
	</div>
	<div class="view-con">
		<ul>
			<li class="house-type">
				<b><i class="bit"></i>房源类型：</b>
				<div class="radio-box">
					<label class="radio {{if $house_type eq 2 or $house_type eq 0}}checked{{/if}}">
					<i class="ifont r-default" {{if $house_type eq 2 or $house_type eq 0}}style="display: none;"{{/if}}>&#xe612;</i>
					<i class="ifont r-select" {{if $house_type eq 2 or $house_type eq 0}}style="display: inline;"{{/if}}>&#xe617;</i></label>
					<input type="radio" name="type" value="" {{if $house_type eq 2 or $house_type eq 0}}checked="checked"{{/if}} data-type="2" />
					<span>集中式公寓</span>
				</div>
				<div class="radio-box radio-type">
					<label class="radio {{if $house_type eq 1}}checked{{/if}}">
					<i class="ifont r-default" {{if $house_type eq 1}}style="display: none;"{{/if}}>&#xe612;</i>
					<i class="ifont r-select" {{if $house_type eq 1}}style="display: inline;"{{/if}}>&#xe617;</i></label>
					<input type="radio" name="type" value="" data-type="1" {{if $house_type eq 1}}checked="checked"{{/if}}/>
					<span>分散式公寓</span>
				</div>
			</li>
			<!--
            	作者：710414018@qq.com
            	时间：2015-06-19
            	描述：分散式
            -->
			<li class="house-distributed" {{if $house_type eq 2 or $house_type eq 0}}style="display: none;"{{/if}}>
				<b><i class="bit">*</i>小区名称：</b>
				<input type="text" community_id="{{$community.community_id}}"  value="{{$community.community_name}}" dataurl="{{'landlord-index/searchexistshouse'|url}}" id="houses" class="ipt ipt-350 mr10 distributed_house" name="distributed_house" actionurl="{{$search_url}}" placeholder="请输入小区名字" datatype="*,compoundsName" nullmsg="请输入小区名" errormsg="小区不存在，请新增小区" />
				<!--<input type="hidden" class="res_name" value="" community_id="" />-->				
				<input type="text" value="{{$house_data.cost}}" class="ipt ipt-40 mr5 build" name="build" datatype="s" nullmsg="请输入栋数" errormsg="栋数格式错误" ignore = "ignore"/>
				<span class="mr5">栋</span>
				<input type="text" value="{{$house_data.unit}}" class="ipt ipt-40 mr5 unit" name="unit" datatype="s" nullmsg="请输入单元数" errormsg="单元数格式错误"  ignore = "ignore"/>
				<span class="mr5">单元</span>
				<input type="text" value="{{$house_data.floor}}" class="ipt ipt-40 mr5 floor" name="floor" datatype="floor" nullmsg="请输入楼数" errormsg="楼数格式错误"  ignore = "ignore"/>
				<span class="mr5">楼</span>
				<input type="text" value="{{$house_data.number}}" class="ipt ipt-50 mr5 num" name="number" datatype="s" nullmsg="请输入号数" errormsg="号数格式错误"  ignore = "ignore"/>
				<span>号</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<!--
            	作者：710414018@qq.com
            	时间：2015-06-19
            	描述：集中式
            -->
			<li class="house-centralized" {{if $house_type eq 1}}style="display: none;"{{/if}}>
				<b><i class="bit">*</i>公寓名称：</b>
				<input type="text" value="{{$flat_data.flat_name}}" class="ipt ipt-625 centralized_house" actionurl="{{'landlord-index/isexistHousename'|url}}" dataurl="{{'landlord-index/searchexistshouse'|url}}"  name="centralized_house" datatype="*" nullmsg="请输入公寓名" />
				<input type="hidden" name="rentType-select" value="1">
				<input type="hidden" name="community_id">
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit">*</i>业　　主：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_name" datatype="*" nullmsg="请输入业主姓名" />
				<b class="dte-50"><i class="bit">*</i>电　　话：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_phone" datatype="/^1\d{10}$/" nullmsg="请输入业主电话" errormsg="电话号码格式错误" />
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit">*</i>证件号码：</b>
				<input type="text" class="ipt ipt-250 ipt-con landlord_card" name="landlord_card" actionurl="{{'landlord-index/isexistIdcard'|url}}" datatype="*1-40" nullmsg="请输入业主证件号码" errormsg="证件号码格式错误" />
				<b class="dte-50"><i class="bit"></i>合同编号：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_contract_num" />
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>合同起始：</b>
				<input type="text" class="ipt ipt-110 ipt-con date contract_start" readonly="readonly" name="landlord_start_time" />
				<span class="mr5 ml5">至</span>
				<input type="text" class="ipt ipt-110 ipt-con date contract_end" readonly="readonly" name="landlord_end_time" />
				<b class="dte-50"><i class="bit"></i>免房租期：</b>
				<input type="text" class="ipt ipt-230 ipt-con reduce-term" style="width: 135px;" name="landlord_term" datatype="landlord_term" errormsg="租期格式错误" />
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con mzq-dw" readonly = 'readonly' selectVal = "month" value="月"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='month' class="selectedLi">月</li>
							<li  selectVal='day'>天</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="landlord-rent">
				<b><i class="bit"></i>租　　金：</b>
				<input type="text" class="ipt ipt-80 ipt-con" name="landlord_rent" datatype="landlordRent" nullmsg="请输入租金" errormsg="租金格式不正确" />
				<span class="ml5">元/月</span>
				<div class="check-box" style="display: none;">
					<label class="increase"><i class="choose ifont1">&#xe60c;</i></label>
					<input type="checkbox" value="" style="display: none;" />
					<span>租金每年递增</span>
				</div>
				<div class="rent-con">
					<div class="radio-box">
						<label class="radio checked"><i class="ifont r-default" style="display: none;">&#xe612;</i><i class="ifont r-select" style="display: inline;">&#xe617;</i></label>
						<input type="radio" name="type" value="" checked="checked" data-type="1" />
						<span>按比例</span>
					</div>
					<div class="radio-box radio-type">
						<label class="radio"><i class="ifont r-default">&#xe612;</i><i class="ifont r-select">&#xe617;</i></label>
						<input type="radio" name="type" value="" data-type="2" />
						<span>按金额</span>
					</div>
					<input type="text" class="ipt ipt-80 rent-con-num" datatype="rentIncrease" errormsg="格式不正确" />
					<input type="hidden" name="rent_money" class="rent_money" />
					<span class="ml5 word" style="display: none;">元</span>
					<span class="ml5 sign">%</span>
					<a href="javascript:;" class="ml15 auto-money" style="display: none;">自定义递增金额</a>
				</div>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>付款方式：</b>
				<span class="mr10">押</span>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con" readonly = 'readonly' selectVal = "" value="" name="landlord_bet_num" datatype="chooseNumBet" nullmsg="请选择押几" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='0'>零</li>
							<li selectVal='1'>一</li>
							<li selectVal='2'>二</li>
							<li selectVal='3'>三</li>
							<li selectVal='4'>四</li>
							<li selectVal='5'>五</li>
							<li selectVal='6'>六</li>
							<li selectVal='7'>七</li>
							<li selectVal='8'>八</li>
							<li selectVal='9'>九</li>
							<li selectVal='10'>十</li>
							<li selectVal='11'>十一</li>
							<li selectVal='12'>十二</li>
						</ul>
					</div>
				</div>
				<span class="mr10 ml10">付</span>
				<div class="selectByM slt-100">
					<input type="text" class="selectByMT slt-con" readonly = 'readonly' selectVal = "" value="" name="landlord_pay_num" datatype="chooseNumPay" nullmsg="请选择付几" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal='1'>一</li>
							<li selectVal='2'>二</li>
							<li selectVal='3'>三</li>
							<li selectVal='4'>四</li>
							<!-- <li selectVal='5'>五</li> -->
							<li selectVal='6'>六</li>
							<!-- <li selectVal='7'>七</li>
							<li selectVal='8'>八</li>
							<li selectVal='9'>九</li>
							<li selectVal='10'>十</li>
							<li selectVal='11'>十一</li> -->
							<li selectVal='12'>十二</li>
						</ul>
					</div>
				</div>
				<b class="dte-50"><i class="bit"></i>押　　金：</b>
				<input type="text" class="ipt ipt-230 ipt-con cl-spe" name="landlord_deposit" datatype="landlordDeposit" nullmsg="请输入押金" errormsg="押金格式不正确" />
				<span class="ml5">元</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>提前付款：</b>
				<input type="text" class="ipt ipt-230 advance-pay ipt-con" value="15" placeholder="例如：15" name="landlord_advance_pay" datatype="landlord_term" errormsg="提前付款格式错误" />
				<span class="ml5">天</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i class="bit"></i>付款银行：</b>
				<div class="selectByM slt-200" hasevent="1">
					<input type="text" class="selectByMT slt-con" readonly="readonly" selectVal="" value="" name="landlord_pay_bank"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
                            {{foreach from=$bankconfig key=key item=v}}
                            	<li class="charts-auto">{{$key}}</li>
                            	{{foreach from=$v key=vkey item=vv}}
							    <li selectVal='{{$vv.key}}'>{{$vv.value}}</li>
							    {{/foreach}}
						    {{/foreach}}
						</ul>
					</div>
				</div>
				<b class="dte-50"><i class="bit"></i>开户支行：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_open_bank" />
			</li>
			<li class="view-con-last-li">
				<b><i class="bit"></i>银行卡号：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_card_num" datatype="landlord_card_num" errormsg="银行卡号格式不正确" />
				<b class="dte-50"><i class="bit"></i>收 款 人：</b>
				<input type="text" class="ipt ipt-250 ipt-con" name="landlord_payee" />
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-con cost-msg">
		<ul>
			<!--<li>
				<b class="cm-head">费用信息</b>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="电费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>电费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="12" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="气费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>气费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="15" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li>
				<b>费用名称：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="清洁费"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>清洁费</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">计费方式：</b>
				<div class="selectByM slt-90">
					<input type="text" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value="月付"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '1'>月付</li>
							<li selectVal = '1'>月付</li><li selectVal = '1'>月付</li>
						</ul>
					</div>
				</div>
				<b class="dte-30">收费单价：</b>
				<input type="text" value="10" disabled class="ipt ipt-70" />
				<span class="ml5">元/月</span>
				<i class="ifont dte-30 mr5">&#xe675;</i>
				<a href="">删除</a>
			</li>
			<li class="view-add-cost">
				<i class="ifont mr5">&#xf0037;</i>
				<a href="">添加费用</a>
			</li>-->
			<li class="li-pic" style="margin-bottom: 0;">
				<b style="margin-bottom: 0;"><i class="bit" style="margin-bottom: 0;"></i>合同照片：</b>
				<span style="margin-bottom: 0;">（建议添加业主合同照片、业主证件照片等，要求：jpg、gif、png、pdf、word格式，最多上传9张）</span>
			</li>
			<li class="view-img">
				<div class="uploader-area" id="landlord-uploaderArea">
		        	<div class="uploadview-wrapper">
		                <div class="upload-group">
		                    <div id="queue"></div>
		                    <input id="landlord-file-upload" name="file_upload" type="file">
		                </div>
		            </div>
		        </div>
			</li>
			<li class="view-txt">
				<b><i class="bit"></i>备注说明：</b>
				<textarea class="i-txt ipt-con fl" name="landlord_mark" ignore="ignore" datatype="*1-400" errormsg="备注内容超出范围" ></textarea>
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" url="{{$add_url}}" class="btn btn2 add-landlord-btn">保存</a>
		<a href="javascript:;" class="btn btn4 btn-cancel">取消</a>
	</div>
</div>
<!--业主信息 e-->
<!--自定义金额 s-->
<div id="hide-auto-money" class="none">
	<div class="auto-money-con">
		<ul>
			<li class="auto-money-head">
				<b>合约年份</b>
				<span>租金</span>
			</li>
			<li>
				<b>第一年</b>
				<input type="text" class="ipt ipt-70 year-money rent-first" readonly="readonly" datatype="n" nullmsg="请输入金额" errormsg="金额格式不正确" />
				<span class="ml10 mr10">元/月</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="loop">
				<b>第${year}年</b>
				<input type="text" class="ipt ipt-70 year-money year-money-con" datatype="n" nullmsg="请输入金额" errormsg="金额格式不正确" />
				<span class="ml10 mr10">元/月</span>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="submit-btn">
				<a href="javascript:;" url="" class="btn btn2 ok-btn">保存</a>
				<a href="javascript:;" class="btn btn4 cancel-btn">取消</a>
			</li>
		</ul>
	</div>
</div>
<!--自定义金额 e-->

<!--新增小区 s-->
<div id="hide-add-compounds" class="none">
	<div class="checkout-con add-compounds-con">
		<ul>
			<li>
				<b><i>*</i>小区名称：</b>
				<input type="text" class="ipt ipt-300 compounds-name fl mb20" datatype="*" nullmsg="请输入小区名称" />
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>城市：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT city" readonly = 'readonly' selectVal = '{{$user.city_id}}' prev-value='{{$user.city_id}}' value="" addressURL="{{'landlord-index/getAreaCity'|url}}"/>
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO city-selectByMO">
						<ul>
						{{foreach from=$allcity item=ac}}
							<li {{if $user.city_id eq $ac.city_id}}class="selectedLi"{{/if}} selectVal = '{{$ac.city_id}}'>{{$ac.name}}</li>
						{{/foreach}}
						</ul>
					</div>
				</div>
				<!--<span class="check-error check-error-ts check-center"></span>-->
			</li>
			<li>
				<b><i>*</i>区域：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT area" readonly = 'readonly' selectVal = '' value="" datatype="areaName" nullmsg="请选择区域" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '0'>区域</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>商圈：</b>
				<div class="selectByM">
					<input type="text" class="selectByMT business" readonly = 'readonly' selectVal = '' value="" datatype="businessName" nullmsg="请选择商圈" />
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
							<li selectVal = '0'>商圈</li>
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts check-center"></span>
			</li>
			<li>
				<b><i>*</i>街道地址：</b>
			</li>
			<li>
				<textarea class="i-txt" datatype="*" nullmsg="请输入街道地址"></textarea>
				<span class="check-error check-error-ts ml5"></span>
			</li>
			<li class="checkout-btn">
				<a href="javascript:;" class="btn btn2 add_compounds_btn" actionurl="{{'landlord-index/addCommunity'|url}}">保存</a>
				<a href="javascript:;" class="btn btn4 cancel-btn">取消</a>
			</li>
		</ul>
	</div>
</div>
<!--新增小区 e-->


{{/if}}
