
		<!--首页 s-->
		<div class="apply-open station">
			<!--头部 s-->
			<div class="head">
				<div class="title">
					<i></i>
					<a href="javascript:;">功能插件></a>
					<span>功能详情</span>
				</div>
				<p>重要提醒：请保证小站上的图片和文字信息真实准确，小站仅作为出租房源的直销平台，需要房东自行推广和宣传，如跟租客之间发生任何纠纷，请自行协商解决，跟九猪无关。</p>
			</div>
			<!--头部 e-->

			<!--状态 s-->
			<div class="center">
				<h1>小站设置</h1>
				<p>您只需上传您的公寓名称、公寓信息，上传您的公寓图片，即可立即开通属于您自己的小站。</p>
			</div>
			<!--状态 e-->

			<!--提交按钮 s-->
			<div class="sub-btn">
				<a href="javascript:;" url="{{'Plugins-SubSite/applyopen'|url}}" class="btn btn1 apply-btn">申请开通小站</a>
			</div>

			<!--提交按钮 e-->

		</div>
		<!--首页 e-->

