<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-station.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript">
seajs.use("{{$smarty.const.APP_WEB_STATIC_URL}}js/plug-station_Js/opened_basic_setJs.js")
        </script>
    </head>
    <body style="background-color: #FFFFFF;">

        <div class="basic-set station" style="padding: 0; margin: 0;">
            <!--基本设置 s-->
            <div class="main main-basic">
                <div class="title">
                    <b>基本信息</b>
                </div>
                <div class="fm">
                    <ul>
                        <li>
                            <b><i class="bit">*</i>公寓名称：</b>
                            <input type="text" class="ipt ipt-330" name="flat_name" value="{{$data.flat_name}}" datatype="*" nullmsg="请填写公寓名" maxlength="20" />
                            <span class="ml10 atten">（请输入20个字符，中文占2个）</span>
                            <span class="check-error check-error-ts"></span>
                        </li>
                        <li>
                            <b><i class="bit">*</i>所在区域：</b>
                            <div class="selectByM slt-160 mr10 compounds" dataUrl="{{'user-user/findCityFromProvinceId'|url}}"  hasevent="true">
                                <input type="text" class="selectByMT bg-gray" readonly = 'readonly' selectVal = '{{$data.province_id}}' value="{{$data.province_name}}"  name="province_id" datatype="province" nullmsg="请选择省份" />
                                <span class='jt_Ctr'><span class='jt_box'></span></span>
                                <div class="selectByMO">
                                    <ul>
                                        {{foreach from=$provincedata item=v}}
                                        <li selectVal = '{{$v.province_id}}' {{if $data.province_id == $v.province_id}}{{/if}}>{{$v.name}}</li>
                                        {{/foreach}}
                                    </ul>
                                </div>
                            </div>
                            <div class="selectByM slt-160 city mr10">
                                <input type="text" class="selectByMT bg-gray" readonly = 'readonly' selectVal = '{{$data.city_id}}' value="{{$data.city_name}}" name="city_id" datatype="city" nullmsg="请选择城市" />
                                <span class='jt_Ctr'><span class='jt_box'></span></span>
                                <div class="selectByMO">
                                    <ul>
                                        {{foreach from=$cityInfo item=v}}
                                        <li selectVal = '{{$v.city_id}}' {{if $data.city_id == $v.city_id}}{{/if}}>{{$v.name}}</li>
                                        {{/foreach}}
                                    </ul>
                                </div>
                            </div>
           
                            <div class="selectByM slt-160 area">
                                <input type="text" class="selectByMT bg-gray" readonly = 'readonly' selectVal = '{{$data.area_id}}' value="{{$areaName}}" name="area_id" datatype="area" nullmsg="请选择区域" />
                                <span class='jt_Ctr'><span class='jt_box'></span></span>
                            </div>
                            <span class="check-error check-error-ts ml20"></span>
                        </li>
                        <li>
                            <b><i class="bit">*</i>联系方式：</b>
                            <input type="text" class="ipt ipt-330" name="phone" value="{{$data.phone}}" datatype="/[0-9\-]/" nullmsg="请输入联系方式" errormsg="联系方式格式错误" />
                            <span class="ml10 atten">（很重要，用于租客预约房源时使用）</span>
                            <span class="check-error check-error-ts"></span>
                        </li>
                        <li>
                            <b><i class="bit"></i>老板姓名：</b>
                            <input type="text" class="ipt ipt-330" name="name" value="{{$data.name}}"/>
                        </li>
                        <li class="li-txt">
                            <b><i class="bit"></i>品牌简介：</b>
                            <textarea class="i-txt" name="summary" maxlength="400">{{$data.summary}}</textarea>
                            <span class="ml10 atten">（最多输入400个字符，中文占2个）</span>
                        </li>
                        <li>
                            <b><i class="bit">*</i>个性网址：</b>
                            <a href="javascript:;" class="mr20">{{''|getXzUrl}}</a>
                            <input type="text" class="ipt ipt-330 bg-gray" name="domain_name" value="{{$data.domain_name}}" disabled maxlength="20" />
                            <span class="ml10 atten">（设定规则：1、至少设置3个字母；2、个性网址一旦设定保存以后不得再修改）</span>
                            <span class="check-error check-error-ts"></span>
                        </li>
                    </ul>
                </div>
            </div>
            <!--基本设置 e-->

            <!--提交按钮 s-->
            <div class="sub-btn">
                <a href="javascript:;" flat_id="{{$data.id}}" class="btn btn1 basic-btn" url="{{'Plugins-SubSite/editSetBasicInfo'|url}}">保存</a>
            </div>
            <!--提交按钮 e-->
        </div>

    </body>
</html>





