

		<!--首页 s-->
		<div class="picture-set station">
			<!--头部 s-->
			<div class="head">
				<div class="title">
					<i></i>
					<a href="javascript:;">功能插件></a>
					<span>功能详情</span>
				</div>
				<p>重要提醒：请保证小站上的图片和文字信息真实准确，小站仅作为出租房源的直销平台，需要房东自行推广和宣传，如跟租客之间发生任何纠纷，请自行协商解决，跟九猪无关。</p>
			</div>
			<!--头部 e-->

			<!--状态 s-->
			<div class="center">
				<h1>小站设置</h1>
				<p>您只需上传您的公寓名称、公寓信息，上传您的公寓图片，即可立即开通属于您自己的小站。</p>
				<div class="open-step">
					<i class="zero"></i>
					<i class="line current"></i>
					<div class="step current">
						<span>1</span>
						<span class="step-con">基本设置</span>
					</div>
					<i class="line current"></i>
					<div class="step current">
						<span>2</span>
						<span class="step-con">图片信息</span>
					</div>
					<i class="line"></i>
					<div class="step">
						<span>3</span>
						<span class="step-con">房源设置</span>
					</div>
					<i class="line"></i>
					<i class="zero"></i>
				</div>
				<div class="open-btn">
					<a href="javascript:;" class="btn btn1">正在开通中</a>
				</div>
			</div>
			<!--状态 e-->

			<!--图片信息 s-->
			<div class="main main-picture" dataUrl="{{'Plugins-SubSite/getDefaultImg'|url}}">
				<div class="title">
					<b class="mr10">图片信息</b>
					<span>（丰富您的小站，让您的小站更具吸引力，一眼就能让人记住）</span>
				</div>
				<div class="picture picture-flat">
					<div class="picture-left">
						<b>公寓品牌形象图片</b>
						<div class="picture-big">
							<div class="upload-pic" filename="FihojkoAUbtdQ81mRMS1R9t5t1sR" datatype="1">
								<img src="{{$pic1}}"/>
							</div>
							<div class="cut-pic cut-pic-2-1">
								<img src="{{$pic1}}"/>
							</div>
							<div class="pl-shade">
								<div class="pl-shade-bg"></div>
								<div class="uploader-area" id="open-uploaderArea">
						        	<div class="uploadview-wrapper">
						                <div class="upload-group">
						                    <div id="queue"></div>
						                    <input id="open-file-upload" name="file_upload" type="file">
						                </div>
						            </div>
						        </div>
								<p>（为保证图片质量清晰，请上传比例为2:1的图片）</p>
							</div>
						</div>
					</div>
					<div class="picture-center">
						<b>系统默认图片</b>
						<ul>
							<li class="mr1 mb1 current pc-top" key="">
								<img width="223" src="{{$pic1}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span style="display: none;">点击使用</span>
									<i class="ifont">&#xf00b2;</i>
								</div>
							</li>
							<li class="mb1 pc-top" key="FikNLaaPDlFgtGXpe-8hDvuI_qUX">
								<img width="223" src="{{$pic2}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="mr1 pc-top" key="FrEAxjn2sXPmh-lMqiyysB4SBUuS">
								<img width="223" src="{{$pic3}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="pc-top" key="Funf3PwVo3grXTOnOV6_wGdCfQdy">
								<img width="223" src="{{$pic4}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
						</ul>
					</div>
					<div class="picture-right">
						<b>效果预览</b>
						<div class="preview">
							<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_10.png"/>
						</div>
					</div>
				</div>

				<div class="picture picture-brand">
					<div class="picture-left">
						<b>品牌故事图片</b>
						<div class="picture-big">
							<div class="upload-pic" filename="FivvcKnizjjF5wSk1p7y-pIdXiNZ" datatype="2">
								<img src="{{$pic5}}"/>
							</div>
							<div class="cut-pic cut-pic-1-1">
								<img src="{{$pic5}}"/>
							</div>
							<div class="pl-shade">
								<div class="pl-shade-bg"></div>
								<div class="uploader-area" id="opens-uploaderArea">
						        	<div class="uploadview-wrapper">
						                <div class="upload-group">
						                    <div id="queue"></div>
						                    <input id="opens-file-upload" name="file_upload" type="file">
						                </div>
						            </div>
						        </div>
								<p>（为保证图片质量清晰，请上传比例为2:1的图片）</p>
							</div>
						</div>
					</div>
					<div class="picture-center">
						<b>系统默认图片</b>
						<ul>
							<li class="mr1 mb1 current" key="FivvcKnizjjF5wSk1p7y-pIdXiNZ" style="background: #f9a03c;">
								<img width="148" src="{{$pic5}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span style="display: none;">点击使用</span>
									<i class="ifont">&#xf00b2;</i>
								</div>
							</li>
							<li class="mb1" key="FjynuLpxTGBAvVrY7uDy59Qn9XMK" style="background: #ffb2b2;">
								<img width="148" src="{{$pic6}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="mr1" key="Fs4BaXqfQLQBQ6qCHSTqLolgmJHf" style="background: #e0e0e0;">
								<img width="148" src="{{$pic7}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li key="Fi2YgYSSk3jQx3_Prh-7ohONnSVr" style="background: #fcb300;">
								<img width="148" src="{{$pic8}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
						</ul>
					</div>
					<div class="picture-right">
						<b>效果预览</b>
						<div class="preview">
							<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_11.png"/>
						</div>
					</div>
				</div>
			</div>
			<!--图片信息 e-->

			<!--提交按钮 s-->
			<div class="sub-btn">
				<a href="javascript:;" url="{{'Plugins-SubSite/setPictureInfo'|url|cat:'&flat_id='|cat:$flat_id|cat:'&city_id='|cat:$city_id|cat:'&dn='|cat:$domain_name}}"  class="btn btn1 picture-btn" >下一步</a>

			</div>

			<!--提交按钮 e-->

		</div>
		<!--首页 e-->

