<!--首页 s-->
<div class="open-basic-set station">
    <!--头部 s-->
    <div class="head">
        <div class="title">
            <i></i>
            <a href="javascript:;">功能插件></a>
            <span>功能详情</span>
        </div>
        <p>重要提醒：请保证小站上的图片和文字信息真实准确，小站仅作为出租房源的直销平台，需要房东自行推广和宣传，如跟租客之间发生任何纠纷，请自行协商解决，跟九猪无关。</p>
    </div>
    <!--头部 e-->

    <!--状态 s-->
    <div class="center">
        <h1>小站设置</h1>
        <p>您只需上传您的公寓名称、公寓信息，上传您的公寓图片，即可立即开通属于您自己的小站。</p>
        <div class="open-step">
            <i class="zero"></i>
            <i class="line current"></i>
            <div class="step current">
                <span>1</span>
                <span class="step-con">基本设置</span>
            </div>
            <i class="line line-two"></i>
            <div class="step step-two">
                <span>2</span>
                <span class="step-con">图片信息</span>
            </div>
            <i class="line"></i>
            <div class="step">
                <span>3</span>
                <span class="step-con">房源设置</span>
            </div>
            <i class="line"></i>
            <i class="zero"></i>
        </div>
        <div class="open-btn">
            <a href="javascript:;" class="btn btn1">正在开通中</a>
        </div>
    </div>
    <!--状态 e-->

    <!--基本设置 s-->
    <div class="main main-basic">
        <div class="title">
            <b>基本信息</b>
        </div>
        <div class="fm">
            <ul>
                <li>
                    <b><i class="bit">*</i>公寓名称：</b>
                    <input type="text" class="ipt ipt-330" name="flat_name" datatype="*" nullmsg="请填写公寓名" maxlength="20" />
                    <span class="ml10 atten">（请输入20个字符，中文占2个）</span>
                    <span class="check-error check-error-ts"></span>
                </li>
                <li>
                    <b><i class="bit">*</i>所在区域：</b>
                    <div class="selectByM slt-160 mr10 compounds" dataUrl="{{'user-user/findCityFromProvinceId'|url}}" hasevent="true">
                        <input type="text" class="selectByMT" readonly = 'readonly' selectVal = '0' value="" name="province_id" datatype="province" nullmsg="请选择省份" />
                        <span class='jt_Ctr'><span class='jt_box'></span></span>
                        <div class="selectByMO">
                            <ul>
                                {{foreach from=$provincedata item=v}}
                                <li selectVal = '{{$v.province_id}}'>{{$v.name}}</li>
                                {{/foreach}}
                            </ul>
                        </div>
                    </div>
                    <div class="selectByM slt-160 mr10 city" dataurl="{{'User-User/getAreaList'|url}}">
                        <input type="text" class="selectByMT" readonly = 'readonly' selectVal = '0' value="" name="city_id" datatype="city" nullmsg="请选择城市" />
                        <span class='jt_Ctr'><span class='jt_box'></span></span>
                        <div class="selectByMO">
                            <ul>
                                <!--<li selectVal = '1'>城市</li>-->
                            </ul>
                        </div>
                    </div>
                    <div class="selectByM slt-160 area">
                        <input type="text" class="selectByMT" readonly = 'readonly' selectVal = '0' value="所有区域" name="area_id" datatype="area" nullmsg="请选择商圈" />
                        <span class='jt_Ctr'><span class='jt_box'></span></span>
                        <div class="selectByMO">
                            <ul>
                                <!--<li selectVal = '1'>商圈</li>-->
                            </ul>
                        </div>
                    </div>
                    <span class="check-error check-error-ts"></span>
                </li>
                <li>
                    <b><i class="bit">*</i>联系方式：</b>
                    <input type="text" class="ipt ipt-330" name="phone" datatype="/[0-9\-]/" nullmsg="请输入联系方式" errormsg="联系方式格式错误" />
                    <span class="ml10 atten">（很重要，用于租客预约房源时使用）</span>
                    <span class="check-error check-error-ts"></span>
                </li>
                <li>
                    <b><i class="bit"></i>老板姓名：</b>
                    <input type="text" class="ipt ipt-330" name="name" />
                </li>
                <li class="li-txt">
                    <b><i class="bit"></i>品牌简介：</b>
                    <textarea class="i-txt" name="summary" maxlength="400"></textarea>
                    <span class="ml10 atten">（最多输入400个字符，中文占2个）</span>
                </li>
                <li>
                    <b><i class="bit">*</i>个性网址：</b>
                    <a href="javascript:;" class="mr20">{{''|getXzUrl}}</a>
                    <input type="text" class="ipt ipt-330" name="domain_name" datatype="website" nullmsg="请输入网址" errormsg="网址格式错误" maxlength="20" />
                    <span class="ml10 atten">（设定规则：1、至少设置3个字母；2、个性网址一旦设定保存以后不得再修改）</span>
                    <span class="check-error check-error-ts"></span>
                </li>
            </ul>
        </div>
    </div>
    <!--基本设置 e-->

    <!--提交按钮 s-->
    <div class="sub-btn">
        <a href="javascript:;" class="btn btn1 basic-btn" url="{{'Plugins-SubSite/setBasicInfo'|url}}">下一步</a>
    </div>

    <!--提交按钮 e-->

</div>
<!--首页 e-->

