
<!--首页 s-->
<div class="opened-basic-set station">
	<!--头部 s-->
	<div class="head head-auto">
		<div class="title">
			<i></i>
			<a href="javascript:;">功能插件></a>
			<span>功能详情</span>
		</div>
		<p>重要提醒：请保证小站上的图片和文字信息真实准确，小站仅作为出租房源的直销平台，需要房东自行推广和宣传，如跟租客之间发生任何纠纷，请自行协商解决，跟九猪无关。</p>
	</div>
	<!--头部 e-->

	<!--状态 s-->
	<div class="center">
		<h1>小站设置</h1>
		<p>您只需上传您的公寓名称、公寓信息，上传您的公寓图片，即可立即开通属于您自己的小站。</p>
		<div class="menu">
			<ul>
				<li class="current menu-basic">
					<a href="javascript:;" dataurl="{{'Plugins-SubSite/basic'|url|cat:'&flat_id='|cat:$data.id}}">基本设置</a>
				</li>
				<li class="menu-picture">
					<a href="javascript:;" dataurl="{{'Plugins-SubSite/picture'|url|cat:'&flat_id='|cat:$data.id}}">图片信息</a>
				</li>
				<li class="menu-house">
					<a href="javascript:;" dataurl="{{'Plugins-SubSite/house'|url|cat:'&flat_id='|cat:$data.id}}">房源设置</a>
				</li>
				<li class="menu-data">
					<a href="javascript:;" dataurl="{{'Plugins-SubSite/datacount'|url|cat:'&flat_id='|cat:$data.id}}">数据统计</a>
				</li>
				<li class="li-spe menu-wechat">
					<a href="javascript:;" dataurl="{{'Plugins-SubSite/weixin'|url|cat:'&flat_id='|cat:$data.id}}">微信功能管理</a>
				</li>
			</ul>
		</div>
		<div class="open-list">
			<ul>
			{{foreach from=$dataArr key=k item=v}}
				<li>
					<a href="javascript:;" class="fsb {{if $k eq 0}}current{{/if}}" dataurl = "{{'Plugins-SubSite/basic'|url|cat:'&flat_id='|cat:$v.id}}" flat_id="{{$v.id}}" >{{$v.flat_name}}</a>
					<span>已开通</span>
				</li>
			{{/foreach}}
			</ul>
		</div>
		<div class="apply-station">
			<i class="ifont">&#xf0037;</i>
			<a href="javascript:;" class="appen-btn" dataurl="{{'Plugins-SubSite/setBasicInfo'|url}}" >申请新小站</a>
		</div>
	</div>
	<!--状态 e-->


	<iframe width="100%" height="1000px" id="opened_iframe" frameborder="no" border="0" marginwidth="0" marginheight="0" src="{{'Plugins-SubSite/basic'|url}}"></iframe>



</div>
<!--首页 e-->



