<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-station.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/uplodify/uploadify.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/cropper/cropper.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/dialog/artDialog/ui-dialog.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript">
        		seajs.use("{{$smarty.const.APP_WEB_STATIC_URL}}js/plug-station_Js/opened_picture_setJs.js")
        </script>
	</head>
	<body style="background-color: #FFFFFF;">
		<!--首页 s-->
		<div class="picture-set station" style="margin: 0; padding: 0;">

			<!--图片信息 s-->
			<div class="main main-picture" dataurl="{{'Plugins-SubSite/getDefaultImg'|url}}">
				<div class="title">
					<b class="mr10">图片信息</b>
					<span>（丰富您的小站，让您的小站更具吸引力，一眼就能让人记住）</span>
				</div>
				<div class="picture picture-flat">
					    <div class="picture-left">
                        <b>公寓品牌形象图片</b>
                        <div class="picture-big">
                            <div class="upload-pic" filename="{{$default_key1}}" datatype="1">
                                <img src="{{$default_img1}}"/>
                            </div>
                            <div class="cut-pic cut-pic-2-1">
                                <img src="{{$default_img1}}"/>
                            </div>
                            <div class="pl-shade">
                                <div class="pl-shade-bg"></div>
                                <div class="uploader-area" id="open-uploaderArea">
                                    <div class="uploadview-wrapper">
                                        <div class="upload-group">
                                            <div id="queue"></div>
                                            <input id="open-file-upload" name="file_upload" type="file">
                                        </div>
                                    </div>
                                </div>
                                <p>（为保证图片质量清晰，请上传比例为2:1的图片）</p>
                            </div>
                        </div>
                    </div>
					
					<div class="picture-center">
						<b>系统默认图片</b>
						<ul>
							<li class="mr1 mb1 current pc-top" key="">
								<img width="223" src="{{$pic1}}" />
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="mb1 pc-top" key="">
								<img width="223" src="{{$pic2}}" />
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" >&#xf00b2;</i>
								</div>
							</li>
							<li class="mr1 pc-top" key="">
								<img width="223" src="{{$pic3}}" />
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="pc-top" key="">
								<img width="223" src="{{$pic4}}" />
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
						</ul>
					</div>
					<div class="picture-right">
						<b>效果预览</b>
						<div class="preview">
							<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_10.png"/>
						</div>
					</div>
				</div>

				<div class="picture picture-brand">
					
					 <div class="picture-left">
                        <b>品牌故事图片</b>
                        <div class="picture-big">
                            <div class="upload-pic" filename="{{$default_key2}}" datatype="2">
                                <img src="{{$default_img2}}"/>
                            </div>
                            <div class="cut-pic cut-pic-1-1">
                                <img src="{{$default_img2}}"/>
                            </div>
                            <div class="pl-shade">
                                <div class="pl-shade-bg"></div>
                                <div class="uploader-area" id="opens-uploaderArea">
                                    <div class="uploadview-wrapper">
                                        <div class="upload-group">
                                            <div id="queue"></div>
                                            <input id="opens-file-upload" name="file_upload" type="file">
                                        </div>
                                    </div>
                                </div>
                                <p>（为保证图片质量清晰，请上传比例为2:1的图片）</p>
                            </div>
                        </div>
                    </div>
					<div class="picture-center">
						<b>系统默认图片</b>
						<ul>
							<li class="mr1 mb1 current" key="" style="background: #f9a03c;">
								<img width="148" src="{{$pic5}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="mb1" key="" style="background: #ffb2b2;">
								<img width="148" src="{{$pic6}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li class="mr1" key="" style="background: #e0e0e0;">
								<img width="148" src="{{$pic7}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
							<li key="" style="background: #fcb300;">
								<img width="148" src="{{$pic8}}"/>
								<div class="pc-shade"></div>
								<div class="pc-use">
									<span>点击使用</span>
									<i class="ifont" style="display: none;">&#xf00b2;</i>
								</div>
							</li>
						</ul>
					</div>
					<div class="picture-right">
						<b>效果预览</b>
						<div class="preview">
							<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/p_11.png"/>
						</div>
					</div>
				</div>
			</div>
			<!--图片信息 e-->

			<!--提交按钮 s-->
			<div class="sub-btn">
				<a href="javascript:;" dataurl="{{'Plugins-SubSite/picture'|url|cat:$data.id}}" flat_id ={{$id}} class="btn btn1 picture-btn">保存</a>
			</div>

			<!--提交按钮 e-->
			
		</div>
		<!--首页 e-->

	</body>
</html>