<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-station.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript">
        		seajs.use("{{$smarty.const.APP_WEB_STATIC_URL}}js/plug-station_Js/wechat_loginJs.js")
        </script>
	</head>
	<body style="background-color: #FFFFFF;">			
		
		<!--首页 s-->
		<div class="wechat-login station">
		    <!--信息 s-->
		    <div class="main-login main">
		        <form >
		            <h1>绑定微信登录</h1>
		            <div class="main-login-col">
		                <b>账号</b>
		                <input type="text" name="username" class="ipt ipt-340" placeholder="请填写微信公众号" />
		            </div>
		            <div class="main-login-col">
		                <b>密码</b>
		                <input type="password" name="pwd" class="ipt ipt-340" />
		            </div>
		            <div class="main-login-col">
		                <b class="mt20">验证码</b>
		                <input type="text" name="code" class="ipt ipt-200 mt20" />
		                <a href="javascript:;" class="main-login-code">
		                    <img src="{{'Plugins-SubSite/yanzhengma'|url}}" />
		                </a>
		            </div>
		            <div class="main-login-col main-login-btn">
		            	<input type="hidden" name="flat_id" value="{{'flat_id'|I}}" />
		                <a href="javascript:;" dataurl="{{'Plugins-SubSite/weixin_login'|url}}" id="login" class="btn btn1">登录</a>
		            </div>   
		            <div class="main-login-col main-login-appen">
		                <p>暂无账号，<a href="https://mp.weixin.qq.com/" target="_black">立即申请</a></p>
		            </div>
		        </form>
		        <div class="main-login-col main-login-mark">
					<p>注：登录前，请确认账号是否开启了风险操作保护，如果开启，可能会导致账号无法授权！<a href="javascript:;" class="close-risk-btn">如何关闭保护</a></p>		        	
		        </div>
		    </div>
		    <!--信息 e-->
		</div>
		<!--首页 e-->
		
		<!--关闭风险操作模板 s-->
		<div id="hide-close-risk" style="display: none;">
			<div class="close-risk-box">
				<!--<i></i>-->
				<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/105_03.png" />
			</div>
		</div>
		<!--关闭风险操作模板 e-->

	</body>
</html>