		<!--分散式公寓-房间详情 s-->
		<div class="distributed_room_view view" hasform="true">
			<div class="view-head">
				<h1>房间详情</h1>
				<span class="red">未出租</span>
			</div>
			<div class="view-con">
				<ul>
					<li class="room-num-box">
						{{foreach from=$room_number key=rkey item=rval}}
						<div class="room-num {{if $rkey eq 1}}current{{/if}}" data-index="{{$rkey}}">
							<span>room</span>
							<i>{{$rkey}}</i>
						</div>
						{{/foreach}}
					</li>
					<li class="room-operate">
						<a href="javascript:;" class="btn btn4 copy-cur-form-data">复制</a>
						<a href="javascript:;" class="btn btn4 paste-cur-form-data">粘贴</a>
					</li>
				</ul>
				{{foreach from=$room_number key=rkey item=rval}}
				<ul class="rommForm {{if $rkey neq 1}}none{{/if}}" {{if $edit_id eq 1}}room-id="{{$rval.room_id}}"{{/if}} data-index="{{$rkey}}">
					<li>
						<i class="bit">*</i>
						<b>房间编号：</b>
						<input type="text" {{if $edit_id eq 1}}value="{{$rval.custom_number}}"{{/if}} name="custom_number" nullmsg="请输入房间编号" errormsg="房间编号不能超过20位字符" datatype="/^.{1,20}$/" class="ipt ipt-385" placeholder="输入房源编号" />
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="col-copy-paste col-rent-room">
						<b>出租房间：</b>
						<div class="selectByM slt-120 mr20">
							<input type="text" name="room_type" class="selectByMT" readonly = 'readonly' selectVal = "{{if $edit_id eq 1}}{{$rval.room_type}}{{else}}main{{/if}}" value=""/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
								{{if $edit_id eq 1}}
									<li {{if $rval.room_type eq 'main'}} class="selectedLi"{{/if}} selectVal = 'main'>主卧</li>
									<li {{if $rval.room_type eq 'second'}} class="selectedLi"{{/if}} selectVal = 'second'>次卧</li>
									<li {{if $rval.room_type eq 'guest'}} class="selectedLi"{{/if}} selectVal = 'guest'>客卧</li>
								{{else}}
									<li selectVal = 'main'>主卧</li>
									<li selectVal = 'second'>次卧</li>
									<li selectVal = 'guest'>客卧</li>
								{{/if}}
								</ul>
							</div>
						</div>
						<span>可住：</span>
						<div class="selectByM slt-120">
							<input  type="text" readonly="readonly" name="occupancy_number"  class="selectByMT" selectVal = "{{$rval.occupancy_number}}" value="{{$rval.occupancy_number}}"/>
							<span class="jt_Ctr"><span class="jt_box"></span></span>
							<div class="selectByMO">
								<ul>
									{{if $edit_id eq 1}}
										{{foreach from=$pay_config key=pukey item=puval}}
											{{if $pukey neq 0}}
											<li {{if $pukey eq $rval.occupancy_number}}class="selectedLi"{{/if}} selectVal='{{$pukey}}'>{{$puval}}</li>
											{{/if}}
										{{/foreach}}
									{{else}}
										{{foreach from = $pay_config key=pkey item=pval}}
											{{if $pkey neq 0}}
											<li selectVal = '{{$pkey}}'>{{$pval}}</li>
											{{/if}}
										{{/foreach}}
									{{/if}}
								</ul>
							</div>
						</div>
						<span class="ml5">人</span>
						<input {{if $edit_id eq 1}}value="{{$rval.area}}"{{/if}} type="text" name="area" class="ipt ipt-80 ml10" datatype="lengthTest" ignore="ignore" errormsg="请输入长度不超过六位的正整数或者小数(保留两位小数)"/>
						<span class="ml5">㎡</span>
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="col-copy-paste col-rent-payment">
						<i class="bit">*</i>
						<b>房间租金：</b>
						<input {{if $edit_id eq 1}}value="{{$rval.money}}"{{/if}} type="text" name="money" class="ipt ipt-80 mr10" datatype="floatGroup"  errormsg="请输入长度不超过八位的正整数或者小数(保留两位小数)" />
						<span class="mr20">元/月</span>
						<span class="mr10">押</span>
						<div class="selectByM slt-90">
							<input type="text" name="detain" class="selectByMT" readonly = 'readonly' selectVal = '{{if $edit_id eq 1}}{{$rval.detain}}{{else}}1{{/if}}' value="{{if $edit_id eq 0}}一{{/if}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
								{{if $edit_id eq 1}}
									{{foreach from=$pay_config key=pk item=pv}}
										<li {{if $rval.detain eq $pk}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
									{{/foreach}}
								{{else}}
									{{foreach from=$pay_config key=pk item=pv}}
										<li {{if $pk eq 1}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
									{{/foreach}}
								{{/if}}
								</ul>
							</div>
						</div>
						<span class="mr10 ml10">付</span>
						<div class="selectByM slt-90 mr20">
							<input type="text" name="pay" class="selectByMT" readonly = 'readonly' selectVal = "{{if $edit_id eq 1}}{{$rval.pay}}{{else}}3{{/if}}" value="{{if $edit_id eq 0}}三{{/if}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
								{{if $edit_id eq 1}}
									{{foreach from=$pay_config key=pk item=pv}}
										{{if $pk neq 0}}
											<li {{if $rval.pay eq $pk}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
										{{/if}}
									{{/foreach}}
								{{else}}
									{{foreach from=$pay_config key=pk item=pv}}
										{{if $pk neq 0}}
											<li {{if $pk eq 3}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
										{{/if}}
									{{/foreach}}
								{{/if}}
								</ul>
							</div>
						</div>
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="view-config col-copy-paste">
						<b>房间配置：</b>
							<div class="house-config clearfix checkbox-area" fm="room_config">
						{{if $edit_id eq 1}}
							{{foreach from=$rval.room_config key=pfk item=pfv}}
							<div class="check-box check-box-o {{if $pfv.name eq "飘窗" or $pfv.name eq "阳台" or $pfv.name eq "卫生间"}}canntchoose{{/if}}">
								<label {{if $pfv.is_read eq 1}}class="checked"{{/if}}>
									<span {{if $pfv.is_read eq 1}}style="display: inline;"{{/if}} class="choose ifont1">&#xe60c;</span>
								</label> 
								<input {{if $pfv.is_read eq 1}}checked="checked"{{/if}} name="centralized_add_house_room_config" type="checkbox" value="{{$pfv.value}}" /> 
								<span>{{$pfv.name}}</span>
							</div>
							{{/foreach}}
						{{else}}
							{{foreach from = $public_config key=rvkey item=rvval}}
							<div class="check-box check-box-o {{if $rvval eq "飘窗" or $rvval eq "阳台" or $rvval eq "卫生间"}}canntchoose{{/if}}">
								<label><i class="choose ifont1">&#xe60c;</i></label>
								<input type="checkbox" value="{{$rvkey}}"/>
								<span>{{$rvval}}</span>
							</div>
							{{/foreach}}
						{{/if}}
						<div class="check-box check-box-a fold">
							<label class="checkAll"><i class="choose ifont1">&#xe60c;</i></label>
							<input type="checkbox"/>
							<span class="select-all">全选</span>
						</div>
						<!--<div class="chose-all-items">
							<span class="select-all btn btn4 fold">全选</span>
						</div>-->
							<div class="check-box roomconfig_diy ml20">
								<a href="javascript:;" class="roomconfig_dy">自定义房间配置</a>
							</div>
							<div class="roomconfig-diy-txt">
								<div class="roomconfig-diy-txt-a">
									<ul>
										<li><label class='checkbox'><span class='choose ifont1'>&#xe60c;</span></label>全选</li>
										<li><a url="{{'Company/addconfig'|url}}" href="javascript:;" class="config-auto-add">新增配置</a></li>
										<li><a href="javascript:;" url="{{'Company/deleteconfig'|url}}" class="config-auto-deleteall">删除配置</a></li>
										<li><a href="javascript:;" class="config-auto-submit">保存配置</a></li>
									</ul>
								</div>
								<ul class="roomconfig-diy-txt-auto"></ul>
							</div>
						</div>
					</li>
					<li>
						<b>房间照片：</b>
						<p style="float:left;margin-top:8px;color:#fd3c69;">(请上传真实、美观的房间图片，要求：jpg、gif、png格式，最多上传9张)</p>
					</li>
					<li>
						<div class="row-upload-zone">
							{{if $edit_id eq 0}}
							<div class="uploader-area" id="distri_hsrm-add{{$rkey}}" fm="image">
					        	<div class="uploadview-wrapper">
					                <div class="upload-group">
					                    <div id="distri_hsrm-add-queue{{$rkey}}"></div>
					                    <input id="distri_hsrm_add_file_upload{{$rkey}}" name="file_upload" type="file">
					                </div>
					            </div>
					        </div>
					        {{/if}}
					        <!--编辑状态绑定元素-->
					        {{if $edit_id eq 1}}
					        <div class="uploader-area" id="distri_hsrm-edit{{$rkey}}" fm="image">
						       {{foreach from=$rval.imag key=imgkey item=imgval}}
						      		<div filename="{{$imgval.key}}" class="upload-imgview">
						      			<img class="" style="_display: none;" src="{{imageView2 op='w/60/h/60' key=$imgval.key}}">
						      			<span class="ie7bug"></span><i class="ifont deleteImg">&#xe627;</i>
						      			<input type="hidden" name="images[new][room1][]" value="{{$imgval.key}}">
						      		</div>
						        {{/foreach}}
					        	<div class="uploadview-wrapper">
					                <div class="upload-group">
					                    <div id="distri_hsrm-edit-queue{{$rkey}}"></div>
					                    <input id="distri_hsrm_edit_file_upload{{$rkey}}" name="file_upload" type="file">
					                </div>
					            </div>
					        </div>
					        {{/if}}
					        <!--编辑状态绑定元素end-->
						</div>
					</li>
					<li class="romForm-col-bot">
						<div class="view-btn room-btn-bar">
							<a href="javascript:;" is_edit={{if $edit_id eq 1}}1{{else}}''{{/if}}  house-id="{{$house_id}}" room-count="{{$count}}" data-btn="{{$rkey}}" class="btn btn2 addAllRoomTrig" editUrl="{{'House-Room/edit'|url}}" addUrl="{{'House-Room/add'|url}}">保存全部房间</a>
						</div>
					</li>
				</ul>
				{{/foreach}}
			</div>
		</div>
		<!--分散式公寓-房间详情 e-->
		<!--多选删除遮罩模板-->
			<div class="deletemoreauto none">
				<div class="top">
					<div class="top1">
						<span class="fl">正在删除...</span>
						<span class="fr">
							<span class="num_cur">1</span>/<span class="num_total"></span>
						</span>
					</div>
					<div class="top2">
						<div class="top2a">
							<div class="top2at"></div>
						</div>
					</div>
				</div>
				<div class="content">
					<table>
						<tr><th class="zb">房间配置名称</th><th class="yb">删除结果</th></tr>
						<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
					</table>
				</div>
			</div>

