		<!--分散式公寓-房间详情 s-->
		<div class="distributed_room_view view" hasform="true">
			<div class="view-head">
				<h1>房间详情</h1>
				{{if $room_data.status eq 1}}
				<span class="red" style="margin-right: 10px;">未出租</span>
				{{/if}}
				{{if $room_data.status eq 2}}
				<span class="blue" style="margin-right: 10px;">已出租</span>
				{{/if}}
				{{if $room_data.status eq 3}}
				<span class="black" style="margin-right: 10px;">停用</span>
				{{/if}}
				{{if $room_data.is_yytz == 1}}
				<span class="yellow" style="margin-right: 10px;">预约退租</span>
				{{/if}}
				{{if $fee_show eq 1 and $contract_id gt 0}}
				<a href="#{{'meterreading/index'|url|cat:'&room_id='|cat:{{$room_data.room_id}}|cat:'&house_type=1'|cat:'&house_id=0'}}">抄表</a>
				{{/if}}
				{{if $contract_id gt 0}}
				<a href="#{{'finance-serial/newaddincome'|url|cat:'&room_id='|cat:{{$room_data.room_id}}|cat:'&house_type=1'|cat:'&charge_contract_id='|cat:$contract_id|cat:'&house_id='|cat:$room_data.house_id|cat:'&charge_source=room_charge'}}">收费</a>
				{{/if}}
				{{if $room_data.is_yd eq 1}}
	                <a href="#{{'tenant-index/reserve'|url|cat:'&room_id='|cat:$house_data.house_name|cat:'&house_type=1'|cat:'&reserve_id='|cat:$resver_data.reserve_id}}">预定</a>
				{{/if}}
				{{if $contract_id gt 0}}
				<a href="#{{'tenant-index/edit'|url|cat:'&'|cat:'contract_id='|cat:$contract_id}}">合同</a>
				{{/if}}
				{{if $room_data.status eq 3}}
				<a href="javascript:;" class="stop-room"  data-url="{{'house-room/getstop'|url|cat:"&room_id="|cat:$room_data.room_id}}">停用</a>
				{{/if}}
				{{if $room_data.is_yytz == 1}}
				<a href="javascript:;" class="yytz-room"  room_id="{{$room_data.room_id}}" reser_back_id="{{$reserve_back_info.reserve_back_id}}" data-url="{{'house-room/getyytzu'|url|cat:"&room_id="|cat:$room_data.room_id}}">预约退租</a>
				{{/if}}
			</div>
			<div class="view-con">
				<!--<ul>
					<li class="room-operate">
						<a href="javascript:;" class="btn btn4 copy-cur-form-data">复制</a>
						<a href="javascript:;" class="btn btn4 paste-cur-form-data">粘贴</a>
					</li>
				</ul>-->
				<ul class="rommForm" room-id="" data-index="">
					<li>
						<i class="bit">*</i>
						<b>房间编号：</b>
						<input type="text" value="{{$room_data.custom_number}}" name="custom_number" nullmsg="请输入房间编号" errormsg="房间编号不能超过20位字符" datatype="/^.{1,20}$/" class="ipt ipt-385" placeholder="输入房源编号" />
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="col-copy-paste col-rent-room">
						<b>出租房间：</b>
						<div class="selectByM slt-120 mr20">
							<input type="text" name="room_type" class="selectByMT" readonly = 'readonly' selectVal = "{{$room_data.room_type}}" value=""/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
									<li {{if $room_data.room_type eq 'main'}}class="selectedLi"{{/if}} selectVal = 'main'>主卧</li>
									<li {{if $room_data.room_type eq 'second'}}class="selectedLi"{{/if}}selectVal = 'second'>次卧</li>
									<li {{if $room_data.room_type eq 'guest'}}class="selectedLi"{{/if}}selectVal = 'guest'>客卧</li>
								</ul>
							</div>
						</div>
						<span>可住：</span>
						<div class="selectByM slt-120">
							<input  type="text" readonly="readonly" name="occupancy_number"  class="selectByMT" selectVal = "{{$room_data.occupancy_number}}" value="{{$room_data.occupancy_number}}"/>
							<span class="jt_Ctr"><span class="jt_box"></span></span>
							<div class="selectByMO">
								<ul>
									{{foreach from=$config key=pk item=pv}}
										{{if $pk neq 0}}
										<li {{if $room_data.occupancy_number eq $pk}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
										{{/if}}
									{{/foreach}}
								</ul>
							</div>
						</div>
						<span class="ml5">人</span>
						<input  type="text" name="area" value="{{$room_data.area}}" class="ipt ipt-80 ml10" datatype="lengthTest" ignore="ignore" errormsg="请输入长度不超过六位的正整数或者小数(保留两位小数)"/>
						<span class="ml5">㎡</span>
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="col-copy-paste col-rent-payment">
						<i class="bit">*</i>
						<b>房间租金：</b>
						<input value="{{$room_data.money}}" type="text" name="money" class="ipt ipt-80 mr10" datatype="floatGroup"  errormsg="请输入长度不超过八位的正整数或者小数(保留两位小数)" />
						<span class="mr20">元/月</span>
						<span class="mr10">押</span>
						<div class="selectByM slt-90">
							<input type="text" name="detain" class="selectByMT" readonly = 'readonly' selectVal = '' value=""/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
									{{foreach from=$config key=pk item=pv}}
										<li {{if $room_data.detain eq $pk}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
									{{/foreach}}
								</ul>
							</div>
						</div>
						<span class="mr10 ml10">付</span>
						<div class="selectByM slt-90 mr20">
							<input type="text" name="pay" class="selectByMT" readonly = 'readonly' selectVal = "" value=""/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
									{{foreach from=$config key=pk item=pv}}
											{{if $pk neq 0}}
											<li {{if $room_data.pay eq $pk}}class="selectedLi"{{/if}} selectVal = '{{$pk}}'>{{$pv}}</li>
											{{/if}}
									{{/foreach}}
								</ul>
							</div>
						</div>
						<span class="check-error check-error-ts check-error-auto"></span>
					</li>
					<li class="view-config col-copy-paste">
						<b>房间配置：</b>
							<div class="house-config clearfix checkbox-area" fm="room_config">
							{{foreach from=$public_facilities key=pfk item=pfv}}
								<div class="check-box check-box-o">
									<label {{if $pfv.is_read eq 1}}class="checked"{{/if}}>
										<span {{if $pfv.is_read eq 1}}style="display: inline;"{{/if}} class="choose ifont1">&#xe60c;</span>
									</label> 
									<input {{if $pfv.is_read eq 1}}checked="checked"{{/if}}  type="checkbox" value="{{$pfv.value}}" /> 
									<span>{{$pfv.name}}</span>
								</div>
							{{/foreach}}
							<div class="check-box check-box-a fold">
								<label class="checkAll"><i class="choose ifont1">&#xe60c;</i></label>
								<input type="checkbox"/>
								<span class="select-all">全选</span>
							</div>
							<!--<div class="chose-all-items">
								<span class="select-all btn btn4 fold">全选</span>
							</div>-->
							<div class="check-box roomconfig_diy ml20">
								<a href="javascript:;" class="roomconfig_dy">自定义房间配置</a>
							</div>
							<div class="roomconfig-diy-txt">
								<div class="roomconfig-diy-txt-a">
									<ul>
										<li><label class='checkbox'><span class='choose ifont1'>&#xe60c;</span></label>全选</li>
										<li><a url="{{'Company/addconfig'|url}}" href="javascript:;" class="config-auto-add">新增配置</a></li>
										<li><a href="javascript:;" url="{{'Company/deleteconfig'|url}}" class="config-auto-deleteall">删除配置</a></li>
										<li><a href="javascript:;" class="config-auto-submit">保存配置</a></li>
									</ul>
								</div>
								<ul class="roomconfig-diy-txt-auto"></ul>
							</div>
						</div>
					</li>
					<li>
						<b>房间照片：</b>
						<p style="float:left;margin-top:8px;color:#fd3c69;">(请上传真实、美观的房间图片，要求：jpg、gif、png格式，最多上传9张)</p>
					</li>
					<li>
						<div class="row-upload-zone">
					        <!--编辑状态绑定元素-->
					        <div class="uploader-area" id="distri_hsrm-detail{{$rkey}}" fm="image">
					       	{{foreach from=$imag key=imgkey item=imgval}}
					      		<div filename="{{$imgval.key}}" class="upload-imgview">
					      			<img class="" style="_display: none;" src="{{imageView2 op='w/60/h/60' key=$imgval.key}}">
					      			<span class="ie7bug"></span><i class="ifont deleteImg">&#xe627;</i>
					      			<input type="hidden" name="images[new][room1][]" value="{{$imgval.key}}">
					      		</div>
					        {{/foreach}}
					        	<div class="uploadview-wrapper">
					                <div class="upload-group">
					                    <div id="distri_hsrm-detail-queue{{$rkey}}"></div>
					                    <input id="distri_hsrm_detail_file_upload{{$rkey}}" name="file_upload" type="file">
					                </div>
					            </div>
					        </div>
					        <!--编辑状态绑定元素end-->
						</div>
					</li>
					<li class="romForm-col-bot">
						<div class="view-btn room-btn-bar">
							<a href="javascript:;" room-id="{{$room_data.room_id}}" data-page="detail" class="btn btn2 addAllRoomTrig" editUrl="{{'House-Room/roomdetail'|url}}">保存房间</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<!--分散式公寓-房间详情 e-->
		<!--多选删除遮罩模板-->
			<div class="deletemoreauto none">
				<div class="top">
					<div class="top1">
						<span class="fl">正在删除...</span>
						<span class="fr">
							<span class="num_cur">1</span>/<span class="num_total"></span>
						</span>
					</div>
					<div class="top2">
						<div class="top2a">
							<div class="top2at"></div>
						</div>
					</div>
				</div>
				<div class="content">
					<table>
						<tr><th class="zb">房间配置名称</th><th class="yb">删除结果</th></tr>
						<!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
					</table>
				</div>
			</div>
<!--停用房间信息展示-房间详情 e-->
<script type="text/template" id="room-detail-distri-stop">
    	<div class="rsv-wrap jzf-form room-stop-form" id="room_detail_stop_info">
			<div class="jzf-col">
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span><i class="red">*</i>起始日期：</span>
					</div>
					<div class="jzf-col-r fl clearfix">
						<input type="text" datatype="*" readonly="readonly" name="endtime_start" nullmsg="请选择起始日期" class="ipt ipt-165 date-input ipx-txt">
						<span class="check-error-ts check-error-auto">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
					</div>
			    </div>
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span><i class="red">*</i>终止日期：</span>
					</div>
					<div class="jzf-col-r fl clearfix">
						<input type="text" datatype="*" readonly="readonly"  name="endtime_end" nullmsg="请选择终止日期" class="ipt ipt-165 date-input ipx-txt">
						<span class="check-error-ts check-error-auto">
							<i class="ico-arrwo-d"></i>
							<span class="check-error"></span>
						</span>
					</div>
			    </div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-l">
					<span>停用说明：</span>
				</div>
				<div class="jzf-col-r blo-row">
					<textarea class="ipx-txt"  ignore="ignore" name="notice" datatype="*"  nullmsg="请输入备注信息"></textarea>
					<span class="check-error-ts">
						<i class="ico-arrwo-d ico-arrwo-d-remark"></i>
						<span class="check-error check-error-textarea"></span>
					</span>
					<input type="text" style="display:none;" class="ipx-txt" name="stop_id" />
				</div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-r blo-row">
					<div class="resv-act-btns">
						<a href="javascript:;" class="btn btn2 mr10"  id="roomdetail-stop-info-save" stopurl="{{'House-House/editstop'|url}}">保存</a>
						<a href="javascript:;" class="btn btn4 restore-disable-act" data-url="{{'House-Room/recover'|url|cat:'&room_id='|cat:$room_data.room_id}}">恢复</a>
					</div>
				</div>
			</div>
    		</div>
    </script>
<!-- 预约退租信息展示-房间详情 -->
    <script type="text/template" id="cover-room-yytz-hz">
    		<div class="rsv-wrap jzf-form room-chekout-form" id="roomCheckoutForm-hz">
    			<div class="jzf-col">
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span class="room-num"></span>
					</div>
					<div class="jzf-col-r">
						<span class="roomNum"></span>
					</div>
			    </div>
			</div>
			<div class="jzf-col">
				<div class="col-box">
					<div class="jzf-col-l float-l">
						<span><i class="red">*</i>退租日期：</span>
					</div>
					<div class="jzf-col-r fl clearfix">
						<input type="text" datatype="*" readonly="readonly" name="start_time" nullmsg="请选择退租日期" class="ipt ipt-165 date-input ipx-txt">
						<span class="check-error-ts check-error-auto">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
					</div>
			    </div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-l">
					<span><i class="red">*</i>备注说明：</span>
				</div>
				<div class="jzf-col-r blo-row">
					<textarea class="ipx-txt" id="remark-for-tz-room-hz" name="remark" datatype="*"  nullmsg="请输入备注信息"></textarea>
					<span class="check-error-ts">
						<i class="ico-arrwo-d ico-arrwo-d-remark"></i>
						<span class="check-error check-error-textarea"></span>
					</span>
				</div>
			</div>
			<div class="jzf-col">
				<div class="jzf-col-r blo-row">
					<div class="resv-act-btns">
						<a href="javascript:;" class="btn btn2 mr10"  id="room-tz-info-save-hz" tzurl="{{'House-Room/rentalback'|url}}">保存</a>
						<a href="javascript:;" class="btn btn4 restore-hz-yytz-act" rasb-url="{{'house-room/revocationsubscribe'|url|cat:'&room_id='|cat:$room_data.room_id}}">撤销</a>
					</div>
				</div>
			</div>
    		</div>
    </script>
