		<div class="center-dpt-room jzf-form center-dpt" isEditpage="0" hasform="true">
			<div class="center-dpt-top">
				<span class="iblue">{{$flat_name}}</span>
				<span class="dpt-floors">[共<i>20</i>层]</span>
			</div>
			<div class="center-dpt-body">
				<div class="center-dpt-nav clearfix">
				{{foreach from=$house_number_data key=key item=val}}
					<a href="javascript:;" {{if $key eq 1}}class="current"{{/if}}>
					<span><span class="floorNum">{{$key}}</span></span>
					</span>
					<i class="unit">楼</i></a>
				{{/foreach}}
				</div>
				
				<div class="center-dpt-txt">
				{{foreach from=$house_number_data key=key item=val}}
					<div class="clearfix" data-FloorNum = "{{$key}}">
						<div class="dpt-row-r fl">
						{{foreach from=$val key=vkey item=vval}}
							<div class="jzf-col">
									<div class="jzf-col-l col-box">
											<span>房源编号：</span>
											<span class="house_Num">{{$vval}}</span>
									</div>
									<div class="jzf-col-r">
										<div class="jzf-col-2">
											<div class="jzf-col-l">
												<span><i class="red">*</i>套内间数：</span>
											</div>
											<div class="jzf-col-r">
												{{if $is_edit eq 1}}
												<input type="text" value="{{$room_data.$vval}}" class="ipt mr5" name="rooms_Count" placeholder="套内间数" datatype="n1-2,nauto" nullmsg="请输入套内间数" errormsg="套内间数应大于0小于100"/>
												{{else}}
												<input type="text" value="{{$room_number}}" class="ipt mr5" name="rooms_Count" placeholder="套内间数" datatype="n1-2,nauto" nullmsg="请输入套内间数" errormsg="套内间数应大于0小于100"/>
												{{/if}}
												<span class="check-error check-error-ts"></span>
											</div>
										</div>
								   </div>
							</div>
						{{/foreach}}
						</div>
					</div>
				{{/foreach}}
				</div>
				
			<div class="dpt-bot-grp">
				<a href="javascript:;" url="{{'Centralized-Flat/roomsnumber'|url}}" class="btn btn2">保存</a>
				<a href="javascript:;" class="btn btn4 ml10 btn-cancel">取消</a>
			</div>
				
			</div>
		</div>
