<div id="question-jooozo">
	<div class="question-jooozo">
		<div class="ab-jooozo">
			<h1><img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/ab-jooozo_03.jpg" alt="成都九猪"/></h1>
			<div class="intro-jooozo">
				<p>“九猪”隶属于成都久租网络科技有限公司，定位长租公寓服务平台。</p>
				<p>项目成立于2012年，前身为楼底网。“九猪”以租住市场的垂直细分领域人群</p>
				<p>租房管理系作为切入点，利用平台+SaaS系统相结合的方式 解决“职业房东”</p>
				<p>痛点，打造统入口。</p>
				<p>SaaS 2.0系统开放了对接租房平台的接口，九猪一直致力于为职业房东的整个</p>
				<p>公寓服务和出租提供一个完整的生态平台。</p>
				<p class="last">九猪的目标——做全国领先的长租公寓服务平台。</p>
			</div>
			<div class="contact-jooozo">
				<p>技术支持：</p>
				<p>目前系统内测阶段，请联系我们的技术支持中心：</p>
				<p><span class="icon icon1"><img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/ab-jooozo_06.jpg" alt="客服qq"/></span>QQ：250085085</p>
				<p><span class="icon"><img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/ab-jooozo_09.jpg" alt="客服微信"/></span>微信：jooomo（九小妹）</p>
				<p><span class="icon"><img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/ab-jooozo_12.jpg" alt="客服电话"/></span>技术支持电话：400-960-6299</p>
			</div>
		</div>
	</div>
</div>