<!DOCTYPE html>
<html>
    <head>
    		<meta http-equiv="X-UA-Compatible" content="IE=10,IE=9">
        <meta charset="utf-8">
        <meta name="renderer" content="webkit"/>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
        <title>首页</title>
        <link rel="shortcut icon" href="{{$smarty.const.APP_WEB_STATIC_URL}}images/favicon.ico" type="image/x-icon" />
		<script type="text/javascript">
        	window.APP_WEB = window.APP_WEB || {};
        	window.APP_WEB.CONST = window.APP_WEB.CONST || {};
        	window.APP_WEB.CONST.VERSION = window.APP_WEB.CONST.VERSION || '{{$smarty.const.APP_WEB_VERSION}}';
        </script>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/index.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/dialog/artDialog/ui-dialog.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/calendar.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/centralized_Depart_Info.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/common.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/customer_manage_page.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/jquery.pagination.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/spread_house.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-station.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/view.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/uplodify/uploadify.css?v={{$smarty.const.APP_WEB_VERSION}}" />
        <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}js/cropper/cropper.css?v={{$smarty.const.APP_WEB_VERSION}}"/>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/respond.src.js?v={{$smarty.const.APP_WEB_VERSION}}" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/seajs/seajs/2.1.0/sea.js?v={{$smarty.const.APP_WEB_VERSION}}" type="text/javascript" charset="utf-8"></script>
        <script src="{{$smarty.const.APP_WEB_STATIC_URL}}js/config.js?v={{$smarty.const.APP_WEB_VERSION}}" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript">
			seajs.use("modules_JS/index");
        </script>
    </head>
    <body>
        <!--顶部条 s-->
        <div class="head">
        	<div class="notice-jooozo" style="font-size: 18px; font-weight: bold; color: red; width: 604px; margin-left: -302px;">温馨提示：我们的系统已经升级到2.0版本，为了保证您获得更好的体验，我们推荐您使用360浏览器/<a href="http://7xiakm.com1.z0.glb.clouddn.com/ChromeStandaloneSetup43.0.2357.130.1435047900.exe" target="_blank">谷歌浏览器</a></div>
            <div class="head-l">
                <a href="#index" class="logo">
                    <img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/logo-small.png?v={{$smarty.const.APP_WEB_VERSION}}"/>
                </a>
            </div>
                <div class="crt-city" id="js-crt-city">
                    	<h3 class="evt-trig-ele" url="{{'User-User/setcity'|url}}">[<span class="evt-trig-ele">{{$city.name}}</span>]</h3>
                        <div class="all-city-box">
                        	<div class="all-city-list">
                                <p>
                                	<a href="javascript:void(0);" city="118">成都</a>
	                                <a href="javascript:void(0);" city="1">北京</a>
	                                <a href="javascript:void(0);" city="2">上海</a>
	                                <a href="javascript:void(0);" city="96">广州</a>
	                                <a href="javascript:void(0);" city="97">深圳</a>
                                    <a href="javascript:void(0);" city="29">苏州</a>
                                    <a href="javascript:void(0);" city="4">重庆</a>
                                    <a href="javascript:void(0);" city="28">南京</a>
                                    <a href="javascript:void(0);" city="111">南宁</a>
                                </p>
                            </div>
                            <div class="all-city-list">
                                <p>
                                	<a href="javascript:void(0);" city="3">天津</a>
	                                <a href="javascript:void(0);" city="87">武汉</a>
                                    <a href="javascript:void(0);" city="22">大连</a>
                                    <a href="javascript:void(0);" city="19">沈阳</a>
                                    <a href="javascript:void(0);" city="128">昆明</a>
                                    <a href="javascript:void(0);" city="132">西安</a>
                                    <a href="javascript:void(0);" city="79">郑州</a>
                                    <a href="javascript:void(0);" city="65">青岛</a>
                                    <a href="javascript:void(0);" city="30">无锡</a>
                                </p>
                            </div>
                        	<div class="all-city-list">
                                <p style="border:none;">
                                    <a href="javascript:void(0);" city="91">长沙</a>
                                    <a href="javascript:void(0);" city="64">济南</a>
                                    <a href="javascript:void(0);" city="131">三亚</a>
                                    <a href="javascript:void(0);" city="52">合肥</a>
	                                <a href="javascript:void(0);" city="44">杭州</a>
                                    <a href="javascript:void(0);" city="14">太原</a>
	                                <a class="more" href="javascript:void(0);"  data-url="{{'User-User/indmorecity'|url}}">更多</a>
                                </p>
                            </div>
                        </div>
                    </div>
            <div class="head-r">
                <a href="#{{'Message-Message/Message'|url}}" title="消息中心">
                    <i>消息</i>
                    <i class="news-num news-num-i" style="display:none;"></i>
                </a>
                <a href="javascript:;" class="help-jooozo" popup_url="{{'index/versionpopup'|url|cat:'&user_id='|cat:$user.user_id}}" title="帮助中心">
                    <i>帮助</i>
                </a>
                <span class="msg" title="个人中心">
                    <i>设置</i>
                </span>
            </div>

            <!--js鼠标点击显示 s-->
            <div class="msg-c msg-c-1">
                <a href="#" class="user current">{{if $user.username eq ''}}{{$user.name}}{{else}}{{$user.username}}{{/if}}
                {{if $user.is_manager eq 0}}@{{$user.company.username}}{{/if}}
                </a>
                <a href="#{{'user-user/info'|url}}">账号设置</a>
                <a href="#{{'user-user/changepwd'|url}}">修改密码</a>
                <a href="#{{'index/aboutjiuz'|url}}">关于九猪</a>
                <a href="javascript:;" data-url="{{'user-user/logout'|url}}" class="logout trigerLogout">退出</a>
            </div>
            <div class="msg-c msg-c-2">
                <a href="#{{'index/question'|url}}">常见问题</a>
                <a href="#{{'index/versions'|url}}">历史版本</a>
                <a href="#{{'index/versionsexplain'|url}}">版本更新</a>
                <a href="http://wpa.qq.com/msgrd?v=3&uin=250085085&site=qq&menu=yes" target="_blank">在线反馈</a>
            </div>
            <!--js鼠标点击显示 e-->

        </div>
        <!--顶部条 e-->

        <!--左部导航条 s-->
        <div class="nav-box">
            <div class="nav-list fst" desc="说明：第一个才要加一个fst">
                <a href="#index" class="one-nav">
                    <i class="ifont">&#xe61b;</i>
                    <span>首页</span>
                </a>
            </div>
            <div class="nav-list">
                <a href="javascript:;" class="one-nav">
                    <i class="ifont">&#xe714;</i>
                    <span>房源管理</span>
                </a>
                <ul class="two-nav">
                	{{if $user.company.pattern eq 10 or $user.company.pattern eq 11}}
                    <li>
                        <a href="#{{'Centralized-Flat/list'|url}}">集中式公寓</a>
                    </li>
                    {{/if}}
                    <!-- <li>
                        <a href="#{{'Memo/add'|url}}">添加备忘测试</a>
                    </li>
                    <li>
                        <a href="#{{'Memo/delete'|url}}">删除备忘测试</a>
                    </li>

                    <li>
                        <a href="#{{'Memo/scanAndEdit'|url}}">查看/编辑备忘测试</a>
                    </li> -->
					{{if $user.company.pattern eq 01 or $user.company.pattern eq 11}}
                    <li>
                        <a href="#{{'house-house/index'|url}}">分散式公寓</a>
                    </li>
                    {{/if}}
                </ul>
            </div>
            <div class="nav-list">
            	<a href="javascript:;" class="one-nav">
                    <i class="ifont">&#xe61c;</i>
                    <span>客户管理</span>
                </a>
                {{if $user.company.pattern neq 00}}
                <ul class="two-nav">
                	<li>
                        <a href="#{{'tenant-index/index'|url}}">租客管理</a>
                    </li>
                    <li>
                        <a href="#{{'tenant-index/reserve'|url}}">预定管理</a>
                    </li>
                 {{/if}}
                </ul>
            </div>
            <div class="nav-list">
                <a href="javascript:;" class="one-nav">
                    <i class="ifont">&#xe640;</i>
                    <span>财务管理</span>
                </a>
                <ul class="two-nav">
                	{{if $user.company.pattern neq 00}}
                    <li>
                        <a href="#{{'finance-index/index'|url}}">流水统计</a>
                    </li>
                    {{/if}}
                    <li>
                        <a href="#{{'finance-TypeManage/feeTypeManage'|url}}">类型管理</a>
                    </li>
                </ul>
            </div>
            <div class="nav-list">
                <a href="javascript:;" class="one-nav">
                    <i class="ifont">&#xe62a;</i>
                    <span>员工管理</span>
                </a>
                <ul class="two-nav">
                    <li>
                        <a href="#{{'Staffmanage-staff/list'|url}}">员工信息</a>
                    </li>
                    <!-- li>
                        <a href="#{{'Staffmanage-group/list'|url}}">权限组列表</a>
                    </li-->
                </ul>
            </div>
            <div class="nav-list">
                <a href="javascript:;" class="one-nav">
                    <i class="ifont">&#xe63f;</i>
                    <span>业主管理</span>
                </a>
                {{if $user.company.pattern neq 00}}
                <ul class="two-nav">
                    <li>
                        <a href="#{{'landlord-index'|url}}">业主信息</a>
                    </li>
                </ul>
                {{/if}}
            </div>
            <div class="nav-list-plug">
                <a href="#{{'Plugins-index'|url}}" class="one-nav">
                    <i class="ifont2">&#xe601;</i>
                    <span>添加功能插件</span>
                </a>
                <ul class="two-nav">
                    <li>
                    </li>
                </ul>
            </div>

        </div>
        <!--左部导航条 e-->

        <!--内容 s-->
        <div class="main">
            <!--页面内容 s-->
            <div class="main-box">

                <!--标签 s-->
                <div class="tag">
                    <a href="javascript:;" class="ifont icon-index">&#xe60f;</a>
                    <ul>
                        <li class="current">
                            <a class="a_Tags irefresh" href="#index" url="#index">首页</a>
                        </li>
                    </ul>
                    <div class="tag-auto-conter">
                    	<a href="javascript:;" class="tag-auto-conter-prev ifont">&#xf016e;</a><a href="javascript:;" class="tag-auto-conter-next ifont">&#xf016d;</a>
                    </div>
                </div>
                <!--标签 e-->
				<div style="width: 100%; height: 2px; background-color: #eee;"></div>
                <!--舞台 s-->
                <div class="main-show">

                    <div class="jooozo_Page model-index">
                        <!--日历 s-->
                        <div class="calendar">
                            <div class="c-head clearfix">
                                <h1 surl="{{'index/getTotal'|url}}" url="{{'index/currentMonthBacklog'|url}}">日程管理</h1>
                                <div class="mark">
                                    <a href="javascript:;" class="eventTriger todo-col" data-index="3" isCached="0" tab-type="todo">待办提醒：<span>{{$total_backlog}}</span></a>
                                    <a href="javascript:;" class="eventTriger rmd-col" data-index="1" isCached="0"  tab-type="remind" listURL="{{'Memo/list'|url}}">
                                        <i class="ifont">&#xf0006;</i>
                                        备忘录
                                    </a>
                                </div>
                            </div>
                            <script type="text/javascript">seajs.use("modules_JS/mod_calendar.js")</script>
                            <link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/calendar.css">
                            <div id="calendar_Ind_box" class="none" style="background:#F5F5F5;padding:50px;text-align:center;"></div>
                            <div class="calendar_Ind tab-col none" tab-index="2" >
                                <div id="detail" style="position: absolute"></div>
                                <form name="CLD">
                                    <table width="100%" height="100%">
                                        <tr>
                                            <td>
                                                <div class="cld-header">
                                                    <div class="sm clearfix cld-h-m">
                                                        <a href="javascript:;" class="btn-m-prev ifont" id="prevM">&#xf0292;</a>
                                                        <div class="zone-year lf zone-sel ">
                                                            <span id="curr-year-txt" class="ctxt txt"></span>
                                                            <ul class="year-ranges" name="SY">
                                                                <script language=Javascript>for (i = 1900; i < 2050; i++)
                                                                        document.write('<li>' + i)</script>
                                                            </ul>
                                                            <!-- <select name="SY">
                                                                <script language=Javascript>for(i=1900;i<2050;i++) document.write('<option>'+i)</script>
                                                            </select> -->
                                                            <span class="ctxt lf sepr">.</span>
                                                        </div>
                                                        <div class="zone-month lf zone-sel ">
                                                            <span id="curr-mon-txt" class="ctxt txt"></span>
                                                            <ul class="month-ranges" name="SM">
                                                                <script language=Javascript>for (i = 1; i < 13; i++)
                                                                        document.write('<li>' + i)</script>
                                                            </ul>
                                                            <!-- <select name="SM" class="jzone-sel">
                                                                <script language=Javascript>for(i=1;i<13;i++)document.write('<option>'+i)</script>
                                                            </select> -->
                                                        </div>
                                                        <a href="javascript:;" class="btn-m-next ifont" id="nextM">&#xf02af;</a>
                                                    </div>
                                                    <!-- <span class="sm"><font id="GZ"></font></span> -->
                                                    <a href="javascript:;" class="back-current-m none" id="currentM">回到本月</a>
                                                </div>
                                                <div class="cld-body" >
                                                    <table id="show_Calendar" >
                                                        <tr class="col-tr col-gem">
                                                            <td class="ch">
                                                                <table class="calendar_Txt">
                                                                    <tr>
                                                                        <td class="red">日</td>
                                                                        <td>一</td>
                                                                        <td>二</td>
                                                                        <td>三</td>
                                                                        <td>四</td>
                                                                        <td>五</td>
                                                                        <td class="red">六</td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </form>
                            </div>

                            <!--<div class="c-botttom">
                                <div class="cb-cutline">-->
                            <!--<a href="#" class="m-zero eventTriger cld-col" data-index="2" isCached="0"  tab-type="calendar">
                                <i class="zero today"></i>
                                今日
                            </a>-->
                            <!--<a href="#" class="m-zero cld-col fr">
                                <i class="zero today"></i>
                                今日
                            </a>-->
                            <!--<a href="#" class="m-zero eventTriger todo-col" data-index="3" isCached="0" tab-type="todo" >
                                <i class="zero untreated"></i>
                                未办事情
                            </a>-->
                            <!--<a href="#" class="m-zero fr">
                                <i class="zero untreated"></i>
                                未办事情
                            </a>-->
                            <!--</div>
                        </div>-->

                            <!--备忘录 s-->
                            <div class="c-memo tab-col" tab-index="1" style="display: none;">
                                <div class="cm-head">
                                    <div class="cmh-l">
                                        <i class="ifont">&#xf0006;</i>
                                        <span>备忘录</span>
                                    </div>
                                    <div class="cmh-r">
                                        <a href="javascript:;" class="btn-b eventTriger" data-index="2" iscached="0" tab-type="calendar">回到日历</a>
                                        <a href="javascript:;" class="btn-b add-Memorandum" addURL="{{'Memo/add'|url}}" infoURL="{{'Memo/scanAndEdit'|url}}" delURL="{{'Memo/delete'|url}}">添加备忘录</a>
                                    </div>
                                </div>
                                <div class="cm-list" id="rlist">
                                    <ul>
                                    </ul>
                                </div>
                            </div>
                            <!--备忘录 e-->

                            <!--待办事项 s-->
                            <div class="c-needs tab-col" style="display: none;" tab-index="3">
                                <div class="cm-head none" id="todo-all-ops">
                                    <div class="cmh-l">
                                        <span>待办提醒：<i>0</i></span>
                                    </div>
                                    <div class="cmh-r">
                                        <a href="javascript:;" class="btn-b eventTriger" data-index="2" iscached="0" tab-type="calendar">回到日历</a>
                                    </div>
                                </div>
                                <div class="cn-head none" id="todo-day-ops">
                                    <div class="cnh-con">
                                        <a href="#" id="prevDay" class="ifont ifont-left">&#xf0292;</a>
                                        <a href="#" id="todo-mon">12</a>
                                        <a href="#">.</span>
                                            <a href="#" id="todo-day">3</span>
                                                <a href="#" id="nextDay" class="ifont ifont-right">&#xf02af;</a>
                                                </div>
                                                <a href="javascript:;" class="btn-b eventTriger" data-index="2" iscached="0" tab-type="calendar">回到日历</a>
                                                </div>
                                                <div class="cn-list cm-list" id="tlist">
                                                	<div class="tlist-ctr">
                                                		<ul>
                                                			<li class="current"><a href="javascript:;">全部</a></li>
                                                			<li><a href="javascript:;">收租</a></li>
                                                			<li><a href="javascript:;">交租</a></li>
                                                			<li><a href="javascript:;">到期</a></li>
                                                			<li><a href="javascript:;">备忘</a></li>
                                                		</ul>
                                                	</div>
                                                    <ul class="tlist-list"></ul>
                                                </div>
                                                </div>
                                                <!--待办事项 e-->



                                                </div>
                                                <!--日历 e-->

                                                </div>

                                                </div>
                                                <!--舞台 e-->
                                                </div>
                                                <!--页面内容 e-->

                                                </div>
                                                <!--内容 e-->

                                                <!--图表 s-->
                                                <div class="chart">
                                                    <script type="text/javascript">seajs.use("modules_JS/mod_statics.js")</script>
                                                    <div class="total-house" actUrl="{{'index/getHouseStatistics'|url}}">
                                                        <h1>房间统计</h1>
                                                        <div class="selectByM roomTypeOps" hasevent="1">
                                                            <input type="text" class="selectByMT" readonly = 'readonly'  name='flat_id' selectVal = '0' value="{{if $user.company.pattern eq 01}}分散式房间{{elseif $user.company.pattern eq 10}}集中式房间{{else}}全部类型{{/if}}"/>
                                                            <span class='jt_Ctr'><span class='jt_box'></span></span>
                                                            <div class="selectByMO">
                                                                <ul>
                                                                    {{if $user.company.pattern eq 01}}
                                                                    <li selectVal ='-1'>分散式房间</li>
                                                                    {{elseif $user.company.pattern eq 10}}
                                                                    <li selectVal ='0'>集中式类型</li>
                                                                    {{else}}
                                                                    <li selectVal ='0'>全部类型</li>
                                                                    <li selectVal ='-1'>分散式房间</li>
                                                                    {{/if}}
                                                                    {{if $user.company.pattern eq 11 or $user.company.pattern eq 10}}
	                                                                    {{foreach $flatList as $value}}
	                                                                    <li selectVal = '{{$value.flat_id}}'>{{$value.flat_name}}</li>
	                                                                    {{/foreach}}
                                                                    {{/if}}
                                                                </ul>
                                                            </div>
                                                        </div>

                                                        <div class="chart-c">
                                                            <!--图表插件 s-->
                                                            <div class="chart-img" id="container">

                                                            </div>
                                                            <!--图表插件 e-->

                                                            <div class="chart-total" id="room-box">

                                                            </div>
                                                            <!--遮罩模板渲染-->
                                                            <script type="text/html" id="room-statics-info">
                                                                <p>房间总数：<span id="room-count"> {{'<%= totalCount%>'}}</span></p>
                                                                <p>已租间数：<span id="room-rented">{{'<%= bookedRooms%>'}}</span></p>
                                                                <p>未租间数：<span id="room-avaiable">{{'<%= unrentedRooms%>'}}</span></p>
                                                                <p>预定间数：<span id="room-booked">{{'<%= bookRooms%>'}}</span></p>
                                                                <p>平均租金：<span id="average-mpay">{{'<%= averagePayment%>'}}</span></p>
                                                                <p>出租率：<span class="ct-blue rate-rented">{{'<%= rateRented%>'}}</span></p>
                                                                <p>月空置率：<span class="ct-blue rate-month-avaiable">{{'<%= rateMonthAvaiable%>'}}</span></p>
                                                                <p>年空置率：<span class="ct-blue rate-year-avaiable">{{'<%= rateYearAvaiable%>'}}</span></p>
                                                                </script>
                                                            </div>
                                                        </div>
                                                        <div class="total-stream"  actUrl="{{'index/getAccountStatistics'|url}}">
                                                            <h1>流水统计</h1>

                                                            <div class="chart-c">
                                                                <!--图表插件 s-->
                                                                <div class="chart-img" id="harea">

                                                                </div>
                                                                <!--图表插件 e-->

                                                                <div class="chart-total" id="finance-box">
                                                                </div>
                                                                <script type="text/html" id="finance-statics-info">
                                                                    <p>今日收入：<span class="ct-blue" id="tday-income-total">{{'<%= todayIncome%>'}}</span></p>
                                                                    <p>今日支出：<span class="ct-blue" id="tday-pay-total">{{'<%= todayPayment%>'}}</span></p>
                                                                    <p>历史收入：<span id="total-income-sum">{{'<%= totalIncome%>'}}</span></p>
                                                                    <p>历史支出：<span id="total-pay-sum">{{'<%= totalPayment%>'}}</span></p>
                                                                    <p>在住押金：<span class="ct-red" id="detain-total">{{'<%= detainSum%>'}}</span></p>
                                                                    </script>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <!--图表 e-->

                                                        <!--备忘录下拉  s-->
                                                        <div class="slt-bwl-autoss" style="display: none;">
                                                        	<div class="selectByM slt-90 slt-bwl-autos">
																<input type="text" class="selectByMT"
																	readonly='readonly' selectVal='' value="提醒方式" name="slt-bwl-auto" /> <span
																	class='jt_Ctr'><span class='jt_box'></span></span>
																<div class="selectByMO">
																	<ul>
																	{{foreach from=$memo_arr key=k item=v}}
																		<li selectVal='{{$k}}'>{{$v}}</li>
																	{{/foreach}}
																	</ul>
																</div>
															</div>
                                                        </div>
                                                        <!--备忘录下拉  e-->
                                                        </body>
                                                        <!--loading e-->
                                                        <div class="layout-loading-overlay" id="overlay-loading"></div>
                                                        <div class="layout-loading-zone">
                                                            <img class="ico-loading" src="{{$smarty.const.APP_WEB_STATIC_URL}}images/loading.gif" />
                                                        </div>
                                                        {{if $user.company.is_verify eq 0}}
                                                        <!--注册成功弹窗 s-->
														<div class="hide-register-suc" style="display: none;">
															<div class="dialog-reg-suc">
																<div class="drs-img">
																	<img src="{{$smarty.const.APP_WEB_STATIC_URL}}images/50_03.png"/>
																</div>
																<p class="drs-head">尊敬的用户，您好！</p>
																<p>您已经注册成功！为了保证我们系统的良好运转，我们的工作人员将在工作日</p>
																<p>的2小时之内联系您，进行基本的用户审核，请耐心等待。</p>
																<p>审核通过之后即可使用SAAS2.0的全部功能！</p>
															</div>
														</div>
														<!--注册成功弹窗 e-->
                                                        {{/if}}
  <!-- <iframe src="{{'index/print'|url}}" style="display: none;" id="printListWrap"></iframe> -->
  <div class="overlay-mask"></div>
  <div id="siwp-image" class="swipe-image">
    <a href="javascript:;" class="cover-close">
       <span class="ico ifont close">&#xe627;</span>
    </a>
      <div class="swp-inner">
        <a href="javascript:;" class="icon-nav view-prev">
           <span class="icon ifont qiehuanqizuo">&#x3465;</span>
        </a>
        <a href="javascript:;" class="icon-nav view-next">
           <span class="icon ifont qiehuanqiyou">&#x3464;</span>
        </a>
        <div class="slide-box">
          <ul id="image-box" class="clearfix"></ul>
        </div>
        <div class="caption">
            <span id="slides"><i class="current">0</i><em>/</em><i id="total">0</i></span>
            <a href="javascript:;" class="download-file"><span class="ico ifont2 xiazai">&#xe607;</span>下载</a>
        </div>
      </div>
  </div>
                                                        </html>
