<!--版本更新页面 s-->
<div class="problem view">
	<div class="view-head">
		<h1>常见问题</h1>
	</div>
	<div class="problem-title">
		{{foreach $category as $_category}}
		<a href="javascript:;" data-id="{{$_category.category_id}}">{{$_category.name}}</a>
		{{/foreach}}
	</div>
	<div class="category-data" style="display: none;">
		{{foreach $category as $_category}}
			<div data-id="{{$_category.category_id}}">
			{{foreach $_category['news'] as $news}}
				{{$news.content}}
			{{/foreach}}
			</div>
		{{/foreach}}
	</div>		
	<div class="view-con">
		
	</div>
</div>
<!--业主信息 e-->