<div id="question-jooozo">
	<div class="question-jooozo">
		<div class="head">Saas2.0版本新功能</div>
		<div class="content-queastion">
			<h3>Saas2.0新版系统和旧版系统就什么不同？功能点上有什么区别？</h3>
			<table>
				<tr>
					<th width="150">模板</th>
					<th width="297">功能点</th>
					<th width="173">旧版</th>
					<th>新版</th>
				</tr>
				    <tr>
				        <td rowspan="3">代办业务提醒</td>
				        <td>1.预定到期提醒</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.租房平台上线后上线预约看房提醒</td>
				       <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.备忘录事件提醒调整</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="5">数据统计</td>
				        <td>1.预约退租房间统计</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.停用房间统计</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.月空置率、年空置率</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>4.平均租金统计</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>5.在住押金统计</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="2">分散式房源管理</td>
				        <td>1.房态管理</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.家具配置自定义</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="4">集中式房源管理</td>
				        <td>1.公寓数据管理</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.房间数据管理</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.费用数据管理</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>4.模板数据管理</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="2">业主管理</td>
				        <td>1.免租期设置</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.业主合同打印功能</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="4">租客合同管理</td>
				        <td>1.租客黑名单提示</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.租客信用提醒</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.租客信用评价</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>4.预定信息打印功能</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="3">预订人管理</td>
				        <td>1.黑名单提示</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.支付方式、来源渠道设置</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.预定转出租功能</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="3">财务管理</td>
				        <td>1.欠费设置、欠费收取功能</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.非房间产生流水设置</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.财务数据打印功能</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td rowspan="3">员工管理</td>
				        <td>1.员工数据打印功能调整</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>2.权限功能细化</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr>
				        <td>3.房源分配功能优化</td>
				        <td class="ifont red">&#xe627;</td>
				        <td class="ifont1 green">&#xe60c;</td>
				    </tr>
				    <tr class="no-border">
				        <td rowspan="2" class="has-border">其他改变</td>
				        <td colspan="3">1.房源批量上传</td>
				    </tr>
				    <tr>
				        <td colspan="3">2.房源、租客合同、预定数据、财务流水数据、员工数据、业主合同批量导出</td>
				    </tr>
			</table>
		</div>
	</div>
</div>
