<div id="question-jooozo">
	<div class="question-jooozo">
		<div class="head">版本更新</div>
		<ul class="col-inner timeline-list">
            {{foreach from=$pub_log_data item=pub_info}}
			  <li class="timeline-box">
					 <span class="tm-date">{{$pub_info.pub_date|date_format:'%Y-%m-%d'}}</span>
					 <div class="timezone">
						 <span class="tm-dot"><i></i></span>
					 	  <h2>{{$pub_info.title}}</h2>
							<div class="feature-box">
								 {{$pub_info.content}}
							</div>
					 </div>
				</li>
			{{/foreach}}
		</ul>
	</div>
</div>
