<link rel="stylesheet" type="text/css" href="{{$smarty.const.APP_WEB_STATIC_URL}}css/plug-station.css?v={{$smarty.const.APP_WEB_VERSION}}" />
		<!--首页 s-->
		<div class="index station">
			<div class="head">
				<h1>个性化功能库</h1>
				<p>可针对您的需要提供更多的个性功能插件。</p>

			</div>
			<div class="plug-type">
				<ul>
					<li class="type-station {{if !empty($data.id)}}current{{/if}}">
						<a {{if !empty($data.id)}}href="#{{'Plugins-SubSite/editSetBasicInfo'|url}}"{{else}}href="#{{'Plugins-SubSite/applyopen'|url}}" {{/if}}>
							<div class="type-logo"></div>
							<div class="type-main">
								<b>九猪小站<i></i></b>
								<p>简单，一分钟上手，五分钟熟练</p>
								<p>有效，自动生成适合微信传播的页面</p>
								<p>实用，打印二维码，扫描即入房源信息界面</p>
							</div>
							<div class="type-switch">
								<span>{{if !empty($data.id)}}<i class="on"></i>已开通{{else}}<i class="off"></i>未开通{{/if}}</span>
							</div>
						</a>
					</li>
					<!--<li class="type-message">
						<a href="#{{'Plugins-Sms/index'|url}}">
							<div class="type-logo"></div>
							<div class="type-main">
								<b>智能短信服务<i></i></b>
								<p>开通该功能后，可设定短信模版，手动</p>
								<p>发送短信、智能发送短信、群发短信。</p>
							</div>
							<div class="type-switch">
								<span><i class="off"></i><i class="on" style="display: none;"></i>未开通</span>
							</div>
						</a>
					</li>-->
				</ul>
			</div>
		</div>
		<!--首页 e-->
