<!--账号设置-修改登录密码 s-->
<div class="account_chance_pwd view" hasform="true">
	<div class="view-head">
		<h1>修改登录密码</h1>
	</div>
	<div class="view-con">
		<ul>
			<li><b>旧 密 码：</b> <input name="oldpwd" id="account_chance_pwd_oldpsw" type="password" class="ipt ipt-300" datatype="*6-18" nullmsg = "请输入旧密码" errormsg = "密码由6到18位字符组成"/>
				<span class="check-error check-error-ts"></span>
			</li>
			<li><b>新 密 码：</b> <input name="newpwd" id="account_chance_pwd_newpwd" type="password" class="ipt ipt-300" datatype="*6-18,recheck" nullmsg = "请输入新密码" errormsg = "密码由6到18位字符组成"/>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="pt5"><b>确认密码：</b> <input name="newpwd2" id="account_chance_pwd_newpwd2" type="password" class="ipt ipt-300" datatype="*6-18" nullmsg = "请输入确认密码" errormsg = "两次密码填写不一样" recheck="newpwd"/>
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" class="btn btn2">确定</a>
	</div>
</div>
<!--账号设置-修改登录密码 e-->
