<!--账号设置-修改冲账密码 s-->
<div class="account_chance_pwd view" hasform="true">
	<div class="view-head">
		<h1>修改冲账密码</h1>
	</div>
	<div class="view-con">
		<ul>
			<li><b>登陆密码：</b> <input type="password" name="safe_oldpwd" id="account_chance_pwd_safe_oldpwd"  class="ipt ipt-300" datatype="*6-18" nullmsg = "请输入旧密码" errormsg = "密码由6到18位字符组成"/>
				<span class="check-error check-error-ts"></span>
			</li>
			<li><b>新 密 码：</b> <input type="password" name="safe_newpwd" id="account_chance_pwd_safe_newpwd"  class="ipt ipt-300" datatype="*6-18,recheck" nullmsg = "请输入新密码" errormsg = "密码由6到18位字符组成"/>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="pt5"><b>确认密码：</b> <input name="safe_newpwd2" id="account_chance_pwd_safe_newpwd2" type="password" datatype="*6-18" nullmsg = "请输入确认密码" errormsg = "两次填写的密码不一致" recheck="safe_newpwd" class="ipt ipt-300" />
				<span class="check-error check-error-ts"></span>
			</li>
		</ul>
	</div>

	<div class="view-btn">
		<a href="javascript:;" class="btn btn2">确定</a>
	</div>
</div>
<!--账号设置-修改冲账密码 e-->
