<!--账号设置 s-->
<div class="account_set view" hasform="true">
	<div class="view-head">
		<h1>账号设置</h1>
	</div>
	<div class="view-con">
		<ul>
			<li>
				<div class="city_ChooseAn" style="width: auto;">
					<b><i class="bit"></i>城 市：</b> <span class="city_Name" data-cityid="{{$city.city_id}}">{{$city.name}}</span>
					<a href="javascript:;" class="ml10">[选择城市<i  class="ifont1">&#xe6b7;</i>]
					</a>
				</div>
				<div class="city_Choose">
					<dl>
						{{foreach from=$city_list key=key item=val}}
						<dd data-cityid="{{$val.city_id}}">{{$val.name}}</dd>
						{{/foreach}}
						<dd><a href="#/index.php?c=user-user&a=morecity">更多</a></dd>
					</dl>
				</div>
			</li>
			<li><b><i class="bit"></i>登录账号：</b> <span>{{$user.username}}{{if $user.is_manager eq 0}}@{{$user.company.username}}{{/if}}</span></li>
			<li><b><i class="bit"></i>登录密码：</b> <input type="text" disabled value="**********"
				class="ipt ipt-spe" /> <a href="#{{'user-user/changepwd'|url}}">[ 修改密码 ]</a></li>
			<li><b><i class="bit"></i>冲账密码：</b> <input type="text" disabled value="**********"
				class="ipt ipt-spe" /> {{if $user.is_manager}}<a href="#{{'user-user/changsafepwd'|url}}">[ 修改密码 ]</a>{{/if}}<i class="notice">(初始密码为主账号的登录密码)</i></li>
			<li><b><i class="bit"></i>公司品牌：</b> <input name="company_name" type="text" placeholder="（例如:九猪公寓等）" {{if !$user.is_manager}}disabled="disabled"{{/if}} value="{{$company.company_name}}" xplaceholder="{{$company.company_name}}"
				class="ipt ipt-300" datatype="*1-40" nullmsg = "请填写公司名称" errormsg="请填写1到40位字符"/><span class="check-error check-error-ts"></span></li>
			<li><b><i class="bit"></i>房源形态：</b>
				<div class="check-box">
					<label {{if $company.pattern eq "10" or $company.pattern eq "11"}} class="checked" {{/if}}>
					<i class="{{if $user.is_manager}}choose{{/if}} ifont1" {{if $company.pattern eq "10" or $company.pattern eq "11"}} style="display: inline;" {{/if}}>&#xe60c;</i>
					</label>

					<input name="jizhong" {{if $company.pattern eq "10" or $company.pattern eq "11"}} checked="checked" {{/if}} type="checkbox" value="" />
					<span>集中式公寓</span>
				</div>
				<div class="check-box">
					<label {{if $company.pattern eq "01" or $company.pattern eq "11"}} class="checked" {{/if}}>
					<i class="{{if $user.is_manager}}choose{{/if}} ifont1" {{if $company.pattern eq "01" or $company.pattern eq "11"}} style="display: inline;" {{/if}}>&#xe60c;</i>
					</label>
					<input name="fensan" {{if $company.pattern eq "01" or $company.pattern eq "11"}} checked="checked" {{/if}} type="checkbox" value="" /> <span>分散式公寓</span>
				</div></li>
			<li><b><i class="bit">*</i>联 系 人：</b> <input type="text" name="linkman" value="{{$user.name}}" xplaceholder="{{$user.name}}"
				class="ipt ipt-300" datatype="s1-12" nullmsg = "请填写联系人"/><span class="check-error check-error-ts"></span></li>
			<li class="pt5">
				<b><i class="bit">*</i>联系电话：</b> 
				<input name="telephone" type="text" value="{{$user.contact}}" xplaceholder="{{$user.contact}}" class="ipt ipt-300" datatype="/^1\d{10}$/" nullmsg = "请填写联系电话" errormsg = "联系电话格式不正确"/>
				<i class="notice">（此联系电话会默认成为租客平台留下的预约号码）</i>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="pt5">
				<b><i class="bit"></i>发布房源：</b>
				<div class="check-box client">
					<label {{if $user.company.allow_client eq 1}}class="checked"{{/if}}>
						<i class="choose ifont1" {{if $user.company.allow_client eq 1}}style="display: block"{{else}}style="display: none;"{{/if}}>&#xe60c;</i>
					</label>
					<input name="allow_client" {{if $user.company.allow_client eq 1}}checked="checked"{{/if}} type="checkbox" value="1" />
					<span title="（勾选后您的房源信息会自动同步到九猪租房后台，工作人员审核后展示到租房平台http://zufang.jooozo.com）">九猪租房</span>
				</div>
				
				<!--<div class="radio-box {{if $user.company.allow_client eq 0}}radio-sync{{/if}}">
					<label class="radio {{if $user.company.allow_client eq 1}}checked{{/if}}">
					<i class="ifont r-default" {{if $user.company.allow_client eq 1}}style="display: none;"{{else}}display: inline;{{/if}}>&#xe612;</i>
					<i class="ifont r-select" {{if $user.company.allow_client eq 1}}style="display: inline;"{{else}}style="display: none;"{{/if}}>&#xe617;</i>
					</label>
					<input name="allow_client" type="radio" value="1" xplaceholder="1" {{if $user.company.allow_client eq 1}}checked="checked"{{/if}}/>
					<span>九猪租房</span>
				</div> -->
				<!--<input name="telephone" type="radio" value="{{$user.contact}}" xplaceholder="{{$user.contact}}" class="ipt ipt-300"/>-->
			</li>
		</ul>
	</div>
	<div class="view-btn">
		<a href="javascript:;" class="btn btn2" url="{{'user-user/info'|url}}">确定</a>
	</div>
</div>
<!--账号设置 e-->
