{{if $view == 'default'}}
<div class="crm-manage crm-list jzf-form">
    <!--筛选-->
    <!-- 这是合同列表 -->
    <div class="crm-top">
        <div class="dpt-toolbar-inactive ">
            <div class="jzf-col clearfix dpt-room-type">
                <div class="jzf-col-l fl sf-mt">
                    <span>房源形态：</span>
                </div>
                <div class="jzf-col-r fl">
                    <a href="javascript:;" data-type="2" class="dpt-sort {{if $default.house_type == 2 || !$default.house_type}}current{{/if}}">集中式公寓</a>
                    <a href="javascript:;" data-type="1" class="dpt-sort {{if $default.house_type == 1}}current{{/if}}">分散式租房</a>
                </div>
            </div>

            <div class="jzf-col dpt-row-dtm">
                <div class="jzf-col-l">
                    <span>到期时间：</span>
                </div>
                <div class="jzf-col-r">
                    <input type="text" readonly="readonly" id="exp_bdate" value="" class="ipt wdate wbdate"   />
                    <span class="jzf-unit">--</span>
                    <input type="text" readonly="readonly" id="exp_edate" class="ipt wdate wedate" />
                    <a href="javascript:;" class="date_ops" data-type="1">今日到期</a>
                    <a href="javascript:;" class="date_ops" data-type="2">一周内到期</a>
                    <a href="javascript:;" class="date_ops" data-type="3">一月内到期</a>
                </div>
            </div>
            <div class="jzf-col dpt-row-payTime">
                <div class="jzf-col-l">
                    <span>下次交租：</span>
                </div>
                <div class="jzf-col-r">
                    <input type="text" readonly="readonly" id="debt_bdate" class="ipt wdate wbdate" />
                    <span class="jzf-unit">--</span>
                    <input type="text" readonly="readonly" id="debt_edate" class="ipt wdate wedate"  />
                    <a href="javascript:;" class="date_ops" data-type="1">今日交租</a>
                    <a href="javascript:;" class="date_ops" data-type="4">三日内交租</a>
                    <a href="javascript:;"  class="date_ops" data-type="2">一周内交租</a>
                </div>
            </div>
            <div class="jzf-col clearfix dpt-rent-status">
                <div class="jzf-col-l fl sf-mt">
                    <span>合同状态：</span>
                </div>
                <div class="jzf-col-r fl">
                    <a href="javascript:;" data-type=""  class="dpt-sort current">全部</a>
                    <a href="javascript:;" data-type="0"  class="dpt-sort">在住中</a>
                    <a href="javascript:;" data-type="1"  class="dpt-sort">已退租</a>
                </div>
            </div>

            <div class="jzf-col">
                <div class="jzf-col-l fl sf-mt">
                    <span>关键词：</span>
                </div>
                <div class="jzf-col-r clearfix">
                    <div class="search fl ml20">
                        <input type="text" id="keywords" class="ipt" placeholder="小区名称/租客姓名/租客电话">
                        <a href="javascript:;" actionURl="{{'tenant-index/index/view_type/data'|url}}" delURL="{{'tenant-index/dele'|url}}" id="goSearchTrig" class="btn btn3 ifont">&#xe645;</a>
                    </div>
                </div>
            </div>
            <div class="dpt-toolbar">
                <a href="#{{'tenant-index/adds'|url}}" class="dpt-add-reserve"><i class="ifont">&#xe61c;</i>添加合同</a>
                <a href="javascript:;" class="dpt-toolbar-delete"><i class="ifont">&#xe675;</i>删除</a>
                <!-- <a href="javascript:;" class="send_sms">短信模板发送</a> -->
                <!-- <a href="javascript:;" class="printCustlist"><i class="ifont1">&#xe65e;</i>打印</a> -->
            </div>
        </div>
        <div class="dpt-toolbar dpt-toolbar-active">
            <span class="mr20">
                <label class="checkBox"><span class="choose ifont1">&#xe60c;</span></label> <a href="javascript:;">全选</a>
            </span>
            <a href="javascript:;" class="dpt-toolbar-active-delete"><i class="ifont">&#xe675;</i>删除</a>
            <a href="javascript:;" class="edit-cancle-trig"><i class="ifont">&#xe627;</i>取消</a>
        </div>
    </div>
    <!--列表-->
    <table class="lst_tb" id="tb-agmt-lst">
        <tr>
            <th class="w10">租客姓名</th>
            <th class="w12">租客电话</th>
            <th >房间名称</th>
            <th>合同周期</th>
            <th>合同状态</th>
            <th class="w10">下次付款时间</th>
            <th class="w10">下次付款金额</th>
            <th>操作</th>
        </tr>
        {{/if}}
        {{if $view == 'data'}}
        {{foreach from=$list item=l}}
        <tr>
            <td class="w10">
                <span class="ck-status">
                    <label class="checkBox"><span class="ifont1">&#xe60c;</span></label>
                    <input type="checkbox" value="{{$l.contract_id}}" />
                </span>
                <a href="#{{'tenant-evaluation/index'|url|cat:'&'|cat:'tid='|cat:$l.tenant_id}}" class="dpt-room-user">{{$l.name}}</a></td>
            <td class="w12">{{$l.phone}}</td>
            <td>
                <span>{{if !empty($l.house_name)}}{{$l.house_name}}{{/if}}{{if !empty($l.room_type)}}{{$l.room_type}}{{/if}}</span>
            </td>
            <td>{{$l.signing_time|date_format:'%Y/%m/%d'}}-{{$l.dead_line|date_format:'%Y/%m/%d'}}</td>
            <td>{{if $l.is_stop eq 1}}已退租{{elseif $l.is_stop eq 0}}在住中{{/if}}</td>
            <td class="w10">
            	{{if $l.is_stop eq 1}}已退租
            	{{elseif $l.is_haveson eq 1}}已续租{{elseif $l.next_pay_time gte $l.end_line}}租金已收完{{elseif ($l.next_pay_time + $l.advance_time * 86400) >= $l.end_line}}租金已收完{{else}}{{$l.next_pay_time|date_format:'%Y/%m/%d'}}{{/if}}
            </td>
            <td>{{if $l.is_stop eq 1}}已退租
            	{{elseif $l.is_haveson eq 1}}已续租{{elseif $l.next_pay_time gte $l.end_line}}租金已收完{{elseif ($l.next_pay_time + $l.advance_time * 86400) >= $l.end_line}}租金已收完{{else}}{{$l.next_pay_money}}{{/if}}</td>
            <td>
                <div class="edit-col">
                    <a href="#{{'tenant-index/edit'|url|cat:'&'|cat:'contract_id='|cat:$l.contract_id}}" data-id="{{$l.contract_id}}">查看合同</a>
                    <em>|</em>
                    {{if $l.is_evaluate eq 0 && ($l.is_stop eq 1 or $l.dead_line lt time())}}
                    <a href="javascript:;"  allTenantActionURL="{{'tenant-index/getalltenant'|url|cat:'&contract_id='|cat:$l.contract_id|cat:'&rental_id='|cat:$l.rental_id}}" data-id="{{$l.contract_id}}" class="spr-cmt-trig">评价</a>
                    <em>|</em>
                    {{else}}
                    {{/if}}

                    {{if $l.is_evaluate eq 1}}
                    <a href="javascript:;" data-url="{{'tenant-index/getoncomment'|url|cat:'&contract_id='|cat:$l.contract_id|cat:'&rental_id='|cat:$l.rental_id}}" class="spr-cmt-trig-look">查看评价</a>
                    <em>|</em>
                    {{/if}}
                    <a href="javascript:;" class="spr-del-trig" data-id="{{$l.contract_id}}">删除</a>
                </div>
            </td>
        </tr>
        {{/foreach}}
        {{/if}}
        {{if $view == 'default'}}
        <!-- 循环这一块 -->
    </table>
    <div class="jzf-pagination clearfix" style="display: none;">
        <div class="pagination" id="pagination"></div>
        <div class="jump-to-page clearfix">
            <span>跳转至</span>
            <div class="jump-edit-box">
                <input type="text" placeholder="页码">
                <a href="javascript:;" class="p-btn btn btn4 get-cstm-trigger">GO</a>
                <i class="page-unit">页</i>
            </div>
        </div>
    </div>
</div>

<!--评价遮罩模板-->
<div id="cmt-ove-temp-hideTemp" class="none">
    <div class="crm-cmt-wrap ratyForm">
        <div class="col-custm">
            <p class="custm-title">租客信息</p>
            <div class="custm-info-box" id="dpt-user-temp"></div>
        </div>
        <div class="col-cmt mt10">
            <p class="custm-title">评价租客</p>
            <div class="jzf-form">
                <div class="jzf-col">
                    <div class="jzf-col-l fl">
                        <span class="ml15">评价分数：</span>
                    </div>
                    <div class="jzf-col-r">
                        <div class="jraty-zone fl">
                            <div class="raty"></div>
                            <div class="jraty-msg"></div>
                        </div>
                    </div>
                </div>
                <div class="jzf-col ">
                    <div class="jzf-col-l fl">
                        <span><i class="red isRequired">*</i>备注说明：</span>
                    </div>
                    <div class="jzf-col-r fl">
                        <textarea name="remark" datatype="*" nullmsg="请输入备注" class="itxr" id="remark"></textarea>
                        <span class="check-error-ts">
                            <i class="ico-arrwo-d ico-arrwo-d-remark"></i>
                            <span class="check-error check-error-textarea">备注说明不能为空</span>
                        </span>
                    </div>
                </div>
                <div class="jzf-col">
                    <div class="rty-act-btns">
                        <a href="javascript:;" class="btn btn2" url="{{'tenant-index/comment'|url}}" id="save-raty-info">保存</a>
                        <a href="javascript:;" class="btn btn4 ml10 close-raty-mask">取消</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--遮罩模板渲染-->
<script type="text/html" id="dpt-user-info">
    <table class="jz_tb">
        <tr>
            <td><span class="jltd">租客姓名：</span></td>
            <td>
                <div class="jbox">{{'<%= username%>'}}</div>
            </td>
            <td><span class="jltd">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：</span></td>
            <td>
                <div class="jbox">{{'<%= sex%>'}}</div>
            </td>
        </tr>
        <tr>
            <td><span class="jltd">证件号码：</span></td>
            <td>
                <div class="jbox">{{'<%= idCard%>'}}</div>
            </td>
            <td><span class="jltd">联系电话：</span></td>
            <td>
                <div class="jbox">{{'<%= phone%>'}}</div>
                <input type="hidden" id="dpt-user-id"  value="{{'<%= id%>'}}"/>
            </td>
        </tr>
    </table>
</script>

<!--遮罩评价记录模板-->
<div id="custm-hideTemp" class="none">
    <div class="crm-custm-wrap" style="height:auto;max-height:500px;overflow:auto;">
        <div class="col-custm">
            <ul class="lin-custm-basic clearfix mb10">
                <li>
                    <span>租客姓名：</span>
                    <span class="gray name-tenant-auto"></span>
                </li>
                <li>
                    <span>联系电话：</span>
                    <span class="gray phone-tenant-auto"></span>
                </li>
                <li>
                    <span>证件号码：</span>
                    <span class="gray idcard-tenant-auto"></span>
                </li>
            </ul>
            <ul class="lin-custm-score clearfix">
                <li>
                    <span>评价分数：</span>
                    <span class="gray"><i class="score-tenant-auto"></i></span>
                </li>
                <li style="margin-top: 15px; position: relative; margin-right: 5px; clear: both;">
                    <span class="fl" style="position: absolute;left: 0; top: 0;">备注说明：</span>
                    <p class="remark-tenant-auto fl" style="line-height: 20px; padding-left: 70px;"></p>
                </li>
            </ul>
        </div>
    </div>
</div>

<!--多选删除遮罩模板-->
<div class="deletemoreauto none">
    <div class="top">
        <div class="top1">
            <span class="fl">正在删除...</span>
            <span class="fr">
                <span class="num_cur">1</span>/<span class="num_total"></span>
            </span>
        </div>
        <div class="top2">
            <div class="top2a">
                <div class="top2at"></div>
            </div>
        </div>
    </div>
    <div class="content">
        <table>
            <tr><th class="zb">租客名称</th><th class="yb">删除结果</th></tr>
            <!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
        </table>
    </div>
</div>
<div class="tenant_List none">
    <div class="empty">
        <div class="empty-main">
            <img src="/web/images/03.png" />
            <p>当前页面没有任何数据，请<a href="#/index.php?c=tenant-index&a=adds">点击这里添加</a>！</p>
        </div>
    </div>
</div>
{{/if}}
