<div class="crm-manage crm-agrmt jzf-form" hasform="true">
    <!-- 添加合同  合同详情  编辑合同 都是这个 -->
    <!-- 预定转出租需要的参数 -->
    {{if isset($smarty.get.house_type)}}
    <input type="hidden" name="house_id" value="{{$tmp_data.house_id}}" />
    <input type="hidden" name="room_id" value="{{$tmp_data.record_id}}" />
    <input type="hidden" name="house_type" value="{{$tmp_data.house_type}}" />
    <input type="hidden" name="reserve_id" value="{{$tmp_data.reserve_id}}" />
    {{else}}
    <input type="hidden" name="house_id" value="{{$onedata.house_id}}" />
    <input type="hidden" name="room_id" value="{{$onedata.room_id}}" />
    <input type="hidden" name="house_type" value="{{$onedata.house_type}}" />
    <input type="hidden" name="reserve_id" value="{{$onedata.reserve_id}}" />
    {{/if}}
    <div class="crm-item-top">
        <span>合同信息</span>
        {{if $smarty.get.a eq 'edit'}}
            {{if $tcdata.is_stop eq 0}}
                <span href="javascript:;" class="ops-agrmt" style="background: #0099e6; color: white;">在住中</span>
                <a href="javascript:;" class="ops-agrmt agmt-end" data-url="{{'tenant-index/stop'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}" data-jump-url="{{'finance-serial/addexpense'|url|cat:'&'|cat:'tc_stop_contract_id='|cat:$tcdata.contract_id|cat:'&'|cat:'tc_source='|cat:tc_stop_contract}}" data-contract="合同id">终止</a>
            {{else}}
                <span href="javascript:;" class="ops-agrmt" style="background: #0099e6; color: white;">已退租</span>
            {{/if}}
       		{{if $tcdata.next_pay_time gte $tcdata.dead_line and $tcdata.is_haveson eq 0}}
        	    <a href="#{{'tenant-index/relet'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}" class="ops-agrmt forword-rent" >续租</a>
        	{{elseif ($tcdata.next_pay_time + $tcdata.advance_time * 86400) gte $tcdata.dead_line and $tcdata.is_haveson eq 0}}
        	    <a href="#{{'tenant-index/relet'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}" class="ops-agrmt forword-rent" >续租</a>
        	{{/if}}
        {{if ($tcdata.next_pay_time + $tcdata.advance_time * 86400) lt $tcdata.dead_line && $tcdata.is_stop != 1}}
            <a href="javascript:;" data-url="{{'Tenant-index/pay'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}" class="ops-agrmt forword-rent get-fee-trigger" >收费</a>
            <input type="text" style="display:none;" id="continue_contract_prt_id" value="{{$tcdata.contract_id}}" /><!-- 续租合同父元素id绑定,需要判断此栏目的显示与否 -->
        {{/if}}
        {{/if}}
        {{if $smarty.get.a eq 'relet'}}
        <!-- 续租时需要的的house_id ,room_id ,house_type -->
        <input type="text" class="rel-parm-hid" style="display:none;"  name="house_id" value="{{$tcdata.r_house_id}}" />
        <input type="text"  class="rel-parm-rid" style="display:none;"  name="room_id" value="{{$tcdata.r_room_id}}" />
        <input type="text"  class="rel-parm-htyp" style="display:none;"  name="house_type" value="{{$tcdata.r_house_type}}" />
        {{/if}}
    </div>
    <div class="agrmtForm" {{if isset($smarty.get.house_type)}}actionUrl="{{'tenant-index/adds'|url|cat:'&house_id='|cat:$tmp_data.house_id|cat:'&room_id='|cat:$tmp_data.record_id|cat:'&house_type='|cat:$tmp_data.house_type}}"{{else}}actionUrl="{{'tenant-index/adds'|url}}"{{/if}}>
         <div class="crm-item-body dataForm">
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span><i class="red">*</i>房源名称：</span>
                    </div>
                    <div class="jzf-col-r fl clearfix">
                        {{if $smarty.get.a eq 'reservetolet'}}
                        <input  type="text" id="houses" value="{{$data.house_name}}" name="housename" datatype="*,housename" nullmsg="请输入正确的房源名称" value="" record_id="" house_type="" area_id=""  rental_way=""  actionUrl="{{'tenant-index/getInfo'|url}}"  class="ipt ipt-250 valid-name" />
                        {{elseif isset($smarty.get.house_type)}}
                        <input disabled type="text" id="houses" value="{{$tmp_data.house_name}}" name="housename" datatype="*,housename" nullmsg="请输入正确的房源名称" value="" record_id="" house_type="" area_id=""   rental_way="" actionUrl="{{'tenant-index/getInfo'|url}}"  class="ipt ipt-250 valid-name dista" />
                        {{elseif $smarty.get.a eq 'edit'}}
                        <input disabled  type="text" id="houses" value="{{$tcdata.house_name}}
                               " record_id="" house_type="" area_id=""  actionUrl="{{'tenant-index/getInfo'|url}}"  class="ipt ipt-250 dista" />
                        {{elseif $smarty.get.a eq 'adds'}}
                        <input  type="text" id="houses" name="housename" datatype="*,housename" nullmsg="请输入正确的房源名称" value="" record_id="" house_type="" area_id=""  rental_way=""  actionUrl="{{'tenant-index/getInfo'|url|cat:'&status=1'}}"  class="ipt ipt-250 valid-name" />
                        {{else}}
                        <input disabled value="{{$tcdata.house_name}}" type="text" id="houses"  record_id="" house_type="" area_id=""  rental_way=""  actionUrl="{{'tenant-index/getInfo'|url}}"  class="ipt ipt-250 dista" />
                        {{/if}}
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>合同编号：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq 'edit'}}
                        <input disabled type="text" name="custom_number" nullmsg="请输入合同编号" {{if !empty($tcdata)}}value="{{$tcdata.custom_number}}"{{/if}} class="ipt ipt-250 dista" />
                               {{else}}
                               <input type="text" datatype="*" name="custom_number" nullmsg="请输入合同编号"  class="ipt ipt-250" />
                        {{/if}}
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>合同起始：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq 'edit' }}
                        <input disabled type="text"  class="ipt ipt-250 dista wdate" {{if $smarty.get.a eq 'relet' && !empty($tcdata)}}value="{{$tcdata.dead_line|date_format:'%Y-%m-%d'}}" {{/if}}{{if $smarty.get.a eq 'edit' && !empty($tcdata)}}value="{{$tcdata.signing_time|date_format:'%Y-%m-%d'}}"{{/if}} name="signing_time" readonly="readonly"  />
                               {{elseif $smarty.get.a eq 'relet'}}
                               <input type="text" datatype="*,checkstart" max_date="{{$tcdata.max_time}}"  nullmsg="请选择合同开始日期" errormsg="开始日期不能大于终止日期" class="ipt ipt-250 maxWdate"    value="{{$tcdata.end_line|date_format:'%Y-%m-%d'}}" name="signing_time" readonly="readonly"  />
                               {{else}}
                               <input type="text" datatype="*,checkstart" nullmsg="请选择合同开始日期" errormsg="开始日期不能大于终止日期" class="ipt ipt-250 wdate" {{if $smarty.get.a eq 'relet' && !empty($tcdata)}}value="{{$tcdata.dead_line|date_format:'%Y-%m-%d'}}" {{/if}}{{if $smarty.get.a eq 'edit' && !empty($tcdata)}}value="{{$tcdata.signing_time|date_format:'%Y-%m-%d'}}"{{/if}} name="signing_time" readonly="readonly"  />
                               {{/if}}
                               <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>合同终止：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq  'edit'}}
                        <input disabled type="text"  {{if $smarty.get.a eq 'relet'}}placeholder="请选择合同结束时间"{{/if}} {{if $smarty.get.a eq 'edit' && !empty($tcdata)}}value="{{$tcdata.dead_line|date_format:'%Y-%m-%d'}}"{{/if}} class="ipt ipt-250 dista wdate" name="dead_line" readonly="readonly" />
                               {{else}}
                               <input type="text" datatype="*,checkend" nullmsg="请选择合同结束日期" errormsg="终止日期不能小于合同开始日期" {{if $smarty.get.a eq 'relet'}}placeholder="请选择合同结束时间"{{/if}} {{if $smarty.get.a eq 'edit' && !empty($tcdata)}}value="{{$tcdata.dead_line|date_format:'%Y-%m-%d'}}"{{/if}} class="ipt ipt-250 wdate" name="dead_line" readonly="readonly" />
                               {{/if}}
                               <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>房屋租金：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq 'reservetolet'}}
                        <input type="text" datatype="floatGroup" nullmsg="请输入房屋租金" value="{{$data.money}}" errormsg="请输入正确的租金金额" class="ipt ipt-188 mr5" name="rent" />
                        {{elseif isset($smarty.get.house_type)}}
                        <input type="text" datatype="floatGroup" nullmsg="请输入房屋租金" value="{{$tmp_data.money}}" errormsg="请输入正确的租金金额" class="ipt ipt-188 mr5" name="rent" />
                        {{elseif $smarty.get.a eq 'edit'}}
                        <input disabled type="text" nullmsg="请输入房屋租金" {{if !empty($tcdata)}}value="{{$tcdata.rent}}"{{/if}} errormsg="请输入正确的租金金额" class="ipt ipt-188 dista mr5" name="rent" />
                               {{elseif $smarty.get.a eq 'relet'}}
                               <input type="text" datatype="floatGroup" nullmsg="请输入房屋租金" {{if !empty($tcdata)}}value="{{$tcdata.rent}}"{{/if}} errormsg="请输入正确的租金金额" class="ipt ipt-188 mr5" name="rent" />
                               {{else}}
                               <input type="text" datatype="floatGroup" nullmsg="请输入房屋租金" {{if !empty($tcdata)}}value="{{$tcdata.rent}}"{{/if}} errormsg="请输入正确的租金金额" class="ipt ipt-188 mr5" name="rent" />
                               {{/if}}
                               <span class="jzf-unit">元/月</span>
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>房间押金：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq 'edit'}}
                        <input disabled type="text" class="ipt ipt-188 dista mr5" {{if !empty($tcdata)}}value="{{$tcdata.deposit}}"{{/if}} nullmsg="请输入房屋押金" errormsg="请输入正确的房间押金金额" name="deposit" />
                               {{elseif $smarty.get.a eq 'relet'}}
                               <input type="text" class="ipt ipt-188 mr5" datatype="floatGroup" {{if !empty($tcdata)}}value="{{$tcdata.deposit}}"{{/if}} nullmsg="请输入房屋押金" errormsg="请输入正确的房间押金金额" name="deposit" />
                               {{else}}
                               <input type="text" class="ipt ipt-188 mr5" datatype="floatGroup" {{if !empty($tmp_data)}}value="{{$tmp_data.money * $tmp_data.detain}}"{{/if}} nullmsg="请输入房屋押金" errormsg="请输入正确的房间押金金额" name="deposit" />
                               {{/if}}
                               <span class="jzf-unit">元</span>
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span><i class="red">*</i>押付方式：</span>
                    </div>
                    <div class="jzf-col-r clearfix">
                        <span class="jzf-txt fl">押</span>
                        <div class="selectByM w9">
                            {{if $smarty.get.a eq 'reservetolet'}}
                            <input type="text" class="selectByMT dpt-house-ya" name="detain" readonly = 'readonly' selectVal = '{{$data.detain}}'value="{{$detain_str}}"/>
                            {{elseif isset($smarty.get.house_type)}}
                            <input type="text" class="selectByMT dpt-house-ya" name="detain" readonly = 'readonly' selectVal = '{{$tmp_data.detain}}'  value="{{$detain_str}}"/>
                            {{elseif $smarty.get.a eq 'edit'}}
                            <input disabled type="text" class="selectByMT dpt-house-ya dista" name="detain" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.detain}}' value="{{$detain_str}}"{{/if}}/>
                                   {{elseif $smarty.get.a eq 'relet'}}
                                   <input type="text" class="selectByMT dpt-house-ya" name="detain" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.detain}}' value="{{$detain_str}}"{{/if}}/>
                                   {{else}}
                                   <input type="text" class="selectByMT dpt-house-ya" name="detain" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.detain}}' value="{{$tcdata.detain}}"{{/if}}/>
                                   {{/if}}
                                   <span class='jt_Ctr'><span class='jt_box'></span></span>
                            <div class="selectByMO">
                                <ul>
                                    {{if $smarty.get.a eq 'reservetolet'}}
                                    {{foreach from=$bet_arr key=k item=value }}
                                    {{if $k>=0}}
                                    {{if $k==$data.detain}}
                                    <li class="selectedLi" selectVal='{{$k}}' >{{$value}}</li>
                                    {{else}}
                                    <li selectVal='{{$k}}'>{{$value}}</li>
                                    {{/if}}
                                    {{/if}}
                                    {{/foreach}}
                                    {{elseif $smarty.get.a eq 'edit'}}
                                    {{elseif $smarty.get.a eq 'relet'}}
                                    {{foreach from=$bet_arr key=k item=value }}
                                    {{if $k>=0}}
                                    {{if $k==$tcdata.detain}}
                                    <li class="selectedLi" selectVal='{{$k}}'>{{$value}}</li>
                                    {{else}}
                                    <li selectVal='{{$k}}'>{{$value}}</li>
                                    {{/if}}
                                    {{/if}}
                                    {{/foreach}}
                                    {{else}}
                                    {{foreach from=$bet_arr key=k item=value }}
                                    <li {{if $k==$tmp_data.detain}}class="selectedLi" {{/if}} selectVal='{{$k}}'>{{$value}}</li>
                                    {{/foreach}}
                                    {{/if}}
                                </ul>
                            </div>
                        </div>
                        <span class="jzf-txt fl ml25">付</span>
                        <div class="selectByM w9">
                            {{if $smarty.get.a eq 'reservetolet'}}
                            <input type="text" class="selectByMT dpt-house-pay" name="pay" readonly = 'readonly' {{if !empty($data)}} selectVal = '{{$data.pay}}' value="{{$pay_str}}"{{/if}}/>
                                   {{elseif isset($smarty.get.house_type)}}
                                   <input type="text" class="selectByMT dpt-house-pay" name="pay" readonly = 'readonly' selectVal = '{{$tmp_data.pay}}'  value="{{$pay_str}}"/>
                            {{elseif $smarty.get.a eq 'edit'}}
                            <input disabled type="text" class="selectByMT dpt-house-pay dista" name="pay" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.pay}}' value="{{$pay_str}}"{{/if}}/>
                                   {{elseif $smarty.get.a eq 'relet'}}
                                   <input type="text" class="selectByMT dpt-house-pay" name="pay" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.pay}}' value="{{$pay_str}}"{{/if}}/>
                                   {{else}}
                                   <input type="text" class="selectByMT dpt-house-pay" name="pay" readonly = 'readonly' {{if !empty($tcdata)}} selectVal = '{{$tcdata.pay}}' value="{{$tcdata.pay}}"{{/if}}/>
                                   {{/if}}
                                   <span class='jt_Ctr'><span class='jt_box'></span></span>
                            <div class="selectByMO">
                                <ul>
                                    {{if  $smarty.get.a eq 'relet'}}
                                    {{foreach from=$pay_arr key=k item=value }}
                                    <li {{if $k+1 == $tcdata.pay}}class="selectedLi" {{/if}} selectVal='{{$k+1}}'>{{$value}}</li>
                                    {{/foreach}}
                                    <!-- <li {{if $tmp_data.pay eq '1'}}class="selectedLi"{{/if}} selectVal='1'>一</li>
                                    <li {{if $tmp_data.pay eq '2'}}class="selectedLi"{{/if}} selectVal='2'>二</li>
                                    <li  {{if $tmp_data.pay eq '3'}}class="selectedLi"{{/if}} selectVal='3'>三</li>
                                    <li  {{if $tmp_data.pay eq '4'}}class="selectedLi"{{/if}} selectVal='4'>四</li>
                                    <li {{if $tmp_data.pay eq '6'}} class="selectedLi" {{/if}} selectVal='6'>六</li>
                                    <li {{if $tmp_data.pay eq '12'}}class="selectedLi"{{/if}} selectVal='12'>十二</li> -->
                                    {{elseif $smarty.get.a eq 'reservetolet'}}
                                    {{foreach from=$pay_arr key=k item=value }}
                                    <li {{if $k+1 == $data.pay}}class="selectedLi" {{/if}} selectVal='{{$k+1}}'>{{$value}}</li>
                                    {{/foreach}}
                                    <!-- <li {{if $data.pay eq '1'}}class="selectedLi"{{/if}} selectVal='1'>一</li>
                                    <li {{if $data.pay eq '2'}}class="selectedLi"{{/if}} selectVal='2'>二</li>
                                    <li  {{if $data.pay eq '3'}}class="selectedLi"{{/if}} selectVal='3'>三</li>
                                    <li  {{if $data.pay eq '4'}}class="selectedLi"{{/if}} selectVal='4'>四</li>
                                    <li {{if $data.pay eq '6'}} class="selectedLi" {{/if}} selectVal='6'>六</li>
                                    <li {{if $data.pay eq '12'}}class="selectedLi"{{/if}} selectVal='12'>十二</li> -->
                                    {{elseif isset($smarty.get.house_type)}}
                                    {{foreach from=$pay_arr key=k item=value }}
                                    <li {{if $k+1 == $tmp_data.pay}}class="selectedLi" {{/if}} selectVal='{{$k+1}}'>{{$value}}</li>
                                    {{/foreach}}
                                    <!-- <li {{if $tmp_data.pay eq '1'}}class="selectedLi"{{/if}} selectVal='1'>一</li>
                                    <li {{if $tmp_data.pay eq '2'}}class="selectedLi"{{/if}} selectVal='2'>二</li>
                                    <li  {{if $tmp_data.pay eq '3'}}class="selectedLi"{{/if}} selectVal='3'>三</li>
                                    <li  {{if $tmp_data.pay eq '4'}}class="selectedLi"{{/if}} selectVal='4'>四</li>
                                    <li {{if $tmp_data.pay eq '6'}} class="selectedLi" {{/if}} selectVal='6'>六</li>
                                    <li {{if $tmp_data.pay eq '12'}}class="selectedLi"{{/if}} selectVal='12'>十二</li> -->
                                    {{elseif $smarty.get.a eq 'edit'}}
                                    {{else}}
                                    {{foreach from=$pay_arr key=k item=value }}
                                    <li selectVal='{{$k+1}}'>{{$value}}</li>
                                    {{/foreach}}
                                    <!-- <li  selectVal='1'>一</li>
                                    <li  selectVal='2'>二</li>
                                    <li  selectVal='3'>三</li>
                                    <li  selectVal='4'>四</li>
                                    <li  selectVal='6'>六</li>
                                    <li  selectVal='12'>十二</li> -->
                                    {{/if}}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>提前付款：</span>
                    </div>
                    <div class="jzf-col-r">
                        {{if $smarty.get.a eq 'edit'}}
                        <input disabled type="text" class="ipt ipt-188 mr5 dista" {{if !empty($tcdata)}}value="{{$tcdata.advance_time}}"{{/if}} nullmsg="请输入提前付款天数" errormsg="请输入正确的提前付款天数" name="advance_time" />
                               {{elseif $smarty.get.a eq 'relet'}}
                               <input type="text" class="ipt ipt-188 mr5" datatype="n" {{if !empty($tcdata)}}value="{{$tcdata.advance_time}}"{{/if}} nullmsg="请输入提前付款天数" errormsg="请输入正确的提前付款天数" name="advance_time" />
                               {{else}}
                               <input type="text" class="ipt ipt-188 mr5" value="15" datatype="n" {{if !empty($tcdata)}}value="{{$tcdata.advance_time}}"{{/if}} nullmsg="请输入提前付款天数" errormsg="请输入正确的提前付款天数" name="advance_time" />
                               {{/if}}
                               <span>天</span>
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            {{if $smarty.get.a eq 'edit'}}<!-- 编辑和查看合同的时候显示这块 -->
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l fl ml15">
                        <span><i class="red"></i>下次付款：</span>
                    </div>
                    <div class="jzf-col-r clearfix">
                        <div class="pay-next-time fl">
                            {{if !empty($tcdata)}}
                                {{if $tcdata.is_stop == 1}}
                                    已退租
                                {{else}}
                                    {{if $tcdata.next_pay_time gte $tcdata.dead_line}}租金已收完{{elseif ($tcdata.next_pay_time + $tcdata.advance_time * 86400) gte $tcdata.dead_line}}租金已收完{{else}}{{$tcdata.next_pay_time|date_format:'%Y-%m-%d'}}{{/if}}
                                {{/if}}
                            {{/if}}
                        </div>
                        <!--  <a href="javascript:;" class="notice-msg fl" actionUrl="{{'tenant-index/sendMessage'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id|cat:'&'|cat:'house_name='|cat:$tcdata.house_name|cat:'&'|cat:'tname='|cat:$tcdata.0.name|cat:'&'|cat:'next_pay_time='|cat:$tcdata.next_pay_time|cat:'&'|cat:'phone'|cat:$tcdata.0.phone|cat:'&'|cat:'pay='|cat:$tcdata.pay*$tcdata.rent}}"><i class="ifont">&#xe64b;</i>短信通知</a> -->
                    </div>
                    <!--<div class="jzf-col-r fl ml10">
                        <span>退租时间：</span>
                    </div>-->
                </div>
                 {{if $tcdata.is_stop == 1}}
	                <div class="col-box col-box-singel">
	                    <div class="jzf-col-l ml15 fl">
	                        <span><i class="red"></i>退租时间：</span>
	                    </div>
	                      <div class="jzf-col-r clearfix fl">
	                        <div class="pay-next-time fl">
	                            {{if !empty($tcdata)}}
	                                    {{$tcdata.end_line|date_format:'%Y-%m-%d'}}
	                            {{/if}}
	                        </div>
	                        <!--  <a href="javascript:;" class="notice-msg fl" actionUrl="{{'tenant-index/sendMessage'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id|cat:'&'|cat:'house_name='|cat:$tcdata.house_name|cat:'&'|cat:'tname='|cat:$tcdata.0.name|cat:'&'|cat:'next_pay_time='|cat:$tcdata.next_pay_time|cat:'&'|cat:'phone'|cat:$tcdata.0.phone|cat:'&'|cat:'pay='|cat:$tcdata.pay*$tcdata.rent}}"><i class="ifont">&#xe64b;</i>短信通知</a> -->
	                    </div>
	                </div>
                {{/if}}
            </div>
            {{/if}}
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l fl ml10" style="width: 800px;">
                        <span><i class="red" style="margin: 0;">&nbsp;</i>合同照片：<i class="red">（建议添加租客合同照片、租客证件照片等，要求：jpg、gif、png、pdf、word格式，最多上传9张）</i></span>
                    </div>
                </div>
            </div>
            <div class="jzf-col" style="margin-top:10px;padding-left: 85px;">
                <div class="uploader-area" id="js-uploaderArea-hz">
                    {{foreach from=$imag key=imgkey item=imgval}}
                    <div filename="{{$imgval.key}}" class="upload-imgview">
                        <img class="" style="_display: none;" src="{{imageView2 op='w/60/h/60' key=$imgval.key}}">
                        <span class="ie7bug"></span><i class="ifont deleteImg">&#xe627;</i>
                        <input type="hidden" name="images[new][room1][]" value="{{$imgval.key}}">
                    </div>
                    {{/foreach}}
                    <div class="uploadview-wrapper">
                        <div class="upload-group">
                            <div id="queue"></div>
                            <input id="file_upload_hz" name="file_upload" type="file">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="crm-item-top">
            <span>租客信息</span>
        </div>
        {{if $smarty.get.a eq 'edit'}}
        <input type="text" id="editContract" class="none" name="contract_id" value="{{$tcdata.contract_id}}" />
        <input type="text" id="editRenter" class="none" name="rental_id" value="{{$tcdata.rental_id}}" />
        {{/if}}
        <!--租客列表-->
        <div class="dpt-cutm-list" id="cutm-list">
            {{if !empty($alltenant) && is_array($alltenant)}}
            {{foreach from=$alltenant item=t}}
            <div class="crm-item-body dataForm dpt-custm-item">
                <input type="text" class="none" name="tenant_id[]" value="{{$t.tenant_id}}" />
                <input type="text" class="none" name="contract_rental_id[]" value="{{$t.contract_rental_id}}" />
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>租客姓名：</span>
                        </div>
                        <div class="jzf-col-r">
                            <input type="text" datatype="*" nullmsg="请输入租客姓名" {{if !empty($t)}}value="{{$t.name}}"{{/if}} errormsg="姓名格式错误" class="ipt ipt-250" name="name[]" />
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                    <div class="col-box col-box-singel">
                        <div class="jzf-col-l float-l">
                            <span><i class="red">*</i>租客性别：</span>
                        </div>
                        <div class="jzf-col-r clearfix">
                            <div class="radio-box">
                                <label class="radio">
                                    {{if !empty($t) && $t.gender eq 1}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                </label>
                                <input type="radio" name="gender[]"  {{if !empty($t) && $t.gender eq 1}}checked="checked"{{/if}} value="1" />
                                       <span>男</span>
                            </div>
                            <div class="radio-box ml60">
                                <label class="radio">
                                    {{if !empty($t) && $t.gender eq 2}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                </label>
                                <input type="radio" name="gender[]"  {{if !empty($t) && $t.gender eq 2}}checked="checked"{{/if}} value="2" />
                                       <span>女</span>
                            </div>
                            <span class="check-error check-error-ts check-error-auto" style="line-height: 32px;margin-left: 5px;"></span>
                        </div>
                    </div>
                </div>
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>联系电话：</span>
                        </div>
                        <div class="jzf-col-r">
                            <input type="text" datatype="/^1\d{10}$/" nullmsg="请输入联系电话" errormsg="电话号码格式错误" {{if !empty($t)}}value="{{$t.phone}}"{{/if}} name="phone[]" class="ipt ipt-250" />
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                    <div class="col-box col-box-singel">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>证件号码：</span>
                        </div>
                        <div class="jzf-col-r"  style="position:relative;">
                            <input type="text" data-score-action="{{'tenant-index/getScore'|url}}" data-info-action="{{'tenant-Evaluation/index'|url|cat:'&type=jumpFromCheck'}}" datatype="*1-40"  nullmsg="请输入证件号码" {{if !empty($t)}}value="{{$t.idcard}}" {{/if}} errormsg="证件号码格式错误" name="idcard[]" class="ipt ipt-250" />
                                   <span class="check-error check-error-ts check-error-auto"></span>
                            <div class="check-error-ts tip-black-list" style="display: none;">
                                <div class="pos-rel">
                                    <i class="ifont red">&#xf00d9;</i>
                                    <i class="ico-arow_down-gray"></i>
                                    <span class="tip-msg">
                                        该租客评价分数<i class="red">2</i>,
                                        点此<a href="javascript:;">查看详情</a>
                                    </span>
                                    <i class="ifont close-user-score-triger">&#xe627;</i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l float-l">
                            <span class="ml16">来源渠道：</span>
                        </div>
                        <div class="jzf-col-r fl">
                            <div class="selectByM w25" hasevent="3">
                                <input type="text" name="from[]" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly'{{if !empty($t)}} selectVal = '{{$t.from}}' {{/if}} value=""/>
                                       <span class='jt_Ctr'><span class='jt_box'></span></span>
                                <div class="selectByMO">
                                    <ul>
                                        {{foreach from=$sysSouce key=k item=f}}
                                        <li 4="{{$t.from}}" f="{{$k}}"{{if !empty($t) && $t.from == $k}} class="selectedLi" {{/if}} selectVal='{{$k}}'>{{$f}}</li>
                                        {{/foreach}}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="javascript:;" class="del-custmer"><i class="ifont">&#xe675;</i>删除</a>
            </div>
            {{/foreach}}
            {{else}}
            <div class="crm-item-body dataForm dpt-custm-item lst-child">
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>租客姓名：</span>
                        </div>
                        <div class="jzf-col-r">
                            {{if $smarty.get.a eq 'reservetolet'}}
                            <input type="text" datatype="*" nullmsg="请输入租客姓名" value="{{$tdata.name}}" errormsg="姓名格式错误" class="ipt ipt-250" name="name[]" />
                            {{else}}
                            <input type="text" datatype="*" nullmsg="请输入租客姓名" {{if !empty($t)}}value="{{$t.name}}"{{/if}} errormsg="姓名格式错误" class="ipt ipt-250" name="name[]" />
                                   {{/if}}
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                    <div class="col-box col-box-singel">
                        <div class="jzf-col-l float-l">
                            <span><i class="red">*</i>租客性别：</span>
                        </div>
                        <div class="jzf-col-r clearfix">
                            <div class="radio-box">
                                <label class="radio">
                                    {{if $smarty.get.a eq 'reservetolet'}}<!-- 预定转出租 -->
                                    {{if !empty($tdata) && $tdata.gender eq 1}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                    {{else}}
                                    {{if !empty($t) && $t.gender eq 1}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                    {{/if}}
                                </label>
                                {{if $smarty.get.a eq 'reservetolet'}}<!-- 预定转出租 -->
                                <input type="radio" name="gender[]"  {{if !empty($tdata) && $tdata.gender eq 1}}checked="checked"{{/if}} value="1" />
                                       {{else}}
                                       <input type="radio" name="gender[]"  {{if !empty($t) && $t.gender eq 1}}checked="checked"{{/if}} value="1" />
                                       {{/if}}
                                       <span>男</span>
                            </div>
                            <div class="radio-box ml60">
                                <label class="radio">
                                    {{if $smarty.get.a eq 'reservetolet'}}<!-- 预定转出租 -->
                                    {{if !empty($tdata) && $tdata.gender eq 2}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                    {{else}}
                                    {{if !empty($t) && $t.gender eq 2}}
                                    <i class="ifont r-default" style="display:none;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:block;">&#xe617;</i>
                                    {{else}}
                                    <i class="ifont r-default" style="display:block;">&#xe612;</i>
                                    <i class="ifont r-select" style="display:none;">&#xe617;</i>
                                    {{/if}}
                                    {{/if}}
                                </label>
                                {{if $smarty.get.a eq 'reservetolet'}}<!-- 预定转出租 -->
                                <input type="radio" name="gender[]"  {{if !empty($tdata) && $tdata.gender eq 2}}checked="checked"{{/if}} value="2" />
                                       {{else}}
                                       <input type="radio" name="gender[]"  {{if !empty($t) && $t.gender eq 2}}checked="checked"{{/if}} value="2" />
                                       {{/if}}
                                       <span>女</span>
                            </div>
                            <!-- <span class="check-error check-error-ts check-error-auto" style="line-height: 32px;margin-left: 5px;"></span> -->
                        </div>
                    </div>
                </div>
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>联系电话：</span>
                        </div>
                        <div class="jzf-col-r">
                            {{if $smarty.get.a eq 'reservetolet'}}
                            <input type="text" datatype="/^1\d{10}$/" nullmsg="请输入联系电话" errormsg="电话号码格式错误" value="{{$tdata.phone}}" name="phone[]" class="ipt ipt-250" />
                            {{else}}
                            <input type="text" datatype="/^1\d{10}$/" nullmsg="请输入联系电话" errormsg="电话号码格式错误" {{if !empty($t)}}value="{{$t.phone}}"{{/if}} name="phone[]" class="ipt ipt-250" />
                                   {{/if}}
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                    <div class="col-box col-box-singel">
                        <div class="jzf-col-l">
                            <span><i class="red">*</i>证件号码：</span>
                        </div>
                        <div class="jzf-col-r" style="position:relative;">
                            {{if $smarty.get.a eq 'reservetolet'}}
                            <input type="text" data-score-action="{{'tenant-index/getScore'|url}}" data-info-action="{{'tenant-Evaluation/index'|url|cat:'&type=jumpFromCheck'}}" datatype="*1-40" nullmsg="请输入证件号码" value="{{$tdata.idcard}}" errormsg="证件号码格式错误" name="idcard[]" class="ipt ipt-250" />
                            {{else}}
                            <input type="text" data-score-action="{{'tenant-index/getScore'|url}}" data-info-action="{{'tenant-Evaluation/index'|url|cat:'&type=jumpFromCheck'}}" datatype="*1-40" nullmsg="请输入证件号码" {{if !empty($t)}}value="{{$t.idcard}}"{{/if}} errormsg="证件号码格式错误" name="idcard[]" class="ipt ipt-250" />
                                   {{/if}}
                                   <span class="check-error check-error-ts check-error-auto"></span>
                            <div class="check-error-ts tip-black-list" style="display: none;">
                                <div class="pos-rel">
                                    <i class="ifont red">&#xf00d9;</i>
                                    <i class="ico-arow_down-gray"></i>
                                    <span class="tip-msg">
                                        该租客评价分数<i class="red">2</i>,
                                        点此<a href="javascript:;">查看详情</a>
                                    </span>
                                    <i class="ifont close-user-score-triger">&#xe627;</i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l float-l">
                            <span class="ml16">来源渠道：</span>
                        </div>
                        <div class="jzf-col-r fl">
                            <div class="selectByM w25" hasevent="3">
                                <input type="text" name="from[]" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value=""/>
                                <span class='jt_Ctr'><span class='jt_box'></span></span>
                                <div class="selectByMO">
                                    <ul>
                                        {{foreach from=$sysSouce key=k item=f}}
                                        <li  {{if !empty($t) && $t.from == $k}} class="selectedLi" {{/if}} selectVal='{{$k}}'>{{$f}}</li>
                                        {{/foreach}}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {{/if}}
            <a href="javascript:;" class="jzf-add-btn ml10" id="dpt-add-client"><i class="ifont">&#xf0037;</i>添加租客</a>
        </div>
        {{if !empty($fee_data)}}
        <!--租客列表end-->
        <div class="crm-item-top">
            <span>费用信息</span>
        </div>
        <!--费用列表-->

        <div class="dpt-cutm-list" id="dpt-fee-list">
            {{foreach from=$fee_data item=v}}
            <div class="crm-item-body dpt-custm-item pdl15 dataForm">

                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l float-l">
                            <span>费用名称：</span>
                        </div>
                        <div class="jzf-col-r clearfix triger-drag-down">
                            <div class="selectByM w25">
                                <input type="text" name="fee_name[]" class="selectByMT centralized_Ind_CuteType dista" disabled="disabled" selectVal = '{{$v.fee_type_id}}' value="{{$v.type_name}}"/>
                                <!--<span class='jt_Ctr'><span class='jt_box'></span></span>-->
                                <div class="selectByMO">
                                    <ul>
                                        <!-- {{if $smarty.get.a eq 'edit'}}
                                        {{else}}
                                            {{foreach from=$ftname item=f}}
                                                <li selectVal='{{$f.fee_type_id}}'>{{$f.type_name}}</li>
                                            {{/foreach}}
                                        {{/if}} -->
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-box">
                        <div class="jzf-col-l float-l">
                            <span>计费方式：</span>
                        </div>
                        <div class="jzf-col-r clearfix">
                            <div class="selectByM w25" hasevent="2">
                                <input type="text" name="fee_type[]" {{if $smarty.get.a eq 'edit'}}disabled {{/if}} class="selectByMT centralized_Ind_CuteType dista" readonly = 'readonly' selectVal = '0' value="{{$v.payment_str}}"/>
                                <!--<span class='jt_Ctr'><span class='jt_box'></span></span>-->
                                       <div class="selectByMO">
                                    <ul>
                                        <!-- {{if $smarty.get.a eq 'edit'}}
                                        {{else}}
                                            {{if $tmp_data.rental_way eq '2'}}
                                                <li selectVal='1' {{if $v.payment_mode eq 1}}class="selectedLi"{{/if}}>一次性支付</li>
                                                <li selectVal='2' {{if $v.payment_mode eq 2}}class="selectedLi"{{/if}}>按月支付</li>
                                            {{else}}
                                                {{foreach from=$sysconfig key=keys item=vs}}
                                                    <li selectVal='{{$keys}}' {{if $v.payment_mode == $keys}}class="selectedLi"{{/if}}>{{$vs}}</li>
                                                {{/foreach}}
                                            {{/if}}
                                        {{/if}} -->
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="jzf-col">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span>收费单价：</span>
                        </div>
                        <div class="jzf-col-r">
                            <input type="text"  name="fee_price[]" class="ipt ipt-188 mr5 dista" nullmsg="请输入收费单价"  datatype="floatGroup" value="{{$v.money}}" errormsg="请输入正确的金额" >
                            <span class="jzf-unit">元/月</span>
                            <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>

                    {{if $v.payment_mode gt 2 and $v.payment_mode lt 6}}
                    <div class="col-box data-cb-opts">
                        <div class="jzf-col-l">
                            <span>当前底度：</span>
                        </div>
                        <div class="jzf-col-r">
                            <input type="text" data-name="now_num[]" {{if $smarty.get.a eq 'edit'}}disabled {{/if}} value="{{$v.now_meter}}" name="now_num[]" nullmsg="请输入当前底度" ignore="ignore" datatype="floatGroup" errormsg="请输入正确的底度" class="ipt ipt-188 mr5">
                            <!-- <span class="jzf-unit">元/月</span> -->
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                    {{/if}}

                </div>

                {{if $v.payment_mode gt 2 and $v.payment_mode lt 6}}
                <div class="jzf-col data-cb-opts">
                    <div class="col-box">
                        <div class="jzf-col-l">
                            <span>抄表日期：</span>
                        </div>
                        <div class="jzf-col-r">
                            <input type="text" {{if $smarty.get.a eq 'edit'}}disabled {{/if}}data-name="record_time[]" value="{{$v.add_time}}" name="record_time[]" readonly="readonly"  datatype="*" nullmsg="请选择抄表日期" class="ipt ipt-188 mr5 wdate">
                                   <span class="check-error check-error-ts check-error-auto"></span>
                        </div>
                    </div>
                </div>
                {{/if}}

                 <!--<a href="javascript:;" class="del-fee-trigger"><i class="ifont">&#xe675;</i>删除</a>-->
            </div>
            {{/foreach}}
            {{else}}
            <!--租客列表end-->

            <div style="display:none" class="crm-item-top fee-item-top">
                <span>费用信息</span>
            </div>
            <!--费用列表-->

            <div style="display:none" class="dpt-cutm-list" id="dpt-fee-list">

            </div>

            {{/if}}

            <div class="crm-item-body dataForm pdl15">
                <div class="jzf-col">
                    <div class="jzf-col-l float-l">
                        <span>备注信息：</span>
                    </div>
                    <div class="jzf-col-r fl">
                        <textarea name="remark">{{$tcdata.remark}}</textarea>
                    </div>
                </div>
                <div class="dpt-bot-grp">
                    <a href="javascript:;" data-xz="{{if $smarty.get.a eq 'relet'}}relet{{/if}}"
                       xzUrl="{{'tenant-index/relet'|url|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}"
                       class="btn btn2 subArmtForm"
                       editUrl="{{'tenant-index/edit'|url|cat:'&'|cat:'rental_id='|cat:$tcdata.rental_id|cat:'&'|cat:'contract_id='|cat:$tcdata.contract_id}}"
                       {{if $smarty.get.a eq 'reservetolet'}}reserveURL="{{'tenant-index/reserveToLet'|url}}{{/if}}"
                       >保存</a>
                    <a href="javascript:;" class="btn btn4 ml10 btn-cancel">取消</a>
                </div>
            </div>

        </div>
        <!--数据循环End-->
    </div>
    <!--添加多租客模板-->
    <div class="emptyTemp not" style="display: none;">
        <div class="crm-item-body dpt-custm-item {cls}">
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>租客姓名：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" datatype="*" nullmsg="请输入租客姓名" errormsg="姓名不能包含特殊字符" class="ipt ipt-250" name="name[]" />
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l float-l">
                        <span><i class="red">*</i>租客性别：</span>
                    </div>
                    <div class="jzf-col-r clearfix">
                        <div class="radio-box">
                            <label class="radio"><i class="ifont r-default" style="display:none;">&#xe612;</i>
                                <i class="ifont r-select" style="display:block;">&#xe617;</i>
                            </label>
                            <input type="radio" name="gender[]"   checked="checked" value="1" />
                            <span>男</span>
                        </div>
                        <div class="radio-box ml60">
                            <label class="radio"><i class="ifont r-default">&#xe612;</i>
                                <i class="ifont r-select">&#xe617;</i>
                            </label>
                            <input type="radio" name="gender[]"   value="2" />
                            <span>女</span>
                        </div>
                    </div>
                    <!-- <span class="check-error check-error-ts check-error-auto" style="line-height: 32px;margin-left: 5px;"></span> -->
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>联系电话：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" datatype="/^1\d{10}$/" nullmsg="请输入联系电话" errormsg="电话号码格式错误" name="phone[]" class="ipt ipt-250" />
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                <div class="col-box col-box-singel">
                    <div class="jzf-col-l">
                        <span><i class="red">*</i>证件号码：</span>
                    </div>
                    <div class="jzf-col-r"  style="position:relative;">
                        <input type="text" data-score-action="{{'tenant-index/getScore'|url}}" data-info-action="{{'tenant-Evaluation/index'|url|cat:'&type=jumpFromCheck'}}" datatype="*1-40" nullmsg="请输入证件号码" errormsg="证件号码格式错误" name="idcard[]" class="ipt ipt-250" />
                        <span class="check-error check-error-ts check-error-auto"></span>
                        <div class="check-error-ts tip-black-list" style="display: none;">
                            <div class="pos-rel">
                                <i class="ifont red">&#xf00d9;</i>
                                <i class="ico-arow_down-gray"></i>
                                <span class="tip-msg">
                                    该租客评价分数<i class="red">2</i>,
                                    点此<a href="javascript:;">查看详情</a>
                                </span>
                                <i class="ifont close-user-score-triger">&#xe627;</i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span class="ml16">来源渠道：</span>
                    </div>
                    <div class="jzf-col-r fl">
                        <div class="selectByM w25" hasevent="3">
                            <input type="text" name="from[]" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' {{if !empty($t)}} selectVal = '{{$t.from}}' value=""{{/if}}/>
                                   <span class='jt_Ctr'><span class='jt_box'></span></span>
                            <div class="selectByMO">
                                <ul>
                                    {{foreach from=$sysSouce key=k item=f}}
                                    <li  {{if !empty($t) && $t.from == $k}} class="selectedLi" {{/if}} selectVal='{{$k}}'>{{$f}}</li>
                                    {{/foreach}}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="javascript:;" class="del-custmer"><i class="ifont">&#xe675;</i>删除</a>
        </div>
    </div>
    <!--添加多租客模板end-->
    <!-- 添加多费用模板 -->
    <div class="emptyFeeTemp" style="display: none;" data-type="{{$tmp_data.rental_way}}">
        <div class="crm-item-body dpt-custm-item pdl15 {cls}">
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span>费用名称：</span>
                    </div>
                    <div class="jzf-col-r clearfix triger-drag-down">
                        <div class="selectByM w25" hasevent="3">
                            <input type="text" name="fee_name[]" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value=""/>
                            <span class='jt_Ctr'><span class='jt_box'></span></span>
                            <div class="selectByMO">
                                <ul>
                                    {{foreach from=$ftname item=f}}
                                    <li selectVal='{{$f.fee_type_id}}'>{{$f.type_name}}</li>
                                    {{/foreach}}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span>计费方式：</span>
                    </div>
                    <div class="jzf-col-r clearfix cache-pay-way-data">
                        <div class="selectByM w25"  hasevent="2">
                            <input type="text" name="fee_type[]" class="selectByMT centralized_Ind_CuteType" readonly = 'readonly' selectVal = '0' value=""/>
                            <span class='jt_Ctr'><span class='jt_box'></span></span>
                            <div class="selectByMO">
                                <ul>
                                    {{foreach from=$sysconfig key=key item=v}}
                                    <li selectVal='{{$key}}'>{{$v}}</li>
                                    {{/foreach}}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span>收费单价：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" name="fee_price[]"  datatype="floatGroup" nullmsg="请输入收费单价" errormsg="请输入正确的金额" class="ipt ipt-188 mr5">
                        <span class="jzf-unit">元</span>
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>

                <div class="col-box data-cb-opts" style="display: none;">
                    <div class="jzf-col-l">
                        <span>当前底度：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" data-name="now_num[]"  name="now_num[]" ignore="ignore" datatype="floatGroup" nullmsg="请输入当前底度" errormsg="请输入正确的底度" class="ipt ipt-188 mr5">

                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            <div class="jzf-col data-cb-opts" style="display: none;">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span>抄表日期：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" data-name="record_time[]"  name="record_time[]" readonly="readonly"  datatype="*" nullmsg="请选择抄表日期" class="ipt ipt-188 mr5 wdate">
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            <a href="javascript:;" class="del-fee-trigger"><i class="ifont">&#xe675;</i>删除</a>
        </div>
    </div>
    <!--添加多费用模板end-->

    <!--费用名称循环模板-->
    <script type="text/html" id="fee-dynamic-temp">
        <ul>
            {{'<% for (var i = 0; i < data.length; i ++) { %>'}}
            <li selectVal='{{'<%=data[i].id%>'}}'>{{'<%=data[i].text%>'}}</li>
            {{'<%}%>'}}
        </ul>
    </script>
    <!--费用名称循环模板end-->


    <!--根据房间加载对应费用循环模板-->
    <script type="text/html" id="feeListTemp">
        {{'<% for (var i = 0; i < feeabout.length; i ++) { %>'}}
        <div class="crm-item-body dpt-custm-item pdl15 dataForm">
            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span>费用名称：</span>
                    </div>
                    <div class="jzf-col-r clearfix triger-drag-down">
                        <div class="selectByM w25">
                            <input type="text" name="fee_name[]" class="selectByMT centralized_Ind_CuteType " disabled="disabled" selectVal="{{'<%=feeabout[i].fee_id%>'}}" value="{{'<%=feeabout[i].type_name%>'}}"/>
                            <div class="selectByMO">
                                <ul></ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-box">
                    <div class="jzf-col-l float-l">
                        <span>计费方式：</span>
                    </div>
                    <div class="jzf-col-r clearfix">
                        <div class="selectByM w25" hasevent="2">
                            <input type="text" name="fee_type[]"  class="selectByMT centralized_Ind_CuteType " readonly = 'readonly'  selectVal="{{'<%=feeabout[i].fee_type_id%>'}}" value="{{'<%=feeabout[i].payment_str%>'}}"/>
                            <div class="selectByMO">
                                <ul>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="jzf-col">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span>收费单价：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" disabled="disabled"  name="fee_price[]" class="ipt ipt-188 mr5 " nullmsg="请输入收费单价"  datatype="floatGroup" value="{{'<%=feeabout[i].money%>'}}" errormsg="请输入正确的金额" >
                        <span class="jzf-unit">元/月</span>
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                {{'<%if(feeabout[i].payment_mode == 3 || feeabout[i].payment_mode == 4 || feeabout[i].payment_mode == 5) { %>'}}
                <div class="col-box data-cb-opts">
                    <div class="jzf-col-l">
                        <span>当前底度：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" data-name="now_num[]"  value="" name="now_num[]" nullmsg="请输入当前底度"  datatype="floatGroup" errormsg="请输入正确的底度" class="ipt ipt-188 mr5">

                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
                {{'<%}%>'}}
            </div>
            {{'<%if(feeabout[i].payment_mode == 3 || feeabout[i].payment_mode == 4 || feeabout[i].payment_mode == 5) { %>'}}
            <div class="jzf-col data-cb-opts">
                <div class="col-box">
                    <div class="jzf-col-l">
                        <span>抄表日期：</span>
                    </div>
                    <div class="jzf-col-r">
                        <input type="text" data-name="record_time[]" value="" name="record_time[]" readonly="readonly"  datatype="*" nullmsg="请选择抄表日期" class="ipt ipt-188 mr5 wdate">
                        <span class="check-error check-error-ts check-error-auto"></span>
                    </div>
                </div>
            </div>
            {{'<%}%>'}}
        </div>
        {{'<%}%>'}}
    </script>
    <!--根据房间加载对应费用循环模板end-->
