{{if $view == 'template'}}
<div class="crm-manage crm-list jzf-form">
    <!--筛选-->
    <!-- 这是合同列表 -->
    <div class="crm-top">
        <div class="dpt-toolbar-inactive ">
            <div class="jzf-col dpt-row-dtm">
                <div class="jzf-col-l">
                    <span>预订周期：</span>
                </div>
                <div class="jzf-col-r">
                    <input type="text" readonly="readonly" id="exp_bdate" value="" class="ipt wdate" name="" placeholder="" />
                    <span class="jzf-unit">--</span>
                    <input type="text" readonly="readonly" id="exp_edate" class="ipt wdate" name="" placeholder="" />
                </div>
            </div>
            <div class="jzf-col clearfix dpt-room-type">
                <div class="jzf-col-l fl sf-mt">
                    <span>房源形态：</span>
                </div>
                <div class="jzf-col-r jzf-col-r-auto fl">
                    <a href="javascript:;" data-type="2" class="dpt-sort {{if $house_type == 2}}current{{/if}}">集中式公寓</a>
                    <a href="javascript:;" data-type="1" class="dpt-sort {{if $house_type == 1}}current{{/if}}">分散式租房</a>
                </div>
            </div>
            <div class="jzf-col">
                <div class="jzf-col-l fl sf-mt">
                    <span>关键词：</span>
                </div>
                <div class="jzf-col-r clearfix">
                    <div class="search fl ml20">
                        {{if isset($room_name)}}<!-- 首页代办过来 -->
                        {{if $room_name.house_type == 1}}<!-- 分散式 -->
                        {{if $room_name.rental_way == 1}}<!-- 合 -->
                        <input type="text" id="keywords" class="ipt" value="{{$room_name.house_name}}{{$room_name.room_type}}{{$room_name.custom_number}}" placeholder="小区名称/房间编号/租客电话">
                        <a href="javascript:;" id="goSearchTrig" class="btn btn3 ifont"></a>
                        {{else}}<!-- 整 -->
                        <input type="text" id="keywords" class="ipt" value="{{$room_name.house_name}}" placeholder="小区名称/房间编号/租客电话">
                        <a href="javascript:;" id="goSearchTrig" class="btn btn3 ifont"></a>
                        {{/if}}
                        {{else}}<!-- 集中式 -->
                        <input type="text" id="keywords" class="ipt" value="{{$key_word}}" placeholder="小区名称/房间编号/租客电话">
                        <a href="javascript:;" id="goSearchTrig" class="btn btn3 ifont"></a>
                        {{/if}}
                        {{else}}<!-- 房间详细过来 -->
                        <input type="text" id="keywords" class="ipt" {{if isset($smarty.get.room_id)}}value="{{$smarty.get.room_id}}"{{/if}} placeholder="小区名称/房间编号/租客电话">
                        <a href="javascript:;" id="goSearchTrig" class="btn btn3 ifont"></a>
                        {{/if}}
                    </div>
                </div>
            </div>
            <div class="dpt-toolbar">
                <a href="javascript:;" reserveURL="{{'tenant-index/addReserve'|url}}" class="dpt-add-reserve"><i class="ifont">&#xe61c;</i>添加预定</a>
                <a href="javascript:;" class="dpt-toolbar-delete"><i class="ifont">&#xe675;</i>删除</a>
                <!-- <a href="javascript:;"><i class="ifont">&#xf0131;</i>打印</a> -->
            </div>
            <div class="dpt-toolbar dpt-toolbar-active">
	 		<span class="mr20">
	 			<label class="checkBox checkBoxAll"><span class="choose ifont1">&#xe60c;</span></label> <a href="javascript:;">全选</a>
	 		</span>
                <a href="javascript:;" class="dpt-toolbar-active-delete" data-url="{{'tenant-index/delreserve'|url}}"><i class="ifont">&#xe675;</i>删除</a>
                <a href="javascript:;" class="edit-cancle-trig"><i class="ifont">&#xe627;</i>取消</a>
            </div>
        </div>
    </div>
    <!--列表-->
    <table class="lst_tb" listaction="{{'tenant-index/reserve/view_type/data'|url}}">
        <tr>
            <th class="w10">预定人姓名</th>
            <th class="w12">预定人电话</th>
            <th>房间名称</th>
            <th>预定周期</th>
            <th class="w10">定金金额</th>
            <th>操作</th>
        </tr>

        <!-- 循环这一块 -->
        {{/if}}
        {{if $view == 'data'}}
        {{foreach from=$alldata item=d}}
        <tr data-id="{{$d.reserve_id}}" >
            <td class="w10">
				<span>
					<label class="checkBox"><span class="ifont1">&#xe60c;</span></label>
					<input type="checkbox" value="{{$d.name}}" />
				</span>
                <span>{{$d.name}}</span>
            </td>
            <td class="w12">{{$d.phone}}</td>
            <td>
                {{$d.full_name}}
            </td>
            <td>{{$d.stime|date_format:'%Y/%m/%d'}}-{{$d.etime|date_format:'%Y/%m/%d'}}</td>
            <td class="w10">{{$d.money}}</td>
            <td>
                <div class="edit-col">
                    <a href="javascript:;" class="dpt-reserve-preview" data-url="{{'tenant-index/showreserve'|url}}">查看</a>
                    <em>|</em>
                    <a href="#{{'tenant-index/reserveToLet'|url|cat:'&'|cat:'reserve_id='|cat:$d.reserve_id}}" class="dpt-reserve-deal">出租</a>
                    <em>|</em>
                    <a href="javascript:;" class="cancle-reserve-trig" data-url="{{'tenant-index/debook'|url}}">退定</a>
                    <em>|</em>
                    <a href="javascript:;" class="spr-del-trig" data-url="{{'tenant-index/delreserve'|url}}">删除</a>
                </div>
            </td>
        </tr>
        {{/foreach}}
        {{/if}}
        {{if $view == 'template'}}
        <!-- 循环这一块 -->
    </table>
    <div class="jzf-pagination clearfix">
        <div class="pagination" id="crm-manage-pagination"></div>
        <div class="jump-to-page clearfix">
            <span>跳转至</span>
            <div class="jump-edit-box">
                <input type="text" placeholder="页码">
                <a href="javascript:;" class="p-btn btn btn4">GO</a>
                <i class="page-unit">页</i>
            </div>
        </div>
    </div>
</div>
<!--预订人信息展示/编辑遮罩模板-->
<div id="hide_reserve_detail" class="none">
    <div class="rsv-wrap reserveUserForm jzf-form" id="reserve_box" action="">
        <div class="jzf-col">
            <div class="jzf-col-l float-l">
                <span><i class="red">*</i>房间名称：</span>
            </div>
            <div class="jzf-col-r fl clearfix">
                <input type="text" id="houses" datatype="*,checkhouse" name="housename" nullmsg="请输入房间名称" class="ipt ipt-425 ipx-txt" edit-url="{{'tenant-index/showreserve'|url}}" searchURL="{{'tenant-index/getinfo'|url}}"/>
                <input type="hidden" name="community_id">
				<span class="check-error-ts check-error-auto">
					<i class="ico-arrwo-d"></i>
					<span class="check-error"></span>
				</span>
            </div>
        </div>
        <div class="jzf-col">
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>预&nbsp;&nbsp;定&nbsp;&nbsp;人：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="*" name="name" nullmsg="请输入预定人" class="ipt ipt-165  ipx-txt">
					<span class="check-error-ts check-error-auto">
					<i class="ico-arrwo-d"></i>
					<span class="check-error"></span>
				</span>
                </div>
            </div>
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>联系电话：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="/^1\d{10}$/" name="phone" nullmsg="请输入联系电话" errormsg="手机号码格式错误" class="ipt ipt-165  ipx-txt" >
					<span class="check-error-ts check-error-phone">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
                </div>
            </div>
        </div>
        <div class="jzf-col">
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>证件号码：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="*1-40" name="idcard" prevval =  "" errormsg="证件号码格式错误" nullmsg="请输入预定人证件号码" class="ipt ipt-165  ipx-txt" data-info-action="{{'tenant-index/getComment'|url}}"  data-score-action="{{'tenant-index/getScore'|url}}">
					<span class="check-error-ts check-error-auto">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
                    <div class="check-error-ts tip-black-list" style="display: none;">
                        <div class="pos-rel">
                            <i class="ifont red">&#xf00d9;</i>
                            <i class="ico-arow_down-gray"></i>
							<span class="tip-msg">
								该租客评价分数<i class="red">2</i>,
								点此<a href="javascript:;">查看详情</a>
							</span>
                        </div>
                        <a href="javascript:;" class="this-close">x</a>
                    </div>
                </div>
            </div>
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>支付定金：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="float" name="money" nullmsg="请输入定金金额" errormsg="定金应大于等于0" class="ipt ipt-165  ipx-txt">
					<span class="check-error-ts check-error-auto">
					<i class="ico-arrwo-d"></i>
					<span class="check-error"></span>
				</span>
                </div>
            </div>
        </div>
        <div class="jzf-col">
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>起始日期：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="*,checkstart" readonly="readonly" name="begin_date" nullmsg="请选择起始日期" errormsg="起始时间不能大于终止时间" class="ipt ipt-165 rev-over-temp-wdate ipx-txt">
					<span class="check-error-ts check-error-auto">
					<i class="ico-arrwo-d"></i>
					<span class="check-error"></span>
				</span>
                </div>
            </div>
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>终止日期：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <input type="text" datatype="*,checkend" readonly="readonly"  name="end_date" nullmsg="请选择终止日期" errormsg="终止时间不能小于起始时间" class="ipt ipt-165 rev-over-temp-wdate  ipx-txt">
					<span class="check-error-ts check-error-auto">
						<i class="ico-arrwo-d"></i>
						<span class="check-error"></span>
					</span>
                </div>
            </div>
        </div>
        <div class="jzf-col">
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>支付方式：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <div class="rev-over-temp-selectByM selectByM w9" hasevent=true>
                        <input type="text" class="selectByMT centralized_Ind_CuteType" name="ya" readonly = 'readonly' selectVal = '' value="选择支付方式" datatype="chooseGroup" choosenull = "请选择支付方式"/>
                        <span class='jt_Ctr'><span class='jt_box'></span></span>
                        <div class="selectByMO">
                            <ul>
                                <li selectVal='1'>支付宝</li>
                                <li selectVal='2'>现金支付</li>
                                <li selectVal='3'>银行卡支付</li>
                                <li selectVal='4'>其他</li>
                            </ul>
                        </div>
								<span class="check-error-ts check-error-auto">
									<i class="ico-arrwo-d"></i>
									<span class="check-error"></span>
								</span>
                    </div>
                </div>
            </div>
            <div class="col-box">
                <div class="jzf-col-l float-l">
                    <span><i class="red">*</i>来源渠道：</span>
                </div>
                <div class="jzf-col-r fl clearfix">
                    <div class="rev-over-temp-selectByM selectByM w9" hasevent=true>
                        <input type="text" class="selectByMT centralized_Ind_CuteType" name="fu" readonly = 'readonly' selectVal = '' value="选择来源渠道" datatype="chooseGroup" choosenull = "请选择来源渠道"/>
                        <span class='jt_Ctr'><span class='jt_box'></span></span>
                        <div class="selectByMO">
                            <ul>
                                <li selectVal='1'>网络渠道</li>
                                <li selectVal='2'>客户介绍</li>
                                <li selectVal='3'>自来客</li>
                                <li selectVal='4'>会员</li>
                                <li selectVal='5'>其他</li>
                            </ul>
                        </div>
						<span class="check-error-ts check-error-auto">
							<i class="ico-arrwo-d"></i>
							<span class="check-error"></span>
						</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="jzf-col">
            <div class="jzf-col-l">
                <span><i class="red">&nbsp;&nbsp;</i>备注说明：</span>
            </div>
            <div class="jzf-col-r blo-row">
                <textarea class="ipx-txt" id="remark" datatype="string255" ignore="ignore" errormsg="备注不能超过255个字符"></textarea>
				<span class="check-error-ts check-error-auto">
					<i class="ico-arrwo-d ico-arrwo-d-remark"></i>
					<span class="check-error check-error-textarea"></span>
				</span>
            </div>
        </div>
        <div class="jzf-col">
            <div class="resv-act-btns">
                <a href="javascript:;" class="btn btn2" id="save-resv-info">保存</a>
                <a href="javascript:;" class="btn btn4 ml10 close-resv-mask">取消</a>
            </div>
        </div>
    </div>
</div>
<!--多选删除遮罩模板-->
<div class="deletemoreauto none">
    <div class="top">
        <div class="top1">
            <span class="fl">正在删除...</span>
				<span class="fr">
					<span class="num_cur">1</span>/<span class="num_total"></span>
				</span>
        </div>
        <div class="top2">
            <div class="top2a">
                <div class="top2at"></div>
            </div>
        </div>
    </div>
    <div class="content">
        <table>
            <tr><th class="zb">预定人名称</th><th class="yb">删除结果</th></tr>
            <!--<tr><td class="zb">我是auto</td><td class="yb blue">删除成功</td></tr>-->
        </table>
    </div>
</div>
<div class="tenant_List none">
    <div class="empty">
        <div class="empty-main">
            <img src="/web/images/03.png" />
            <p>当前页面没有任何数据，请<a href="javascript:;" reserveURL="{{'tenant-index/addReserve'|url}}" class="dpt-add-reserve">点击这里添加</a>！</p>
        </div>
    </div>
</div>
{{/if}}
