<div id="workerManage_Authority" hasform="true">
	<div class="workerManage_Authority">
		<div class="workerManage_Authority_A">新增权限组</div>
		<form class="authority_form" action="{{if isset($group_data)}}{{"Staffmanage-Group/edit/group_id/"|cat:$group_data.group_id|url}}{{else}}{{$form_action}}{{/if}}" target="formIframe">
		<div class="workerManage_Authority_B">
			<div class="a">
				<span class="name fl">分组名：</span><input type="text" name="group_name" value="{{if isset($group_data)}} {{$group_data.name}}{{/if}}" datatype="*" nullmsg = "请填写分组名" 
					placeholder="分组名" class="fl ipt" /><label class="chooseAll"><i class="ifont1">&#xe60c;</i></label>
						<a href="javascript:;" class="chooseAllAuto">全选</a>
								<span class="check-error check-error-ts ml5"></span>
			</div>
			<div class="b">
				<ul>
				{{foreach $modular_list[0] as $modular}}
					{{if isset($modular_list[$modular['modular_id']])}}
					<li>
						<div class="li_Head">
							<label {{if $modular.selected}}checked{{/if}}>
								<span class="choose ifont1" {{if $modular.selected}}style="display: inline;"{{/if}}>&#xe60c;</span>
							</label>
							<input type="checkbox" {{if $modular.selected}}checked{{/if}} class="exce_item"/>
							<span class="name">{{$modular.name}}</span>
						</div>
						{{foreach $modular_list[$modular['modular_id']] as $value}}
						<dl class="li_DL form_checkbox" fm-name="{{$value.mark}}">
							<dt>
								<label {{if $value.selected}}checked{{/if}}>
									<span class="choose ifont1" {{if $value.selected}}style="display: inline;"{{/if}}>&#xe60c;</span>
								</label>
								<input type="checkbox" class="exce_item" {{if $value.selected}}checked{{/if}} />
								<span class="name">{{$value.name}}</span>
							</dt>
							<dd>
								<label {{if $value['auth'][0]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $value['auth'][0]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$value.mark}}" value="0" {{if $value['auth'][0]}}checked="checked"{{/if}}/> <span class="name">增加</span>
							</dd>
							<dd>
								<label {{if $value['auth'][1]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $value['auth'][1]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$value.mark}}" value="1" {{if $value['auth'][1]}}checked="checked"{{/if}}/> <span class="name">修改</span>
							</dd>
							<dd>
								<label {{if $value['auth'][2]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $value['auth'][2]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$value.mark}}" value="2" {{if $value['auth'][2]}}checked="checked"{{/if}}/> <span class="name">删除</span>
							</dd>
							<dd>
								<label {{if $value['auth'][3]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $value['auth'][3]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$value.mark}}" value="3" {{if $value['auth'][3]}}checked="checked"{{/if}}/> <span class="name">查看</span>
							</dd>
						</dl>
						{{/foreach}}
					</li>
					{{else}}
					<li>
						<dl class="form_checkbox" fm-name="{{$modular.mark}}">
							<dt>
								<label {{if $modular.selected}}checked{{/if}}>
									<span class="choose ifont1" {{if $modular.selected}}style="display: inline;"{{/if}}>&#xe60c;</span>
								</label>
								<input type="checkbox" class="exce_item" {{if $modular.selected}}checked{{/if}} />
								<span class="name">{{$modular.name}}</span>
							</dt>
							<dd>
								<label {{if $modular['auth'][0]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $modular['auth'][0]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$modular.mark}}" value="0" {{if $modular['auth'][0]}}checked="checked"{{/if}}/> <span class="name">增加</span>
							</dd>
							<dd>
								<label {{if $modular['auth'][1]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $modular['auth'][1]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$modular.mark}}" value="1" {{if $modular['auth'][1]}}checked="checked"{{/if}}/> <span class="name">修改</span>
							</dd>
							<dd>
								<label {{if $modular['auth'][2]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $modular['auth'][2]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$modular.mark}}" value="2" {{if $modular['auth'][2]}}checked="checked"{{/if}}/> <span class="name">删除</span>
							</dd>
							<dd>
								<label {{if $modular['auth'][3]}}class="checked"{{/if}}>
								<span class="choose ifont1" {{if $modular['auth'][3]}}style="display: inline;" {{/if}}>&#xe60c;</span></label> 
								<input type="checkbox" name="{{$modular.mark}}" value="3" {{if $modular['auth'][3]}}checked="checked"{{/if}}/> <span class="name">查看</span>
							</dd>
						</dl>
					</li>
					{{/if}}
				{{/foreach}}
					<li class="lst">
						<input type="submit" class="subTriger" value="保存" />
					</li>
				</ul>
			</div>
		</div>
		</form>
		<iframe name="formIframe" style="display: none;"></iframe>
	</div>
</div>
