<!--财务管理-流水统计 s-->
<div class="finance_cost view add_expense" hasform="true">
	<div class="view-head" dataUrl="{{'finance-serial/roomsearchlandlordcon'|url}}">
		<h1>支出流水</h1>
		<!-- <i class="ifont1 mr5 ml5">&#xe65e;</i> -->
		<!-- <a href="javascript:;">打印</a> -->
	</div>
	<div class="view-con">
		<ul class="view-ul">
			<li class="cost-detail" id="li-spe">
			    {{if $not_room != 'not_room'}}
    				<b class="title-room"><i class="bit">*</i>房间：</b>
    				<b class="title-city" style="display: none;"><i class="bit">*</i>城市：</b>
    				<input type="text" class="ipt ipt-385 city-name" style="display: none;" />
				{{elseif $not_room == 'not_room'}}
    				<b class="title-city"><i class="bit">*</i>城市：</b>
    				<input type="text" class="ipt ipt-385 city-name" style="display: none;" />
				{{/if}}
				<!-- 房间退租时的支出流水,(退租客押金) -->
				{{if isset($tenancy_room_info)}}
				    {{if $tenancy_room_info.house_type == 1}}<!-- 分散式 -->
				        {{if $tenancy_room_info.rental_way == 1}}<!-- 合租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$tenancy_room_info.h_name|cat:$tenancy_room_info.room_type|cat:$tenancy_room_info.r_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{else}}<!-- 整租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$tenancy_room_info.h_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{/if}}
				    {{else}}<!-- 集中式 -->
				        <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$tenancy_room_info.f_name|cat:$tenancy_room_info.rf_floor|cat:'楼'|cat:$tenancy_room_info.rf_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{/if}}
				<!-- 业主合同添加后的支出流水(二房东从一房东手里租房) -->
				{{elseif $contract_source == 'owner_contract'}}
				    {{if $house_type == 1}}
				        <input type="text" name="serial_income[room]" class="ipt ipt-300 cost-room" value="{{$house_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{else}}
				        <input type="text" name="serial_income[room]" class="ipt ipt-300 cost-room" value="{{$house_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{/if}}
				<!-- 支出流水编辑 -->
				{{elseif isset($serial_id) && $not_room != 'not_room'}}
				    {{if $room_serial_info.house_type == 1 && $source != 'landlord_contract'}}
				        {{if $room_name.rental_way == 1}}<!-- 合租 -->
        			        <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.h_name|cat:$room_name.room_type|cat:$room_name.r_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
        			    {{else}}<!-- 整租 -->
        			        <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.h_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
        			    {{/if}}
				    {{elseif $room_serial_info.house_type == 2 && $source != 'landlord_contract'}}<!-- 集中式 -->
    				    <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.flat_name|cat:$room_name.rf_floor|cat:'楼'|cat:$room_name.rf_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{elseif $source == 'landlord_contract'}}<!-- 业主合同 -->
    				    <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.h_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{/if}}
				<!-- 首页代办提醒(二房东交租) -->
				{{elseif isset($landlord_contract_id)}}
				    <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$landlord_con_info.house_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				<!-- 业主合同支付 -->
				{{elseif $lc_contract == 'lc_pay'}}
				    <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$house_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				<!-- 房间退订 -->
				{{elseif $ns_source == 'unsubscribe'}}
				    {{if $reserve_room_info.house_type == 1}}<!-- 分散式 -->
				        {{if $room_name.rental_way == 1}}<!-- 合租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.h_name|cat:$room_name.room_type|cat:$room_name.r_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{else}}<!-- 整租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.h_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{/if}}
				    {{else}}<!-- 集中式 -->
				        <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_name.flat_name|cat:$room_name.floor|cat:'楼'|cat:$room_name.rf_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{/if}}
				<!-- 终止租客合同 -->
				{{elseif $tc_stop_contract == 'tc_stop_contract'}}
				    {{if $room_info.house_type == 1}}<!-- 分散式 -->
				        {{if $room_info.rental_way == 1}}<!-- 合租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_info.h_name|cat:$room_info.room_type|cat:$room_info.r_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{else}}<!-- 整租 -->
				            <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_info.h_name}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				        {{/if}}
				    {{else}}<!-- 集中式 -->
				        <input type="text" name="serial_income[room]" class="ipt ipt-385 cost-room" value="{{$room_info.flat_name|cat:$room_info.floor|cat:'楼'|cat:$room_info.rf_custom_num|cat:'号'}}" placeholder="高新区-楠香山-1栋2单元2703" datatype="*" nullmsg="请输入房间名称" />
				    {{/if}}
				{{elseif $not_room == 'not_room'}}
				<!-- 非房间流水 -->
				    <input type="text" name="serial_income[room]" disabled="disabled" class="ipt ipt-385 cost-room" value="{{$not_room_data[0].name}}" placeholder="高新区-楠香山-1栋2单元2703" />
				{{else}}
				<!-- 新增支出流水 -->
				    <input type="text" name="serial_income[room]" url="{{'finance-serial/wordSearchRoom'|url}}" class="ipt ipt-385 cost-room" value="" sub_tenancy="add" placeholder="高新区-楠香山-1栋2单元2703" datatype="cost_room" nullmsg="请输入房间名称" />
				{{/if}}
                <!-- 判断是否勾选 和 显示 非房间流水 -->
				{{if !isset($serial_id) && !isset($debts_info) && !isset($reserve_id) && !isset($contract_id) && !isset($meter) && !isset($index_tenant_con_id) && $not_room != 'not_room'}}
    				<div class="check-box">
    					<label><i class="choose ifont1">&#xe60c;</i></label>
        				<input type="checkbox" value=""style="display: none;" />
    					<span>非房间产生的流水</span>
    				</div>
    				<span class="check-error check-error-ts"></span>
    			{{elseif $not_room == 'not_room'}}
    				<div class="check-box li-spe-checkbox">
                        <label class="checked"><i class="choose ifont1" style="display: inline;">&#xe60c;</i></label>
                        <input type="checkbox" value="" style="display: none;" checked="checked"/>
    					<span>非房间产生的流水</span>
    				</div>
    				<span class="check-error check-error-ts" style="display: block;"></span>
				{{/if}}
			</li>
			
			<!--根据房源名字拉费用数据 s-->
			<div id="get_cost_expense"></div>
			
			<script type="text/html" id="cost_mode_expense">
				{{'<% for (var i = 0; i < data.length; i ++) { %>'}}
				<li class="cost-detail cost-detail-con" sn_id="{{$serial_id}}" detail_id="{{$fee_list.sd_id}}">
					<div class="cd-t">
						<b><i class="bit"></i>费用：</b>
						<div class="selectByM slt-180" hasevent="true">
							<input type="text" name="" class="selectByMT cost_type" readonly="readonly" selectVal="{{'<%=data[i].fee_type_id%>'}}" value="{{'<%=data[i].type_name%>'}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
						            <li selectVal = "{{$list_fee.fee_type_id}}" class="selectedLi"></li>
						            <li selectVal = "{{$list_fee.fee_type_id}}"></li>
								</ul>
							</div>
						</div>
						<b class="dte-40">金额：</b>
						<input type="text" name="" value="{{'<%=data[i].money%>'}}" class="ipt ipt-80 cost_num" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
					</div>
					<div class="cd-b">
						<b><i class="bit"></i>费用：</b>
						<span class="cdb-con">冲减租金</span>
						<b>金额：</b>
						<input type="text" name="" class="ipt ipt-80" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;">删除</a>
					</div>
				</li>
				{{'<%}%>'}}
			</script>
			<!--根据房源名字拉费用数据 e-->
			
			
<!-- 编辑支出流水 -->
			{{if isset($serial_id)}}
    			{{foreach from=$room_fee_info item=fee_list key=k}}
    				<li class="cost-detail cost-detail-con" sn_id="{{$serial_id}}" detail_id="{{$fee_list.sd_id}}">
    					<div class="cd-t">
    						<b><i class="bit"></i>费用：</b>
    						<div class="selectByM slt-180" hasevent="true">
    							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$fee_list.fee_type_id}}' value="{{$fee_list.type_name}}"/>
    							<span class='jt_Ctr'><span class='jt_box'></span></span>
    							<div class="selectByMO">
    								<ul>
    								    {{foreach from=$room_fee_info item=list_fee}}
    								        {{if $fee_list.fee_type_id == $list_fee.fee_type_id}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}" class="selectedLi">{{$list_fee.type_name}}</li>
    								        {{else}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}">{{$list_fee.type_name}}</li>
    								        {{/if}}
    								    {{/foreach}}
    								</ul>
    							</div>
    						</div>
    						<b class="dte-40">金额：</b>
    						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{if isset($fee_list.sd_money)}}{{$fee_list.sd_money}}{{/if}}" class="ipt ipt-80 cost_num" placeholder="1500" />
    						<span class="ml10">元</span>
    						<i class="ifont dte-30">&#xe675;</i>
    						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
    					</div>
    					<!--点击冲账更改保存后才显示 s-->
    					<div class="cd-b">
    						<b><i class="bit"></i>费用：</b>
    						<span class="cdb-con">冲减租金</span>
    						<b>金额：</b>
    						<input type="text" name="serial_income[fee_offset{{$k}}]" class="ipt ipt-80" placeholder="1500" />
    						<span class="ml10">元</span>
    						<i class="ifont dte-30">&#xe675;</i>
    						<a href="javascript:;">删除</a>
    					</div>
    					<!--点击冲账更改保存后才显示 s-->
    				</li>
    			{{/foreach}}
			{{/if}}
<!-- 添加业主合同 含有(押金/租金)-->
			{{if $contract_source == 'owner_contract'}}
    			{{foreach from=$landlord_fee item=fee_list key=k}}
    				<li class="cost-detail cost-detail-con" uid="">
    					<div class="cd-t">
    						<b><i class="bit"></i>费用：</b>
    						<div class="selectByM slt-180" hasevent="true">
    							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$fee_list.fee_type_id}}' value="{{$fee_list.type_name}}"/>
    							<span class='jt_Ctr'><span class='jt_box'></span></span>
    							<div class="selectByMO">
    								<ul>
    								    {{foreach from=$landlord_fee item=list_fee}}
    								        {{if $fee_list.fee_type_id == $list_fee.fee_type_id}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}" class="selectedLi">{{$list_fee.type_name}}</li>
    								        {{else}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}">{{$list_fee.type_name}}</li>
    								        {{/if}}
    								    {{/foreach}}
    								</ul>
    							</div>
    						</div>
    						<b class="dte-40">金额：</b>
    						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$fee_list.money}}" class="ipt ipt-80 cost_num" placeholder="1500" />
    						<span class="ml10">元</span>
    						<i class="ifont dte-30">&#xe675;</i>
    						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
    					</div>
    				</li>
        	    {{/foreach}}
			{{/if}}
<!-- 房间退租, 支出流水 -->
			{{if isset($tenancy_room_info)}}
				<li class="cost-detail cost-detail-con" uid="">
					<div class="cd-t">
						<b><i class="bit"></i>费用：</b>
						<div class="selectByM slt-180" hasevent="true">
							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$deposit_fee.fee_type_id}}' value="{{$deposit_fee.type_name}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
							        <li selectVal = "{{$deposit_fee.fee_type_id}}" class="selectedLi">{{$deposit_fee.type_name}}</li>
								</ul>
							</div>
						</div>
						<b class="dte-40">金额：</b>
						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$tenancy_room_info.deposit}}" class="ipt ipt-80 cost_num" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
					</div>
					<!--点击冲账更改保存后才显示 s-->
					<div class="cd-b">
						<b><i class="bit"></i>费用：</b>
						<span class="cdb-con">冲减租金</span>
						<b>金额：</b>
						<input type="text" name="serial_income[fee_offset{{$k}}]" class="ipt ipt-80" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;">删除</a>
					</div>
					<!--点击冲账更改保存后才显示 s-->
				</li>
			{{/if}}
<!-- 首页代办提醒(二房东交租) -->
			{{if isset($landlord_contract_id)}}
                {{foreach from=$landlord_con_fee item=fee_list key=k}}
    				<li class="cost-detail cost-detail-con" uid="">
    					<div class="cd-t">
    						<b><i class="bit"></i>费用：</b>
    						<div class="selectByM slt-180" hasevent="true">
    							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$fee_list.fee_type_id}}' value="{{$fee_list.type_name}}"/>
    							<span class='jt_Ctr'><span class='jt_box'></span></span>
    							<div class="selectByMO">
    							    {{foreach from=$landlord_con_fee item=fee}}
    								<ul>
    							        <li selectVal = "{{$fee.fee_type_id}}" class="selectedLi">{{$fee.type_name}}</li>
    								</ul>
    								{{/foreach}}
    							</div>
    						</div>
    						<b class="dte-40">金额：</b>
    						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$landlord_con_info.next_pay_money}}" class="ipt ipt-80 cost_num" placeholder="1500" />
    						<span class="ml10">元</span>
    						<i class="ifont dte-30">&#xe675;</i>
    						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
    					</div>
    				</li>
                {{/foreach}}
			{{/if}}
<!-- 业主合同支付 -->
			{{if $lc_contract == 'lc_pay'}}
    			{{foreach from=$lc_contract_fee item=fee_list key=k}}
    				<li class="cost-detail cost-detail-con" uid="">
    					<div class="cd-t">
    						<b><i class="bit"></i>费用：</b>
    						<div class="selectByM slt-180" hasevent="true">
    							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$fee_list.fee_type_id}}' value="{{$fee_list.type_name}}"/>
    							<span class='jt_Ctr'><span class='jt_box'></span></span>
    							<div class="selectByMO">
    								<ul>
    								    {{foreach from=$landlord_fee item=list_fee}}
    								        {{if $fee_list.fee_type_id == $list_fee.fee_type_id}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}" class="selectedLi">{{$list_fee.type_name}}</li>
    								        {{else}}
    								            <li selectVal = "{{$list_fee.fee_type_id}}">{{$list_fee.type_name}}</li>
    								        {{/if}}
    								    {{/foreach}}
    								</ul>
    							</div>
    						</div>
    						<b class="dte-40">金额：</b>
    						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$fee_list.money}}" class="ipt ipt-80 cost_num" placeholder="1500" />
    						<span class="ml10">元</span>
    						<i class="ifont dte-30">&#xe675;</i>
    						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
    					</div>
    				</li>
        	    {{/foreach}}
			{{/if}}
<!-- 房间退订 -->
			{{if $ns_source == 'unsubscribe'}}
                <li class="cost-detail cost-detail-con" uid="">
					<div class="cd-t">
						<b><i class="bit"></i>费用：</b>
						<div class="selectByM slt-180" hasevent="true">
							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$unsubscribe_fee.fee_type_id}}' value="{{$unsubscribe_fee.type_name}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
							        <li selectVal = "{{$unsubscribe_fee.fee_type_id}}" class="selectedLi">{{$unsubscribe_fee.type_name}}</li>
								</ul>
							</div>
						</div>
						<b class="dte-40">金额：</b>
						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$unsubscribe_fee.money}}" class="ipt ipt-80 cost_num" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
					</div>
				</li>
			{{/if}}
<!-- 非房间流水 -->
			{{if $not_room == 'not_room'}}
                {{foreach from=$not_room_data item=fee_list key=k}}
    				<li class="cost-detail cost-detail-con" sn_id="{{$serial_id}}" detail_id="{{$fee_list.sd_id}}">
    					<div class="cd-t">
    						<b><i class="bit"></i>费用：</b>
    						<div class="selectByM slt-180" hasevent="true">
    							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$fee_list.fee_type_id}}' value="{{$fee_list.type_name}}"/>
    							<span class='jt_Ctr'><span class='jt_box'></span></span>
    							<div class="selectByMO">
    								<ul>
    								    {{foreach from=$fee_type_list key=key item=fee}}
    								        {{if $fee_list.fee_type_id == $fee.fee_type_id}}
    								            <li selectVal = "{{$fee.fee_type_id}}" class="selectedLi">{{$fee.type_name}}</li>
    								        {{else}}
    								            <li selectVal = "{{$fee.fee_type_id}}">{{$fee.type_name}}</li>
    								        {{/if}}
    								    {{/foreach}}
    								</ul>
    							</div>
    						</div>
    						<b class="dte-40">金额：</b>
    						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{if isset($fee_list.sd_money)}}{{$fee_list.sd_money}}{{/if}}" class="ipt ipt-80 cost_num" placeholder="1500" datatype="cost_num" nullmsg="请填写费用金额" errormsg="费用金额格式错误" />
    						<span class="ml10">元</span>
    					</div>
    				</li>
    			{{/foreach}}
			{{/if}}
<!-- 终止租客合同 -->
			{{if $tc_stop_contract == 'tc_stop_contract'}}
                <li class="cost-detail cost-detail-con" uid="">
					<div class="cd-t">
						<b><i class="bit"></i>费用：</b>
						<div class="selectByM slt-180" hasevent="true">
							<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '{{$stop_contract_fee.fee_type_id}}' value="{{$stop_contract_fee.type_name}}"/>
							<span class='jt_Ctr'><span class='jt_box'></span></span>
							<div class="selectByMO">
								<ul>
							        <li selectVal = "{{$stop_contract_fee.fee_type_id}}" class="selectedLi">{{$stop_contract_fee.type_name}}</li>
								</ul>
							</div>
						</div>
						<b class="dte-40">金额：</b>
						<input type="text" name="serial_income[fee_sum{{$k}}]" value="{{$stop_contract_fee.money}}" class="ipt ipt-80 cost_num" placeholder="1500" />
						<span class="ml10">元</span>
						<i class="ifont dte-30">&#xe675;</i>
						<a href="javascript:;" url="{{'Finance-serial/deleteFee'|url}}" class="cd-btn">删除</a>
					</div>
				</li>
			{{/if}}
		</ul>
	</div>
	
	<div class="view-con cost-add">
		<ul>
			<li class="view-add-cost">
				<i class="ifont">&#xf0037;</i>
				<a href="javascript:;" class="add-cost">添加费用</a>
			</li>
			<li>
				<b class="pay-ways"><i class="bit">*</i>交易时间：</b>
				{{if isset($serial_id) && $not_room != 'not_room'}}<!-- 编辑房间流水 -->
				    <input type="text" name="serial_income[pay_time]" class="ipt ipt-200 date cost-time mr5" readonly="readonly" value="{{$room_serial_info.pay_time|date_format:"%Y-%m-%d"}}" datatype="*" nullmsg="请填写时间" />
				{{elseif $not_room == 'not_room'}}<!-- 非房间流水 -->
				    <input type="text" name="serial_income[pay_time]" class="ipt ipt-200 date cost-time mr5" readonly="readonly" value="{{$not_room_data[0].pay_time|date_format:"%Y-%m-%d"}}" datatype="*" nullmsg="请填写时间" />
				{{else}}
				    <input type="text" name="serial_income[pay_time]" class="ipt ipt-200 date cost-time mr5" readonly="readonly" value="" datatype="*" nullmsg="请填写时间" />
				{{/if}}
				<b class="dte-65 pay-ways"><i class="bit">*</i>支付方式：</b>
				<div class="selectByM slt-200">
				    {{if isset($serial_id) && $not_room != 'not_room'}}
					    <input type="text" name="serial_income[pay_type]" class="selectByMT centralized_Ind_CuteType cost-ways" readonly = 'readonly' selectVal = '{{$room_serial_info.payment_mode}}' value="{{$room_serial_info.payment_mode}}" datatype="costWays" nullmsg="请选择支付方式" />
					{{elseif $not_room == 'not_room'}}
					    <input type="text" name="serial_income[pay_type]" class="selectByMT centralized_Ind_CuteType cost-ways" readonly = 'readonly' selectVal = '{{$not_room_data[0].payment_mode}}' value="{{$not_room_data[0].payment_mode}}" datatype="costWays" nullmsg="请选择支付方式" />
					{{else}}
					    <input type="text" name="serial_income[pay_type]" class="selectByMT centralized_Ind_CuteType cost-ways" readonly = 'readonly' selectVal = '0' value="" datatype="costWays" nullmsg="请选择支付方式" />
					{{/if}}
					<span class='jt_Ctr'><span class='jt_box'></span></span>
					<div class="selectByMO">
						<ul>
						    {{foreach from=$pay_type item=val}}
							<li selectVal = {{$val}}>{{$val}}</li>
							{{/foreach}}
						</ul>
					</div>
				</div>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="mark">
				<b>备注：</b>
				{{if isset($serial_id) && $not_room != 'not_room'}}<!-- 流水编辑 -->
				    <textarea name="serial_income[remark]" class="i-txt">{{$room_serial_info.remark}}</textarea>
				{{elseif $not_room == 'not_room'}}
				    <textarea name="serial_income[remark]" class="i-txt">{{$not_room_data[0].remark}}</textarea>
				{{else}}
				    <textarea name="serial_income[remark]" class="i-txt"></textarea>
				{{/if}}
			</li>
		</ul>
	</div>
	
	<div class="view-con cost-total">
		<ul>
			<li>
				<b>共计支付：</b>
				<span name="receivable" flag="edit" class="red receivable"></span>
				<b>元</b>
			</li>
		</ul>
	</div>
	
	<div class="view-btn">
	    {{if isset($serial_id)}}
    		<a href="javascript:;" sub_tenancy="editExpense" sn_id="{{$serial_id}}" url="{{'Finance-serial/editExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
    	<!-- 添加业主合同 -->
	    {{elseif $contract_source == 'owner_contract'}}
    		<a href="javascript:;" sub_tenancy="owner_contract" contract_id="{{$contract_id}}" house_type="{{$house_type}}" house_id="{{$house_id}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
    	<!-- 房间退租 -->
	    {{elseif $out_tenancy == 'out_tenancy'}}
    		<a href="javascript:;" sub_tenancy="out_tenancy" house_id="{{$house_id}}" room_id="{{$room_id}}" room_focus_id="{{$room_focus_id}}" house_type="{{$house_type}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
        <!-- 首页代办提醒(二房东交租) -->
        {{elseif isset($landlord_contract_id)}}
    		<a href="javascript:;" sub_tenancy="landlord_con" contract_id="{{$landlord_contract_id}}" house_id="{{$landlord_con_info.house_id}}" house_type="{{$landlord_con_info.house_type}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
    	<!-- 业主合同支付 -->
        {{elseif $lc_contract == 'lc_pay'}}
    		<a href="javascript:;" sub_tenancy="lc_pay" contract_id="{{$contract_id}}" house_type="{{$house_type}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
    	<!-- 房间退订 -->
        {{elseif $ns_source == 'unsubscribe'}}
    		<a href="javascript:;" sub_tenancy="unsubscribe" reserve_id="{{$reserve_room_info.reserve_id}}" house_id="{{$reserve_room_info.house_id}}" room_id="{{$reserve_room_info.room_id}}" house_type="{{$reserve_room_info.house_type}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
        <!-- 终止租客合同 -->
        {{elseif $tc_stop_contract == 'tc_stop_contract'}}
    		<a href="javascript:;" sub_tenancy="tc_stop_contract" tc_contract_id="{{$tc_contract_id}}" house_id="{{$rental_data.house_id}}" room_id="{{$rental_data.room_id}}" house_type="{{$rental_data.house_type}}" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
        {{else}}
    		<a href="javascript:;" url="{{'Finance-serial/addExpense'|url}}" class="btn btn2 add-expense-btn">保存</a>
        {{/if}}
		<a href="javascript:;" class="btn btn4 cancel btn-cancel">取消</a>
	</div>
</div>
<!--财务管理-流水统计 e-->

<!--冲账功能弹窗 s-->
<div id="hide-checkout" class="none">
	<div class="checkout-con">
		<ul>
			<li>
				<b><i>*</i>授权密码：</b>
				<input type="password" name="strike[pass]" class="ipt ipt-250 auth_pwd" datatype="*6-18" nullmsg="请填写密码" errormsg="密码由6到18位字符组成" />
				<!--<span>默认是系统初始密码，可点击<a href="javascript:;" class="edit-pwd">修改密码</a></span>-->
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i></i>当前金额：</b>
				<input type="text" name="strike[current_sum]" class="ipt ipt-250 cur_num" readonly="readonly" />
			</li>
			<li>
				<b><i>*</i>冲账金额：</b>
				<input type="text" name="strike[balance_sum]" class="ipt ipt-250 checkout-con-num" placeholder="最大金额为当前金额" datatype="n" nullmsg="请填写冲账金额" errormsg="冲账金额格式不正确" />
				<span class="check-error check-error-ts"></span>
			</li>
			<li>
				<b><i>*</i>备　　注：</b>
				<textarea name="strike[balance_mark]" class="i-txt" datatype="*" nullmsg="请填写冲账金额"></textarea>
				<span class="check-error check-error-ts"></span>
			</li>
			<li class="checkout-btn">
				<a href="javascript:;" class="btn btn2">保存</a>
				<a href="javascript:;" class="btn btn4 cancel-btn">取消</a>
			</li>
		</ul>
	</div>
</div>
<!--冲账功能弹窗 s-->

<!--添加费用模板 s-->
<div id="cost" style="display: none;">
	<li class="cost-detail cost-col-detail" uid="">
		<div class="cd-t">
			<b><i class="bit"></i>费用：</b>
			<div class="selectByM slt-180" hasevent="true">
				<input type="text" name="serial_income[fee_type{{$k}}]" class="selectByMT cost_type" readonly = 'readonly' selectVal = '' value="" datatype="cost_type" nullmsg="请选择费用类型" />
				<span class='jt_Ctr'><span class='jt_box'></span></span>
				<div class="selectByMO">
					<ul>
					    {{foreach from=$fee_type_list item=list_fee}}
					        <li selectVal = "{{$list_fee.fee_type_id}}">{{$list_fee.type_name}}</li>
					    {{/foreach}}
					</ul>
				</div>
			</div>
			<b class="dte-40">金额：</b>
			<input type="text" name="serial_income[fee_sum{{$k}}]" class="ipt ipt-80 cost_num" datatype="cost_num" nullmsg="请填写费用金额" errormsg="费用金额格式错误" />
			<span class="ml10">元</span>
			<i class="ifont dte-30">&#xe675;</i>
			<a href="javascript:;" class="cd-btn">删除</a>
			<span class="check-error check-error-ts"></span>
		</div>
		<!--点击冲账更改保存后才显示 s-->
		<div class="cd-b">
			<b><i class="bit"></i>费用：</b>
			<span class="cdb-con">冲减租金</span>
			<b>金额：</b>
			<input type="text" name="serial_income[fee_offset{{$k}}]" class="ipt ipt-80" placeholder="1500" />
			<span class="ml10">元</span>
			<i class="ifont dte-30">&#xe675;</i>
			<a href="javascript:;">删除</a>
		</div>
		<!--点击冲账更改保存后才显示 s-->
	</li>
</div>
<!--添加费用模板 e-->
